const REF='/api/reference-image';
const M={breaking:['Breaking AI News','The newest high-signal AI announcements and developments as they appear.',[]],chatgpt:['ChatGPT & OpenAI','OpenAI, ChatGPT, Codex, Sora, agents and model releases.',['openai','chatgpt','gpt','codex','sora']],claude:['Claude & Anthropic','Anthropic, Claude models, Claude Code, research and product updates.',['anthropic','claude']],gemini:['Gemini & Google AI','Gemini, Google DeepMind and Google AI product announcements.',['gemini','google','deepmind']],'ai-models':['AI Models','New frontier and open-weight language, reasoning and multimodal models.',['model','llm','reasoning','multimodal','llama','qwen','mistral','deepseek']],'ai-video':['AI Video','Generative video, editing models and creative video tools.',['video','sora','veo','runway','kling','luma']],'ai-images':['AI Images','Image generation, editing, design models and visual AI tools.',['image','midjourney','flux','stable diffusion','visual']],coding:['AI Coding','Coding agents, developer tools, IDE assistants and software-generation models.',['code','coding','developer','github','copilot','cursor','codex']],hardware:['AI Hardware','GPUs, accelerators, data centers, chips and AI infrastructure.',['nvidia','amd','intel','gpu','chip','compute','data center']],robotics:['AI Robotics','Humanoid robots, autonomous systems and embodied AI.',['robot','robotics','humanoid','autonomous']],business:['AI Business','Funding, acquisitions, partnerships, enterprise AI and market moves.',['funding','valuation','business','enterprise','revenue','deal','startup']],'all-news':['All AI News','A single feed containing every AI story collected by AI News Now.',[]]};
const F=[['Anthropic signs massive $45 billion AI-compute agreement with Nscale','https://techcrunch.com/2026/08/26/anthropic-continues-compute-gobbling-streak-in-45-billion-deal-with-nscale/','TechCrunch',12,'The six-year deal will provide Anthropic with up to 1 gigawatt of compute capacity using Nvidia’s next-gen infrastructure.'],['NVIDIA Q2 revenue hits $96.2B beating Wall Street estimates','https://www.nvidia.com/en-us/','NVIDIA',28,'Data center revenue continues to surge as AI chip demand grows.'],['Google adds new memory and personalization to Gemini Live','https://blog.google/technology/ai/','Google',45,'New Gemini features make conversations more natural and context-aware.'],['OpenAI hints at new reasoning model arriving this fall','https://openai.com/news/','OpenAI',60,'OpenAI continues advancing reasoning systems and AI agents.'],['Meta open-sources Llama 4 Behemoth','https://ai.meta.com/','Meta',120,'Meta continues investing in open model development and research.'],['Runway Gen-3 Alpha now available','https://runwayml.com/','Runway',135,'Generative video tools continue to improve creative workflows.'],['Microsoft integrates AI into Windows 12','https://www.microsoft.com/en-us/ai','Microsoft',180,'AI capabilities are expanding across the desktop experience.']].map((x,i)=>({id:'f'+i,title:x[0],link:x[1],source:x[2],publishedAt:new Date(Date.now()-x[3]*60000).toISOString(),description:x[4]}));
const e=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=x=>{let m=Math.max(1,Math.floor((Date.now()-new Date(x))/60000));return m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
function crop(box,cls=''){const [x,y,w,h]=box;return `<span class="crop ${cls}"><svg viewBox="${x} ${y} ${w} ${h}" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><image href="${REF}" x="0" y="0" width="512" height="432" preserveAspectRatio="none"/></svg></span>`}
const BOX={"hero":[2,2,312,239],"nvidia":[316,2,123,113],"gemini":[2,243,124,113],"openai":[128,243,124,113],"meta":[254,243,127,113],"bot":[383,243,57,62],"p2":[442,243,45,37],"p3":[2,358,45,37],"p4":[49,358,45,37],"anthropicT":[96,358,41,36],"nvidiaT":[139,358,41,36],"geminiT":[182,358,41,36],"openaiT":[225,358,41,36],"metaT":[268,358,41,36],"p1":[311,358,45,36],"p5":[358,358,45,36],"magai":[405,358,26,33],"opus":[433,358,29,33],"codestral":[464,358,29,33],"leonardo":[2,397,29,33],"voicemod":[33,397,29,33]};
function text(n){return (n.title+' '+n.description+' '+n.source).toLowerCase()}
function imgKey(n,i=0){let t=text(n);if(t.includes('nvidia')||t.includes('gpu')||t.includes('chip'))return'nvidia';if(t.includes('gemini')||t.includes('google'))return'gemini';if(t.includes('openai')||t.includes('chatgpt')||t.includes('gpt'))return'openai';if(t.includes('meta')||t.includes('llama'))return'meta';return['nvidia','gemini','openai','meta'][i%4]}
function thumbKey(n,i=0){let t=text(n);if(t.includes('anthropic')||t.includes('claude'))return'anthropicT';if(t.includes('nvidia')||t.includes('gpu')||t.includes('chip'))return'nvidiaT';if(t.includes('gemini')||t.includes('google'))return'geminiT';if(t.includes('openai')||t.includes('chatgpt')||t.includes('gpt'))return'openaiT';if(t.includes('meta')||t.includes('llama'))return'metaT';return['anthropicT','nvidiaT','geminiT','openaiT','metaT'][i%5]}
function card(n,i=0){let k=imgKey(n,i);return `<article class="card"><div class="art">${crop(BOX[k])}</div><div class="body"><div class="meta">${e(n.source)} · ${ago(n.publishedAt)}</div><h3>${e(n.title)}</h3><p>${e(n.description)}</p><div class="foot"><a href="${e(n.link)}" target="_blank" rel="noreferrer">${e(n.source)} · Read source ↗</a><span>♡</span></div></div></article>`}
async function news(){try{let r=await fetch('/api/news',{cache:'no-store'});if(!r.ok)throw 0;let j=await r.json();return j.news?.length?j.news:F}catch{return F}}
function pick(n,terms,fallback){let hit=n.find(x=>terms.some(t=>text(x).includes(t)));return hit||fallback}
function home(n){
  let rawHero=pick(n,['nscale','45b','anthropic'],F[0]);
  let hero=rawHero.link&&rawHero.link.includes('nscale')?{...rawHero,title:'Anthropic signs massive $45 billion AI-compute agreement with Nscale',description:'The six-year deal will provide Anthropic with up to 1 gigawatt of compute capacity using Nvidia’s next-gen infrastructure.'}:rawHero;
  let latest=[pick(n,['nvidia'],F[1]),pick(n,['gemini'],F[2]),pick(n,['openai'],F[3]),pick(n,['meta','llama'],F[4])];
  let seen=new Set([rawHero.link,...latest.map(x=>x.link)]);let pop=n.filter(x=>!seen.has(x.link)).slice(0,5);while(pop.length<5)pop.push(F[(pop.length+1)%F.length]);
  let br=n.slice(0,5);if(br.length<5)br=[...n,...F].slice(0,5);
  let tr=['Claude','Nvidia Earnings','Gemini','Sora','AI Agents'];
  let pboxes=['p1','p2','p3','p4','p5'];
  return `<main class="dashboard">
    <aside class="left">
      <section class="panel breaking"><div class="pt"><span>🔥 BREAKING NEWS</span><a href="/breaking/">View all</a></div>${br.map((x,i)=>`<a class="breakitem" href="${e(x.link)}" target="_blank"><div><small>${ago(x.publishedAt)} • ${e(x.source)}</small><strong>${e(x.title)}</strong></div><span class="thumb">${crop(BOX[thumbKey(x,i)])}</span></a>`).join('')}<a class="railbtn" href="/breaking/">View all breaking news →</a></section>
      <section class="panel"><div class="pt"><span>📈 TRENDING TOPICS</span><a href="/all-news/">View all</a></div>${tr.map((x,i)=>`<a class="trend" href="/search/?q=${encodeURIComponent(x)}"><span class="rank">${i+1}</span><div><strong>${x}</strong><small>Trending now</small></div><span class="spark">⌁⌁⌁</span></a>`).join('')}</section>
    </aside>
    <section class="center">
      <article class="hero"><div class="hcopy"><span class="tag">JUST IN</span><h1>${e(hero.title)}</h1><p>${e(hero.description)}</p><div class="hmeta">${ago(hero.publishedAt)} • <b>${e(hero.source)}</b></div></div><div class="visual">${crop(BOX.hero)}</div><a class="herolink" href="${e(hero.link)}" target="_blank" rel="noreferrer"></a><span class="arr l">‹</span><span class="arr r">›</span><span class="dots"><i></i><i></i><i></i><i></i><i></i><i></i></span></article>
      <div class="sh"><h2>LATEST AI NEWS</h2><a href="/all-news/">View all →</a></div><div class="grid">${latest.map(card).join('')}</div>
    </section>
    <aside class="right">
      <section class="panel daily"><div class="bot">${crop(BOX.bot)}</div><h3>DAILY AI BRIEF</h3><p class="date">${new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric'}).format(new Date())}</p><p>5 major stories, top tools, and important updates in AI today.</p><a class="bluebtn" href="/breaking/">Read Today's Brief →</a></section>
      <section class="panel"><div class="pt"><span>POPULAR NEWS</span><a href="/all-news/">View all</a></div>${pop.map((x,i)=>`<a class="pop" href="${e(x.link)}" target="_blank"><b>${i+1}</b><div><strong>${e(x.title)}</strong><small>${(2.3-i*.28).toFixed(1)}K reads</small></div><span class="pimg">${crop(BOX[pboxes[i]])}</span></a>`).join('')}</section>
    </aside>
    <section class="panel tools"><div class="pt"><span>NEW AI TOOLS</span><a href="/ai-models/">View all →</a></div><div class="toolrow">${[['Magai','AI Presentation Maker','magai'],['OpusClip 2.0','AI Video Editor','opus'],['Codestral','AI Coding Assistant','codestral'],['Leonardo AI','Image Generation','leonardo'],['Voicemod AI','Voice Changer','voicemod']].map(([a,b,k])=>`<a class="tool" href="/search/?q=${encodeURIComponent(a)}"><span class="toolicon">${crop(BOX[k])}</span><span><strong>${a}</strong><small>${b}</small></span><b>NEW</b></a>`).join('')}</div></section>
  </main>`
}
function section(n,key){let q=new URLSearchParams(location.search).get('q')||'',m=M[key]||M['all-news'],title=m[0],desc=m[1],ks=m[2],items=n;if(key==='breaking')items=n.slice(0,24);else if(key==='search'){title=q?`Search: “${q}”`:'Search AI News';desc=q?`Live results matching ${q}.`:'Use the search box to find companies, models, tools and topics.';items=q?n.filter(x=>text(x).includes(q.toLowerCase())):n}else if(key!=='all-news')items=n.filter(x=>ks.some(k=>text(x).includes(k)));return `<main class="section"><div class="sectionhero"><div><a class="back" href="/">← AI News Now</a><span class="live">● LIVE FEED</span><h1>${e(title)}</h1><p>${e(desc)}</p></div><div class="stat"><strong>${items.length}</strong><span>stories loaded</span><small>Refreshes automatically</small></div></div>${items.length?`<div class="sectiongrid">${items.map(card).join('')}</div>`:`<div class="simple"><div class="box"><h2>No matching live stories right now.</h2><p>The collector will add matching articles automatically as new RSS items arrive.</p><a href="/all-news/">Browse all AI news</a></div></div>`}</main>`}
function special(key){if(key==='about')return `<main class="simple"><section class="box"><span class="tag">ABOUT</span><h1>One place for everything happening in AI.</h1><p>AI News Now reads public RSS feeds on the server, removes obvious duplicates, sorts stories by recency and sends readers to the original publisher for the full article.</p><h2>No paid news API required</h2><p>The collector uses public feeds and a 15-minute cache. If a feed is temporarily unavailable, fallback headlines keep the interface usable until the next refresh.</p><h2>Respectful aggregation</h2><p>We show short summaries and attribution instead of republishing complete copyrighted articles.</p></section></main>`;if(key==='subscribe')return `<main class="simple"><section class="box"><h1>Newsletter</h1><p>The Subscribe button has been removed from the website header. This route is kept only so old bookmarks do not break.</p><a href="/">← Back to AI News Now</a></section></main>`}
document.querySelector('.search').onsubmit=x=>{x.preventDefault();let q=x.currentTarget.querySelector('input').value.trim();if(q)location.href='/search/?q='+encodeURIComponent(q)};
document.getElementById('theme').onclick=()=>document.documentElement.classList.toggle('light');
let key=location.pathname.split('/').filter(Boolean)[0]||'home';document.querySelectorAll('.nav a').forEach(a=>{let p=a.getAttribute('href').split('/').filter(Boolean)[0]||'home';if(p===key)a.classList.add('active')});
(async()=>{let app=document.getElementById('app');if(key==='about'||key==='subscribe'){app.className='';app.innerHTML=special(key);return}let n=await news();app.className='';app.innerHTML=key==='home'?home(n):section(n,key)})();
