(()=>{
const key=location.pathname.split('/').filter(Boolean)[0]||'home';if(key!=='home'&&key!=='breaking')return;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=x=>{const m=Math.max(1,Math.floor((Date.now()-new Date(x))/60000));return m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
function img(n,cls='news-img'){return `<img class="${cls}" src="${esc(n.image)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer">`}
function card(n){return `<article class="card"><a class="art" href="${esc(n.link)}" target="_blank" rel="noreferrer">${img(n)}</a><div class="body"><div class="meta">${esc(n.source)} · ${ago(n.publishedAt)}</div><h3><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.title)}</a></h3><p>${esc(n.description)}</p><div class="foot"><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.source)} · Read source ↗</a><span>♡</span></div></div></article>`}
function rail(items){const p=document.querySelector('.panel.breaking');if(!p)return false;const top=items.slice(0,5);p.innerHTML=`<div class="pt"><span>🔥 BREAKING NEWS</span><a href="/breaking/">View all</a></div>${top.map(n=>`<a class="breakitem" href="${esc(n.link)}" target="_blank" rel="noreferrer"><div><small>${ago(n.publishedAt)} • ${esc(n.source)}</small><strong>${esc(n.title)}</strong></div><span class="thumb">${img(n,'thumb-img')}</span></a>`).join('')}<a class="railbtn" href="/breaking/">View all breaking news →</a>`;return true}
function page(items){const app=document.getElementById('app');if(!app)return;app.className='';app.innerHTML=`<main class="section"><div class="sectionhero"><div><a class="back" href="/">← AI News Now</a><span class="live">● LIVE · REFRESHES EVERY 2 MINUTES</span><h1>Major Breaking Technology News</h1><p>High-impact live coverage across AI, IT, cybersecurity, cloud, hardware, outages, vulnerabilities, major product launches, regulation, acquisitions and other important technology developments.</p></div><div class="stat"><strong>${items.length}</strong><span>major stories loaded</span><small>Updates automatically</small></div></div>${items.length?`<div class="sectiongrid">${items.slice(0,30).map(card).join('')}</div>`:`<div class="simple"><div class="box"><h2>No major breaking stories are available right now.</h2><p>This page checks again automatically every two minutes.</p></div></div>`}</main>`;document.title='Major Breaking Technology News — AI News Now'}
async function refresh(){try{const r=await fetch('/api/breaking-live',{cache:'no-store'});if(!r.ok)throw Error(String(r.status));const j=await r.json(),items=j.news||[];if(key==='breaking')page(items);else if(!rail(items)){let tries=0;const t=setInterval(()=>{tries++;if(rail(items)||tries>20)clearInterval(t)},350)}}catch{}}
refresh();setInterval(refresh,120000);
})();
