(()=>{
const key=location.pathname.split('/').filter(Boolean)[0]||'home';if(key!=='home'&&key!=='breaking')return;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const ago=x=>{const m=Math.max(1,Math.floor((Date.now()-new Date(x))/60000));return m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
const clock=x=>{try{return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(x))}catch{return'now'}};
const currentPage=()=>{const n=parseInt(new URLSearchParams(location.search).get('page')||'1',10);return Number.isFinite(n)?Math.max(1,Math.min(15,n)):1};
function pageHref(p){const u=new URL(location.href);u.searchParams.set('page',String(p));return u.pathname+u.search}
function pager(j){const total=Math.max(1,Math.min(15,Number(j.totalPages||1))),p=Math.max(1,Math.min(total,Number(j.page||1)));let h='<nav class="news-pagination" aria-label="Breaking news pages">';h+=p>1?`<a href="${pageHref(p-1)}">← Previous</a>`:'<span class="disabled">← Previous</span>';h+='<span class="page-label">Page</span>';for(let i=1;i<=total;i++)h+=i===p?`<span class="current" aria-current="page">${i}</span>`:`<a href="${pageHref(i)}">${i}</a>`;h+=p<total?`<a href="${pageHref(p+1)}">Next →</a>`:'<span class="disabled">Next →</span>';h+='</nav>';h+=`<div class="pagination-meta">Page ${p} of ${total} · ${Number(j.totalCount||j.count||0)} major stories available · 30 stories per page · up to 15 pages</div>`;return h}
function img(n,cls='news-img'){return `<img class="${cls}" src="${esc(n.image)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer">`}
function card(n){const sev=n.severity||'DEVELOPING';return `<article class="card breaking-card" data-severity="${esc(sev)}" data-priority="${Number(n.priority||0)}"><a class="art" href="${esc(n.link)}" target="_blank" rel="noreferrer">${img(n)}</a><div class="body"><div class="meta">${esc(n.source)} · ${ago(n.publishedAt)}</div><h3><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.title)}</a></h3><p>${esc(n.description)}</p>${n.whyItMatters?`<p class="why-matters"><strong>Why it matters:</strong> ${esc(n.whyItMatters)}</p>`:''}<div class="foot"><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.source)} · Read source ↗</a><span>Priority ${Number(n.priority||0)}</span></div></div></article>`}
function storyKey(n){return String(n.id||n.link||n.title||'')}
function hrefKey(v){try{const u=new URL(v,location.href);u.hash='';return u.href}catch{return String(v||'')}}
function railRow(n){const a=document.createElement('a');a.className='breakitem';a.href=n.link;a.target='_blank';a.rel='noreferrer';a.dataset.storyKey=storyKey(n);a.innerHTML=`<div><small>${esc(n.severity||'DEVELOPING')} · ${ago(n.publishedAt)} · ${esc(n.source)}</small><strong>${esc(n.title)}</strong></div><span class="thumb">${img(n,'thumb-img')}</span>`;return a}
function updateRailRow(row,n){row.dataset.storyKey=storyKey(n);row.href=n.link;const small=row.querySelector('small'),strong=row.querySelector('strong');if(small)small.textContent=`${n.severity||'DEVELOPING'} · ${ago(n.publishedAt)} · ${n.source||''}`;if(strong&&strong.textContent!==n.title)strong.textContent=n.title}
function rail(items){const p=document.querySelector('.panel.breaking');if(!p)return false;const top=items.slice(0,5);let head=p.querySelector(':scope > .pt');if(!head){head=document.createElement('div');head.className='pt';head.innerHTML='<span>🔥 BREAKING NEWS</span><a href="/breaking/">View all</a>';p.prepend(head)}let btn=p.querySelector(':scope > .railbtn');if(!btn){btn=document.createElement('a');btn.className='railbtn';btn.href='/breaking/';btn.textContent='View all breaking news →';p.appendChild(btn)}
const rows=[...p.querySelectorAll(':scope > .breakitem')],byKey=new Map(),byHref=new Map();for(const row of rows){if(row.dataset.storyKey)byKey.set(row.dataset.storyKey,row);byHref.set(hrefKey(row.getAttribute('href')),row)}const keep=new Set();for(const n of top){const k=storyKey(n),h=hrefKey(n.link);let row=byKey.get(k)||byHref.get(h);if(!row)row=railRow(n);else updateRailRow(row,n);keep.add(row);p.insertBefore(row,btn)}for(const row of rows)if(!keep.has(row))row.remove();return true}
function page(items,j){const app=document.getElementById('app');if(!app)return;const c=j.severityCounts||{},y=window.scrollY,p=j.page||currentPage();app.className='';app.innerHTML=`<main class="section"><div class="sectionhero breaking-hero"><div><a class="back" href="/">← AI News Now</a><span class="breaking-pulse">LIVE BREAKING DESK · CHECKS EVERY 60 SECONDS</span><h1>Major Breaking Technology News</h1><p>High-impact live coverage across AI, IT, cybersecurity, cloud, hardware, outages, vulnerabilities, major product launches, regulation, acquisitions and other important technology developments.</p><div class="breaking-summary"><span class="breaking-count"><b>${c.BREAKING||0}</b> Breaking</span><span class="breaking-count"><b>${c.MAJOR||0}</b> Major</span><span class="breaking-count"><b>${c.DEVELOPING||0}</b> Developing</span></div><div class="breaking-lastcheck">Last checked ${clock(j.updatedAt)} · newest high-signal stories are ranked by impact and recency</div></div><div class="stat"><strong>${items.length}</strong><span>stories on page ${p}</span><small>${j.totalCount||items.length} major stories available</small></div></div>${items.length?`<div class="sectiongrid">${items.map(card).join('')}</div>${pager(j)}`:`<div class="simple"><div class="box"><h2>No major breaking stories are available on this page right now.</h2><p>This page checks again automatically every 60 seconds.</p></div></div>`}</main>`;document.title='Major Breaking Technology News — AI News Now'+(p>1?` · Page ${p}`:'');requestAnimationFrame(()=>window.scrollTo(0,y));window.dispatchEvent(new CustomEvent('ainn:page-rendered',{detail:j}))}
let last='';async function refresh(){try{const p=key==='breaking'?currentPage():1,r=await fetch('/api/breaking-plus?page='+p+'&_t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(String(r.status));const j=await r.json(),items=j.news||[],fp=p+'|'+items.slice(0,8).map(x=>x.id||x.link).join('|');if(key==='breaking'){if(fp&&fp===last)return;last=fp;page(items,j)}else if(!rail(items)){let tries=0;const t=setInterval(()=>{tries++;if(rail(items)||tries>20)clearInterval(t)},350)}}catch{}}
refresh();setInterval(()=>{if(document.visibilityState==='visible')refresh()},60000);
})();