(()=>{
const POLL_MS=60000;
const STORAGE_PERMISSION_PROMPT='ainn-notification-prompted-v1';
const STORAGE_LAST_STORY='ainn-last-breaking-story-v1';
const STORAGE_ENABLED='ainn-notifications-enabled-v1';
let timer=null,checking=false;
const canNotify='Notification' in window;
const css=`
.ain-notify-active{background:#0c2d21!important;color:#55ec91!important;box-shadow:inset 0 0 0 1px #2a7e50,0 0 16px rgba(61,228,108,.14)!important}
.ain-notify-active:after{content:'';position:absolute;width:7px;height:7px;border-radius:50%;background:#49e97c;right:5px;top:5px;box-shadow:0 0 8px #49e97c}
.reference-action.bell{position:relative}
.ain-notify-prompt{position:fixed;right:22px;top:90px;z-index:1000;width:min(390px,calc(100vw - 28px));padding:18px;border:1px solid #29445f;border-radius:12px;background:linear-gradient(145deg,#071522,#0b1d2d);box-shadow:0 18px 60px rgba(0,0,0,.42);color:#f6f9fc;font-family:Inter,ui-sans-serif,system-ui,-apple-system,'Segoe UI',sans-serif}
.ain-notify-prompt strong{display:block;font-size:15px;margin-bottom:7px}.ain-notify-prompt p{margin:0;color:#a6b7c8;font-size:12px;line-height:1.55}.ain-notify-actions{display:flex;gap:9px;margin-top:14px}.ain-notify-actions button{height:36px;padding:0 14px;border-radius:7px;cursor:pointer;font-weight:700;font-size:11px}.ain-notify-enable{border:1px solid #2a81e6;background:#1266d4;color:#fff}.ain-notify-later{border:1px solid #294158;background:#081724;color:#b8c5d2}.ain-notify-toast{position:fixed;right:22px;bottom:22px;z-index:1001;max-width:390px;padding:13px 15px;border:1px solid #2d4d68;border-radius:10px;background:#071522;color:#eaf2fa;box-shadow:0 15px 45px rgba(0,0,0,.35);font:12px/1.45 Inter,ui-sans-serif,system-ui;animation:ainToastIn .2s ease-out}.ain-notify-toast b{display:block;margin-bottom:3px}@keyframes ainToastIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}
@media(max-width:830px){.ain-notify-prompt{top:128px;right:14px}.ain-notify-toast{right:14px;bottom:14px;left:14px;max-width:none}}
`;
function addStyles(){if(document.getElementById('ain-notification-style'))return;const s=document.createElement('style');s.id='ain-notification-style';s.textContent=css;document.head.appendChild(s)}
function bell(){return document.querySelector('.reference-action.bell,.actions a[href="/breaking/"]')}
function paintBell(){const b=bell();if(!b)return;const granted=canNotify&&Notification.permission==='granted';b.classList.toggle('ain-notify-active',granted);b.setAttribute('aria-label',granted?'Breaking news notifications enabled':'Enable breaking news notifications');b.setAttribute('title',granted?'Breaking alerts enabled':'Enable breaking alerts');}
function toast(title,msg){document.querySelector('.ain-notify-toast')?.remove();const d=document.createElement('div');d.className='ain-notify-toast';d.innerHTML=`<b>${title}</b>${msg}`;document.body.appendChild(d);setTimeout(()=>d.remove(),4200)}
async function registration(){if(!('serviceWorker' in navigator))return null;try{return await navigator.serviceWorker.register('/sw.js',{scope:'/'}),await navigator.serviceWorker.ready}catch{return null}}
async function enable(){if(!canNotify){toast('Notifications unavailable','This browser does not support website notifications.');return false}let p=Notification.permission;if(p==='default'){try{p=await Notification.requestPermission()}catch{p='denied'}}if(p==='granted'){localStorage.setItem(STORAGE_ENABLED,'1');paintBell();await registration();toast('Breaking alerts enabled','You will receive alerts for new major technology stories while AI News Now is active.');start();return true}localStorage.removeItem(STORAGE_ENABLED);paintBell();toast('Notifications not enabled','You can change notification permission later in your browser site settings.');return false}
function prompt(){if(!canNotify||Notification.permission!=='default'||localStorage.getItem(STORAGE_PERMISSION_PROMPT))return;const d=document.createElement('div');d.className='ain-notify-prompt';d.setAttribute('role','dialog');d.setAttribute('aria-label','Enable breaking news alerts');d.innerHTML=`<strong>🔔 Get Major Breaking Tech Alerts</strong><p>Get notified when AI News Now detects an important AI, IT, cybersecurity, outage, vulnerability, hardware or big-tech story.</p><div class="ain-notify-actions"><button class="ain-notify-enable" type="button">Enable alerts</button><button class="ain-notify-later" type="button">Not now</button></div>`;d.querySelector('.ain-notify-enable').onclick=async()=>{localStorage.setItem(STORAGE_PERMISSION_PROMPT,'1');d.remove();await enable()};d.querySelector('.ain-notify-later').onclick=()=>{localStorage.setItem(STORAGE_PERMISSION_PROMPT,'1');d.remove()};document.body.appendChild(d)}
async function notifyStory(story){const title='AI NEWS NOW · Breaking Tech';const body=String(story.title||'New major technology story').slice(0,180);const opts={body,icon:'/favicon.svg',badge:'/favicon.svg',tag:'breaking-'+String(story.id||story.link||Date.now()),renotify:false,data:{url:story.link||'/breaking/'}};const reg=await registration();try{if(reg)await reg.showNotification(title,opts);else new Notification(title,opts)}catch{}}
async function check(silent=false){if(checking||!canNotify||Notification.permission!=='granted')return;checking=true;try{const r=await fetch('/api/breaking-plus',{cache:'no-store'});if(!r.ok)throw 0;const j=await r.json(),story=j.news?.[0];if(!story)return;const id=String(story.id||story.link||story.title);const prev=localStorage.getItem(STORAGE_LAST_STORY);localStorage.setItem(STORAGE_LAST_STORY,id);if(!silent&&prev&&prev!==id)await notifyStory(story)}catch{}finally{checking=false}}
function start(){if(timer)clearInterval(timer);if(canNotify&&Notification.permission==='granted'){check(true);timer=setInterval(()=>check(false),POLL_MS)}}
function bindBell(){const b=bell();if(!b||b.dataset.notifyBound==='1')return;b.dataset.notifyBound='1';b.addEventListener('click',async e=>{e.preventDefault();if(canNotify&&Notification.permission==='granted'){location.href='/breaking/';return}await enable()});paintBell()}
addStyles();
const mo=new MutationObserver(()=>{bindBell();paintBell()});mo.observe(document.documentElement,{subtree:true,childList:true});
window.addEventListener('load',()=>{bindBell();paintBell();if(canNotify&&Notification.permission==='granted'){localStorage.setItem(STORAGE_ENABLED,'1');start()}else setTimeout(prompt,1800)},{once:true});
})();