(()=>{
const key=location.pathname.split('/').filter(Boolean)[0]||'home';
const skip=new Set(['home','about','daily-brief','breaking','bleepingcomputer','hacker-news','securityweek','ars-security','dark-reading','the-record','cybernews','techpowerup','the-register']);
if(skip.has(key))return;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=x=>{let m=Math.max(1,Math.floor((Date.now()-new Date(x))/60000));return m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
const currentPage=()=>{const n=parseInt(new URLSearchParams(location.search).get('page')||'1',10);return Number.isFinite(n)?Math.max(1,Math.min(15,n)):1};
function card(n,i){const img=/^https?:\/\//i.test(n.image||'')?n.image:`/api/article-image?article=${encodeURIComponent(n.link||'')}&seed=${encodeURIComponent(n.id||n.title||i)}&variant=page-${i}`;return `<article class="card"><a class="art" href="${esc(n.link)}" target="_blank" rel="noreferrer"><img class="news-img" src="${esc(img)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer"></a><div class="body"><div class="meta">${esc(n.source||'News')} · ${ago(n.publishedAt)}</div><h3><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.title)}</a></h3><p>${esc(n.description||'Latest technology news and analysis.')}</p><div class="foot"><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.source||'News')} · Read source ↗</a><span>♡</span></div></div></article>`}
function pageHref(p){const u=new URL(location.href);u.searchParams.set('page',String(p));return u.pathname+u.search}
function pager(meta){const total=Math.max(1,Math.min(15,Number(meta.totalPages||1))),page=Math.max(1,Math.min(total,Number(meta.page||1)));let h='<nav class="news-pagination" aria-label="News pages">';h+=page>1?`<a href="${pageHref(page-1)}">← Previous</a>`:'<span class="disabled">← Previous</span>';h+='<span class="page-label">Page</span>';for(let i=1;i<=total;i++)h+=i===page?`<span class="current" aria-current="page">${i}</span>`:`<a href="${pageHref(i)}">${i}</a>`;h+=page<total?`<a href="${pageHref(page+1)}">Next →</a>`:'<span class="disabled">Next →</span>';h+='</nav>';h+=`<div class="pagination-meta">Page ${page} of ${total} · ${Number(meta.totalCount||meta.count||0)} stories available · 30 stories per page · up to 15 pages</div>`;return h}
async function run(){let tries=0;while(tries++<100){const section=document.querySelector('#app .section:not(.instant-home)'),grid=section?.querySelector('.sectiongrid');if(section&&grid)break;await new Promise(r=>setTimeout(r,100))}const section=document.querySelector('#app .section:not(.instant-home)'),grid=section?.querySelector('.sectiongrid');if(!section||!grid)return;const q=new URLSearchParams(location.search).get('q')||'',category=key==='search'?'search':key,p=currentPage();try{const params=new URLSearchParams({category,page:String(p)});if(q)params.set('q',q);const r=await fetch('/api/news?'+params.toString());if(!r.ok)throw Error('news '+r.status);const j=await r.json(),items=j.news||[];document.querySelector('.reader-toolbar')?.remove();grid.innerHTML=items.length?items.map(card).join(''):'<div class="reader-empty">No stories are available on this page yet.</div>';section.querySelector('.news-pagination')?.remove();section.querySelector('.pagination-meta')?.remove();grid.insertAdjacentHTML('afterend',pager(j));const stat=section.querySelector('.stat');if(stat){const strong=stat.querySelector('strong'),span=stat.querySelector('span'),small=stat.querySelector('small');if(strong)strong.textContent=String(items.length);if(span)span.textContent=`stories on page ${j.page||p}`;if(small)small.textContent=`${j.totalCount||items.length} available · up to 15 pages`}document.title=document.title.replace(/ · Page \d+$/,'')+(Number(j.page||1)>1?` · Page ${j.page}`:'');window.dispatchEvent(new CustomEvent('ainn:page-rendered',{detail:j}))}catch(err){console.warn('Pagination update skipped',err)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();