const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = __dirname;
const out = path.join(root, 'dist');
const generatedIndex = path.join(out, 'index.html');

if (!fs.existsSync(generatedIndex)) {
  throw new Error('postbuild: dist/index.html was not generated by build.cjs');
}

// build.cjs already produces a fully validated page with the authoritative
// 332-certification catalog embedded directly in the HTML. Keep that page as
// the production entry point. Do not fetch/decompress the catalog in Safari at
// runtime: WebKit can fail inside DecompressionStream/TransformStream before
// the application renders.
let html = fs.readFileSync(generatedIndex, 'utf8');

for (let i = 1; i <= 4; i++) {
  const runtimePath = path.join(root, `itcv-runtime-${i}.js`);
  if (!fs.existsSync(runtimePath)) {
    throw new Error(`postbuild: itcv-runtime-${i}.js is missing`);
  }
  // Each chunk must itself be valid classic browser JavaScript.
  new vm.Script(fs.readFileSync(runtimePath, 'utf8'), { filename: `itcv-runtime-${i}.js` });
}

const runtime3 = fs.readFileSync(path.join(root, 'itcv-runtime-3.js'), 'utf8');
if (!runtime3.includes('function genVideos(id)') || !runtime3.includes('window.CERT_VIDEOS=lazy(window.CERT_VIDEOS,genVideos)')) {
  throw new Error('postbuild: certification video fallback runtime is missing');
}

// The historical app points study routes at /data/<version>/ JSON files that
// are no longer deployed. Replace only that obsolete manifest before any app
// JavaScript executes. The local runtime below then supplies study books,
// questions, labs, images, domains, and video links for every certification ID.
const legacyBlobPattern = /window\.CF_BLOB=\{version:"[^"]+",base:'\/data\/',manifest:\{[^\n]*\}\};/g;
const legacyBlobCount = (html.match(/window\.CF_BLOB=\{version:/g) || []).length;
html = html.replace(legacyBlobPattern, 'window.CF_BLOB={version:"local-runtime",base:"",manifest:{}};');
if (/window\.CF_BLOB=\{version:"[^"]+",base:'\/data\/'/.test(html)) {
  throw new Error('postbuild: obsolete /data/ certification manifest is still present');
}

const marker = 'var META=window.CERT_META';
const markerPos = html.indexOf(marker);
if (markerPos < 0) {
  throw new Error('postbuild: ITCertVault application marker was not found');
}
const appScriptPos = html.lastIndexOf('<script', markerPos);
if (appScriptPos < 0) {
  throw new Error('postbuild: ITCertVault application script was not found');
}

const runtimeTags =
  '<script>' +
  `window.ITCV_LEGACY_BLOB_COUNT=${legacyBlobCount};` +
  'window.CERT_DOMAINS=window.CERT_DOMAINS||{};' +
  'window.CERT_VIDEOS=window.CERT_VIDEOS||{};' +
  '</script>' +
  '<script src="itcv-runtime-1.js"></script>' +
  '<script src="itcv-runtime-2.js"></script>' +
  '<script src="itcv-runtime-3.js"></script>' +
  '<script src="itcv-runtime-4.js"></script>' +
  '<script>' +
  '(function(){' +
  'if(!window.ITCV_RUNTIME_SRC)throw new Error("ITCertVault runtime chunks did not load.");' +
  'Function(window.ITCV_RUNTIME_SRC)();' +
  // The runtime intentionally builds content from ITCV_META. Restore CERT_META
  // to an isolated copy before the historical application script runs so old
  // catalog appenders cannot mutate the authoritative 332-cert array.
  'if(Array.isArray(window.ITCV_META))window.CERT_META=window.ITCV_META.slice();' +
  '})();' +
  '</script>';

html = html.slice(0, appScriptPos) + runtimeTags + html.slice(appScriptPos);

if (!html.includes('itcv-runtime-3.js') || !html.includes('window.CERT_META=window.ITCV_META.slice()')) {
  throw new Error('postbuild: direct production runtime injection failed validation');
}
if (!html.includes('window.CF_BLOB={version:"local-runtime",base:"",manifest:{}};')) {
  throw new Error('postbuild: local study-content manifest replacement was not applied');
}

fs.writeFileSync(generatedIndex, html, 'utf8');

console.log(`postbuild: published direct Safari-safe production page (${html.length.toLocaleString()} chars).`);
console.log(`postbuild: removed ${legacyBlobCount} legacy blob manifest reference(s).`);
console.log('postbuild: all-cert study/video runtime injected before application startup.');
