const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = __dirname;
const out = path.join(root, 'dist');
const generatedIndex = path.join(out, 'index.html');

if (!fs.existsSync(generatedIndex)) {
  throw new Error('postbuild: dist/index.html was not generated by build.cjs');
}

let html = fs.readFileSync(generatedIndex, 'utf8');

for (let i = 1; i <= 4; i++) {
  const runtimePath = path.join(root, `itcv-runtime-${i}.js`);
  if (!fs.existsSync(runtimePath)) {
    throw new Error(`postbuild: itcv-runtime-${i}.js is missing`);
  }
  new vm.Script(fs.readFileSync(runtimePath, 'utf8'), { filename: `itcv-runtime-${i}.js` });
}

const runtime3 = fs.readFileSync(path.join(root, 'itcv-runtime-3.js'), 'utf8');
if (!runtime3.includes('function genVideos(id)') || !runtime3.includes('window.CERT_VIDEOS=lazy(window.CERT_VIDEOS,genVideos)')) {
  throw new Error('postbuild: certification video fallback runtime is missing');
}

const legacyBlobPattern = /window\.CF_BLOB=\{version:"[^"]+",base:'\/data\/',manifest:\{[^\n]*\}\};/g;
const legacyBlobCount = (html.match(/window\.CF_BLOB=\{version:/g) || []).length;
html = html.replace(legacyBlobPattern, 'window.CF_BLOB={version:"local-runtime",base:"",manifest:{}};');
if (/window\.CF_BLOB=\{version:"[^"]+",base:'\/data\/'/.test(html)) {
  throw new Error('postbuild: obsolete /data/ certification manifest is still present');
}

const marker = 'var META=window.CERT_META';
const markerPos = html.indexOf(marker);
if (markerPos < 0) {
  throw new Error('postbuild: ByteBadge application marker was not found');
}
const appScriptPos = html.lastIndexOf('<script', markerPos);
if (appScriptPos < 0) {
  throw new Error('postbuild: ByteBadge application script was not found');
}

const runtimeTags =
  '<script>' +
  `window.ITCV_LEGACY_BLOB_COUNT=${legacyBlobCount};` +
  'window.CERT_DOMAINS=window.CERT_DOMAINS||{};' +
  'window.CERT_VIDEOS=window.CERT_VIDEOS||{};' +
  '</script>' +
  '<script src="itcv-runtime-1.js"></script>' +
  '<script src="itcv-runtime-2.js"></script>' +
  '<script src="itcv-runtime-3.js"></script>' +
  '<script src="itcv-runtime-4.js"></script>' +
  '<script>' +
  '(function(){' +
  'if(!window.ITCV_RUNTIME_SRC)throw new Error("ByteBadge runtime chunks did not load.");' +
  'Function(window.ITCV_RUNTIME_SRC)();' +
  'if(Array.isArray(window.ITCV_META))window.CERT_META=window.ITCV_META.slice();' +
  '})();' +
  '</script>';

html = html.slice(0, appScriptPos) + runtimeTags + html.slice(appScriptPos);

if (!html.includes('itcv-runtime-3.js') || !html.includes('window.CERT_META=window.ITCV_META.slice()')) {
  throw new Error('postbuild: direct runtime injection failed validation');
}
if (!html.includes('window.CF_BLOB={version:"local-runtime",base:"",manifest:{}};')) {
  throw new Error('postbuild: local study-content manifest replacement was not applied');
}

html = html
  .replace(/CertForge/g, 'ByteBadge')
  .replace(/ITCertVault/g, 'ByteBadge');

// Fresh-site safe mode:
// The historical page accumulated dozens of independent DOM-repair layers.
// Each layer installs a MutationObserver and many of them observe the entire
// document subtree. They react to each other's DOM changes and can keep the
// browser busy indefinitely. The original core application does not require
// those observer patches to boot, so remove them from this fresh branch.
let removedObservers = 0;
html = html.replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi, (full, attrs, body) => {
  if (/new\s+MutationObserver\b/.test(body)) {
    removedObservers++;
    return '';
  }
  return full;
});

if (removedObservers < 20) {
  throw new Error(`postbuild: safe mode expected many legacy observer scripts; found only ${removedObservers}`);
}

// Add a tiny marker so we can verify the fast build is the one being served.
html = html.replace(
  /<head>/i,
  '<head><meta name="bytebadge-build" content="fresh-fast-v1">'
);

fs.writeFileSync(generatedIndex, html, 'utf8');

console.log(`postbuild: published ByteBadge fresh fast build (${html.length.toLocaleString()} chars).`);
console.log(`postbuild: removed ${legacyBlobCount} legacy blob manifest reference(s).`);
console.log(`postbuild: removed ${removedObservers} legacy MutationObserver repair scripts.`);
console.log('postbuild: ByteBadge branding applied.');
