const fs = require('fs');
const path = require('path');

const root = __dirname;
const out = path.join(root, 'dist');
const generatedIndex = path.join(out, 'index.html');
const shellPath = path.join(root, 'index.html');

if (!fs.existsSync(generatedIndex)) {
  throw new Error('postbuild: dist/index.html was not generated by build.cjs');
}
if (!fs.existsSync(shellPath)) {
  throw new Error('postbuild: bootstrap index.html is missing');
}

const builtBase = fs.readFileSync(generatedIndex, 'utf8');
const shell = fs.readFileSync(shellPath, 'utf8');

const requiredShellMarkers = [
  'base.html',
  'itcv-runtime-1.js',
  'itcv-runtime-2.js',
  'itcv-runtime-3.js',
  'itcv-runtime-4.js',
  'legacyBlobPattern',
  'document.write(html)'
];
for (const marker of requiredShellMarkers) {
  if (!shell.includes(marker)) {
    throw new Error(`postbuild: bootstrap index.html is missing required marker: ${marker}`);
  }
}

const runtime3Path = path.join(root, 'itcv-runtime-3.js');
if (!fs.existsSync(runtime3Path)) {
  throw new Error('postbuild: itcv-runtime-3.js is missing');
}
const runtime3 = fs.readFileSync(runtime3Path, 'utf8');
if (!runtime3.includes('function genVideos(id)') || !runtime3.includes('window.CERT_VIDEOS=lazy(window.CERT_VIDEOS,genVideos)')) {
  throw new Error('postbuild: certification video fallback runtime is missing');
}

// build.cjs produces the repaired, validated legacy application as dist/index.html.
// Keep that exact validated result as base.html, then publish the bootstrap shell
// as index.html. The shell removes the obsolete /data/ manifest before the app
// executes and injects the runtime that supplies study content and videos for all
// certification IDs.
fs.writeFileSync(path.join(out, 'base.html'), builtBase, 'utf8');
fs.writeFileSync(path.join(out, 'index.html'), shell, 'utf8');

console.log(`postbuild: published bootstrap index.html and validated base.html (${builtBase.length.toLocaleString()} chars).`);
console.log('postbuild: legacy study loader bypass + all-cert video runtime verified.');
