const TOOL_REDIRECTS={
  'magai':'/tool-magai/',
  'opusclip':'/tool-opusclip/',
  'opusclip 2.0':'/tool-opusclip/',
  'opus clip':'/tool-opusclip/',
  'codestral':'/tool-codestral/',
  'leonardo ai':'/tool-leonardo-ai/',
  'leonardo.ai':'/tool-leonardo-ai/',
  'voicemod':'/tool-voicemod-ai/',
  'voicemod ai':'/tool-voicemod-ai/'
};
const FALLBACK='https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1800&q=90';
const e=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=x=>{let m=Math.max(1,Math.floor((Date.now()-new Date(x))/60000));return m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
const text=n=>(n.title+' '+n.description+' '+n.source).toLowerCase();
function loadFixCss(){if(!document.querySelector('link[href="/media-fix.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/media-fix.css';document.head.appendChild(l)}}
function upgradeHeader(){const top=document.querySelector('.top');if(!top)return;top.classList.add('reference-header');const brand=top.querySelector('.brand');if(brand)brand.innerHTML='<span class="brand-favicon-shell"><img class="brand-favicon" src="/favicon.svg" alt="AI News Now"></span><span class="brand-copy"><strong>AI NEWS NOW</strong><small>Your Daily Source for Everything AI</small></span>';const search=top.querySelector('.search');if(search){const b=search.querySelector('button');if(b)b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"></circle><path d="m16 16 4 4"></path></svg>';search.onsubmit=ev=>{ev.preventDefault();const q=search.querySelector('input').value.trim();if(q)location.href='/search/?q='+encodeURIComponent(q)}}const actions=top.querySelector('.actions');if(actions)actions.innerHTML='<button class="reference-action" id="theme" type="button" aria-label="Toggle light and dark theme" title="Toggle theme"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3.4"></circle><path d="M12 2.2v2.1M12 19.7v2.1M4.2 4.2l1.5 1.5M18.3 18.3l1.5 1.5M2.2 12h2.1M19.7 12h2.1M4.2 19.8l1.5-1.5M18.3 5.7l1.5-1.5"></path></svg></button><a class="reference-action bell" href="/breaking/" aria-label="Breaking news" title="Breaking news"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 9.8a5.5 5.5 0 0 1 11 0c0 6 2.2 6.1 2.2 6.1H4.3s2.2-.1 2.2-6.1"></path><path d="M9.8 19a2.5 2.5 0 0 0 4.4 0"></path></svg></a>';const theme=document.getElementById('theme');if(theme)theme.onclick=()=>document.documentElement.classList.toggle('light')}
function img(n){const src=/^https?:\/\//i.test(n.image||'')?n.image:FALLBACK;return `<img class="news-img" src="${e(src)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src='${FALLBACK}'">`}
function card(n){return `<article class="card"><a class="art" href="${e(n.link)}" target="_blank" rel="noreferrer">${img(n)}</a><div class="body"><div class="meta">${e(n.source)} · ${ago(n.publishedAt)}</div><h3><a href="${e(n.link)}" target="_blank" rel="noreferrer">${e(n.title)}</a></h3><p>${e(n.description||'Open the original story for full details.')}</p><div class="foot"><a href="${e(n.link)}" target="_blank" rel="noreferrer">${e(n.source)} · Read source ↗</a><span>♡</span></div></div></article>`}
function fill(primary,all,count=30){const out=[],seen=new Set();for(const n of [...primary,...all]){const k=n.link||n.id||n.title;if(!k||seen.has(k))continue;seen.add(k);out.push(n);if(out.length===count)break}return out}
async function run(){loadFixCss();upgradeHeader();const app=document.getElementById('app'),q=(new URLSearchParams(location.search).get('q')||'').trim(),lower=q.toLowerCase();if(TOOL_REDIRECTS[lower]){location.replace(TOOL_REDIRECTS[lower]);return}if(!q){location.replace('/all-news/');return}document.title=`Search: ${q} — AI News Now`;try{const r=await fetch('/api/news?category=search&q='+encodeURIComponent(q),{cache:'no-store'});if(!r.ok)throw Error('Live feed unavailable');const j=await r.json(),all=j.news||[],exact=all.filter(n=>text(n).includes(lower)),items=fill(exact,all,30);app.className='';app.innerHTML=`<main class="section"><div class="sectionhero"><div><a class="back" href="/">← AI News Now</a><span class="live">● LIVE SEARCH</span><h1>Search: “${e(q)}”</h1><p>Live web-news results for ${e(q)}, followed by related current AI coverage.</p></div><div class="stat"><strong>${items.length}</strong><span>stories loaded</span><small>Refreshes automatically</small></div></div><div class="sectiongrid">${items.map(card).join('')}</div></main>`}catch(err){app.className='';app.innerHTML=`<main class="simple"><div class="box"><h1>Search: “${e(q)}”</h1><p>The live search feed is temporarily unavailable. Refresh this page in a moment.</p><a href="/all-news/">Browse all AI news</a></div></main>`}}
run();
