(()=>{
const KEY=location.pathname.split('/').filter(Boolean)[0]||'home';
const SAVED_KEY='ainn-saved-stories-v2',READ_KEY='ainn-local-read-counts-v1';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeJSON=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k)||'')||fallback}catch{return fallback}};
const saveJSON=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const getSaved=()=>safeJSON(SAVED_KEY,[]),getReads=()=>safeJSON(READ_KEY,{});
const normalizeUrl=u=>{try{const x=new URL(u,location.href);x.hash='';return x.href}catch{return String(u||'')}};
const storyKey=u=>normalizeUrl(u).replace(/[?&](utm_[^=]+|ref|source)=[^&]*/gi,'');
const SOURCE_DOMAINS={'TechCrunch':'techcrunch.com','The Verge':'theverge.com','VentureBeat':'venturebeat.com','Hugging Face':'huggingface.co','BleepingComputer':'bleepingcomputer.com','The Hacker News':'thehackernews.com','SecurityWeek':'securityweek.com','Ars Technica Security':'arstechnica.com','Ars Technica':'arstechnica.com','Google News':'news.google.com','r/sysadmin':'reddit.com','NVIDIA':'nvidia.com','OpenAI':'openai.com','Google':'google.com','Meta':'meta.com','Microsoft':'microsoft.com'};

function removeVercelUI(root=document){
  const selectors=['script[src*="vercel.live/_next-live/feedback"]','script[src*="vercel.live"]','vercel-live-feedback','#vercel-live-feedback','[data-vercel-toolbar]','.vercel-toolbar','iframe[src*="vercel.live"]','iframe[src*="vercel.com/live"]'];
  for(const s of selectors)root.querySelectorAll?.(s).forEach(n=>n.remove());
}
removeVercelUI();new MutationObserver(m=>{for(const x of m)for(const n of x.addedNodes){if(n.nodeType===1){removeVercelUI(n);if(n.matches?.('script[src*="vercel.live"],vercel-live-feedback,[data-vercel-toolbar],iframe[src*="vercel.live"]'))n.remove()}}}).observe(document.documentElement,{childList:true,subtree:true});

function navMarkup(){return `<div class="ain-nav-shell">
<a class="ain-nav-link" href="/">HOME</a><a class="ain-nav-link breaking-nav" href="/breaking/">BREAKING</a>
<details class="nav-group"><summary>AI</summary><div class="nav-menu"><a href="/chatgpt/">ChatGPT & OpenAI</a><a href="/claude/">Claude & Anthropic</a><a href="/gemini/">Gemini & Google AI</a><a href="/ai-models/">AI Models</a><a href="/ai-video/">AI Video</a><a href="/ai-images/">AI Images</a><a href="/coding/">AI Coding</a><a href="/robotics/">AI Robotics</a></div></details>
<details class="nav-group"><summary>TECHNOLOGY</summary><div class="nav-menu"><a href="/it-news/">IT News</a><a href="/hardware/">Hardware</a><a href="/sysadmin/">Sysadmin</a><a href="/business/">Business & Big Tech</a></div></details>
<details class="nav-group"><summary>SECURITY</summary><div class="nav-menu"><a href="/cybersecurity/">Cybersecurity</a><a href="/bleepingcomputer/">BleepingComputer</a><a href="/hacker-news/">The Hacker News</a><a href="/securityweek/">SecurityWeek</a><a href="/ars-security/">Ars Technica Security</a></div></details>
<details class="nav-group"><summary>PUBLISHERS</summary><div class="nav-menu"><a href="/bleepingcomputer/">BleepingComputer</a><a href="/hacker-news/">The Hacker News</a><a href="/securityweek/">SecurityWeek</a><a href="/ars-security/">Ars Technica Security</a></div></details>
<a class="ain-nav-link" href="/all-news/">ALL NEWS</a>
<details class="nav-group"><summary>MORE</summary><div class="nav-menu"><a href="/daily-brief/">Daily AI Brief</a><a href="/about/">About AI News Now</a><a href="#saved" data-open-saved="1">Saved Stories</a></div></details>
</div>`}
function upgradeNav(){const nav=document.querySelector('.nav');if(!nav||nav.dataset.upgraded==='1')return;nav.dataset.upgraded='1';nav.innerHTML=navMarkup();const activePath='/'+(KEY==='home'?'':KEY+'/');nav.querySelectorAll('a[href]').forEach(a=>{const h=a.getAttribute('href');if(h===activePath||(KEY==='home'&&h==='/'))a.classList.add('active')});nav.querySelectorAll('.nav-group').forEach(g=>{if(g.querySelector('a.active'))g.classList.add('active')});
 const actions=document.querySelector('.reference-header .actions,.top .actions');if(actions&&!actions.querySelector('.mobile-nav-toggle')){const b=document.createElement('button');b.className='mobile-nav-toggle';b.type='button';b.setAttribute('aria-label','Open navigation');b.innerHTML='<span></span>';b.onclick=()=>{nav.classList.toggle('mobile-open');b.setAttribute('aria-label',nav.classList.contains('mobile-open')?'Close navigation':'Open navigation')};actions.prepend(b)}
 document.addEventListener('click',e=>{if(innerWidth>980)return;if(!nav.contains(e.target)&&!e.target.closest('.mobile-nav-toggle'))nav.classList.remove('mobile-open')});
}

function topicFor(text=''){const t=text.toLowerCase();if(/ransomware|malware|breach|vulnerab|zero.?day|cyber|hack|phishing|cisa|threat actor|security/.test(t))return'Cyber';if(/nvidia|amd|intel|gpu|chip|semiconductor|hardware|data center/.test(t))return'Hardware';if(/funding|valuation|acquisition|merger|revenue|earnings|startup|business|antitrust|lawsuit/.test(t))return'Business';if(/windows|linux|server|active directory|microsoft 365|exchange|vmware|hyper-v|sysadmin|network|cloud|outage|infrastructure/.test(t))return'IT';if(/openai|chatgpt|anthropic|claude|gemini|deepmind|llm|artificial intelligence|\bai\b|model|agent|sora|copilot/.test(t))return'AI';return'Tech'}
function whyFor(topic,text=''){const t=text.toLowerCase();if(/outage|disruption|down/.test(t))return'Service availability can affect users, operations and dependent systems.';if(/zero.?day|critical vulnerab|actively exploited/.test(t))return'Security teams should review exposure, patches, mitigations and active exploitation risk.';if(topic==='Cyber')return'This can change defensive priorities, incident response or the risk facing organizations.';if(topic==='Hardware')return'This may affect compute capacity, pricing, AI infrastructure and hardware planning.';if(topic==='Business')return'This could reshape competition, investment, regulation or enterprise technology strategy.';if(topic==='IT')return'This may affect administrators, enterprise systems, cloud services or day-to-day operations.';if(topic==='AI')return'This may change model capabilities, developer workflows or how AI products are used.';return'This is a notable technology development that may affect products, users or the broader industry.'}
function sourceFromCard(card){const meta=card.querySelector('.meta')?.textContent?.trim()||'';return meta.split('·')[0].trim()||'News'}
function linkFromCard(card){const links=[...card.querySelectorAll('a[href]')];for(const a of links){try{const u=new URL(a.href,location.href);if(/^https?:$/.test(u.protocol)&&u.origin!==location.origin)return u.href}catch{}}return links[0]?.href||''}
function storyFromCard(card){const url=linkFromCard(card),title=card.querySelector('h1,h2,h3,strong')?.textContent?.trim()||'Story',source=sourceFromCard(card),desc=card.querySelector('.body>p,.brief-story-copy>p')?.textContent?.trim()||'',img=card.querySelector('img')?.currentSrc||card.querySelector('img')?.src||'',topic=card.dataset.topic||topicFor(title+' '+desc+' '+source);return{key:storyKey(url),url,title,source,desc,img,topic,savedAt:Date.now()}}
function isSaved(key){return getSaved().some(x=>x.key===key)}
function toggleSaved(story){let list=getSaved(),exists=list.some(x=>x.key===story.key);list=exists?list.filter(x=>x.key!==story.key):[story,...list.filter(x=>x.key!==story.key)].slice(0,200);saveJSON(SAVED_KEY,list);updateSavedUI();renderSaved();return!exists}
function recordRead(url){const k=storyKey(url),r=getReads();r[k]=(r[k]||0)+1;saveJSON(READ_KEY,r)}
function sourceLogo(source){const d=SOURCE_DOMAINS[source];if(!d)return `<span class="source-logo">${esc(source.slice(0,1).toUpperCase())}</span>`;return `<span class="source-logo"><img src="https://${d}/favicon.ico" alt="" onerror="this.parentNode.textContent='${esc(source.slice(0,1).toUpperCase())}'"></span>`}
function enhanceCard(card,index=0){if(card.dataset.readerEnhanced==='1')return;const story=storyFromCard(card);if(!story.url)return;card.dataset.readerEnhanced='1';card.dataset.storyKey=story.key;card.dataset.topic=story.topic;card.dataset.originalIndex=String(index);const body=card.querySelector('.body')||card.querySelector('.brief-story-copy');if(!body)return;const meta=body.querySelector('.meta');if(meta&&!meta.querySelector('.source-meta')){const txt=meta.textContent.trim();meta.innerHTML=`<span class="source-meta">${sourceLogo(story.source)}<span class="source-meta-text">${esc(txt)}</span></span>`}
 const row=document.createElement('div');row.className='card-upgrade-row';const severity=card.dataset.severity||'';row.innerHTML=`<div class="story-badges"><span class="story-badge ${story.topic.toLowerCase()}">${esc(story.topic)}</span>${severity?`<span class="story-badge ${severity.toLowerCase()}">${esc(severity)}</span>`:''}</div><div class="story-actions"><button class="story-action story-save ${isSaved(story.key)?'saved':''}" type="button" title="Save story" aria-label="Save story">${isSaved(story.key)?'★':'☆'}</button><button class="story-action story-share" type="button" title="Share story" aria-label="Share story">↗</button></div>`;body.insertBefore(row,body.firstChild);
 const p=body.querySelector('p');if(p&&!body.querySelector('.why-matters')){const w=document.createElement('p');w.className='why-matters';w.innerHTML=`<strong>Why it matters:</strong> ${esc(whyFor(story.topic,story.title+' '+story.desc))}`;p.insertAdjacentElement('afterend',w)}
 row.querySelector('.story-save').onclick=e=>{e.preventDefault();e.stopPropagation();toggleSaved(story)};row.querySelector('.story-share').onclick=async e=>{e.preventDefault();e.stopPropagation();try{if(navigator.share)await navigator.share({title:story.title,url:story.url});else{await navigator.clipboard.writeText(story.url);e.currentTarget.textContent='✓';setTimeout(()=>e.currentTarget.textContent='↗',1200)}}catch{}};
 card.querySelectorAll('a[href]').forEach(a=>{try{const u=new URL(a.href,location.href);if(u.origin!==location.origin)a.addEventListener('click',()=>recordRead(a.href),{passive:true})}catch{}})
}
function enhanceCards(){document.querySelectorAll('.card,.brief-story').forEach((c,i)=>enhanceCard(c,i));updateSavedUI();ensureReaderToolbar()}

function cardAgeHours(card){const txt=card.querySelector('.meta')?.textContent||'';let m=txt.match(/(\d+)m ago/i);if(m)return +m[1]/60;m=txt.match(/(\d+)h ago/i);if(m)return +m[1];m=txt.match(/(\d+)d ago/i);if(m)return +m[1]*24;return 0}
function ensureReaderToolbar(){const section=document.querySelector('.section');if(!section||KEY==='breaking'||section.querySelector('.reader-toolbar'))return;const hero=section.querySelector('.sectionhero');const grid=section.querySelector('.sectiongrid');if(!hero||!grid)return;const sources=[...new Set([...grid.querySelectorAll('.card')].map(sourceFromCard).filter(Boolean))].sort();const bar=document.createElement('div');bar.className='reader-toolbar';bar.innerHTML=`<div class="reader-tabs"><button class="reader-tab active" data-mode="latest">Latest</button><button class="reader-tab" data-mode="read">Most Read <span style="opacity:.55">(this device)</span></button><button class="reader-tab" data-mode="saved">Saved</button></div><select class="reader-select" data-filter="source"><option value="">All sources</option>${sources.map(s=>`<option>${esc(s)}</option>`).join('')}</select><select class="reader-select" data-filter="topic"><option value="">All topics</option><option>AI</option><option>Cyber</option><option>IT</option><option>Hardware</option><option>Business</option><option>Tech</option></select><button class="reader-chip active" data-hours="0">All</button><button class="reader-chip" data-hours="24">24h</button><button class="reader-chip" data-hours="168">7d</button><span class="reader-toolbar-spacer"></span><button class="reader-chip" data-open-saved="1">★ Saved Stories</button><span class="reader-status"></span>`;hero.insertAdjacentElement('afterend',bar);bar.addEventListener('click',e=>{const tab=e.target.closest('[data-mode]');if(tab){bar.querySelectorAll('.reader-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');applyFilters()}const chip=e.target.closest('[data-hours]');if(chip){bar.querySelectorAll('[data-hours]').forEach(x=>x.classList.remove('active'));chip.classList.add('active');applyFilters()}if(e.target.closest('[data-open-saved]'))openSaved()});bar.querySelectorAll('select').forEach(s=>s.onchange=applyFilters);applyFilters()}
function applyFilters(){const bar=document.querySelector('.reader-toolbar'),grid=document.querySelector('.sectiongrid');if(!bar||!grid)return;const source=bar.querySelector('[data-filter="source"]')?.value||'',topic=bar.querySelector('[data-filter="topic"]')?.value||'',hours=+(bar.querySelector('[data-hours].active')?.dataset.hours||0),mode=bar.querySelector('[data-mode].active')?.dataset.mode||'latest',reads=getReads();let cards=[...grid.querySelectorAll('.card')];cards.forEach(c=>{const matchSource=!source||sourceFromCard(c)===source,matchTopic=!topic||c.dataset.topic===topic,matchTime=!hours||cardAgeHours(c)<=hours,matchSaved=mode!=='saved'||isSaved(c.dataset.storyKey);c.hidden=!(matchSource&&matchTopic&&matchTime&&matchSaved)});const shown=cards.filter(c=>!c.hidden);if(mode==='read')shown.sort((a,b)=>(reads[b.dataset.storyKey]||0)-(reads[a.dataset.storyKey]||0)||(+a.dataset.originalIndex)-(+b.dataset.originalIndex));else shown.sort((a,b)=>(+a.dataset.originalIndex)-(+b.dataset.originalIndex));shown.forEach(c=>grid.appendChild(c));const status=bar.querySelector('.reader-status');if(status)status.textContent=`${shown.length} of ${cards.length} stories`;let empty=grid.querySelector('.reader-empty');if(!shown.length){if(!empty){empty=document.createElement('div');empty.className='reader-empty';empty.textContent='No stories match these filters.';grid.appendChild(empty)}}else empty?.remove()}

function ensureSavedDrawer(){if(document.querySelector('.saved-drawer'))return;const back=document.createElement('div');back.className='saved-backdrop';back.onclick=closeSaved;const d=document.createElement('aside');d.className='saved-drawer';d.setAttribute('aria-label','Saved stories');d.innerHTML=`<div class="saved-head"><h2>Saved Stories</h2><button class="saved-close" type="button" aria-label="Close saved stories">×</button></div><div class="saved-list"></div><div class="saved-footer">Saved stories stay on this browser unless you clear site data.</div>`;d.querySelector('.saved-close').onclick=closeSaved;document.body.append(back,d);renderSaved()}
function openSaved(){ensureSavedDrawer();document.querySelector('.saved-backdrop').classList.add('open');document.querySelector('.saved-drawer').classList.add('open');renderSaved()}
function closeSaved(){document.querySelector('.saved-backdrop')?.classList.remove('open');document.querySelector('.saved-drawer')?.classList.remove('open')}
function renderSaved(){const list=document.querySelector('.saved-list');if(!list)return;const saved=getSaved();if(!saved.length){list.innerHTML='<div class="saved-empty">No saved stories yet.<br>Use ☆ on any story card to keep it here.</div>';return}list.innerHTML=saved.map(s=>`<div class="saved-item"><a href="${esc(s.url)}" target="_blank" rel="noreferrer">${s.img?`<img src="${esc(s.img)}" alt="">`:''}</a><div><small>${esc(s.source)} · ${esc(s.topic||'Tech')}</small><a href="${esc(s.url)}" target="_blank" rel="noreferrer" style="text-decoration:none"><strong>${esc(s.title)}</strong></a><div class="saved-item-actions"><button data-remove-saved="${esc(s.key)}">Remove</button><button data-share-saved="${esc(s.url)}">Share</button></div></div></div>`).join('');list.querySelectorAll('[data-remove-saved]').forEach(b=>b.onclick=()=>{saveJSON(SAVED_KEY,getSaved().filter(x=>x.key!==b.dataset.removeSaved));updateSavedUI();renderSaved();enhanceCards();applyFilters()});list.querySelectorAll('[data-share-saved]').forEach(b=>b.onclick=async()=>{try{if(navigator.share)await navigator.share({url:b.dataset.shareSaved});else await navigator.clipboard.writeText(b.dataset.shareSaved)}catch{}})}
function updateSavedUI(){const saved=getSaved();document.querySelectorAll('.card[data-story-key]').forEach(c=>{const b=c.querySelector('.story-save'),on=saved.some(x=>x.key===c.dataset.storyKey);if(b){b.classList.toggle('saved',on);b.textContent=on?'★':'☆'}});let btn=document.querySelector('.ain-saved-header');const actions=document.querySelector('.reference-header .actions,.top .actions');if(actions&&!btn){btn=document.createElement('button');btn.type='button';btn.className='reference-action ain-saved-header';btn.title='Saved stories';btn.setAttribute('aria-label','Open saved stories');btn.innerHTML='★<span class="ain-saved-count"></span>';btn.onclick=openSaved;const bell=actions.querySelector('.bell,a[href="/breaking/"]');bell?.insertAdjacentElement('beforebegin',btn)}if(btn){const c=btn.querySelector('.ain-saved-count');if(c){c.textContent=String(saved.length);c.style.display=saved.length?'block':'none'}}}

function bindSavedLinks(){document.addEventListener('click',e=>{const a=e.target.closest('[data-open-saved]');if(!a)return;e.preventDefault();openSaved()})}
async function registerCache(){if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('/sw.js',{scope:'/'})}catch{}}
function init(){upgradeNav();ensureSavedDrawer();bindSavedLinks();enhanceCards();registerCache();updateSavedUI();if(location.hash==='#saved')openSaved()}
const obs=new MutationObserver(()=>{upgradeNav();enhanceCards();removeVercelUI()});obs.observe(document.documentElement,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();