(()=>{
const REFRESH_MS=60000;
const key=location.pathname.split('/').filter(Boolean)[0]||'home';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=x=>{let m=Math.max(1,Math.floor((Date.now()-new Date(x))/60000));return m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
const TOOLS={
 'tool-magai':{name:'Magai',category:'Multi-model AI workspace',official:'https://magai.co/',query:'Magai',desc:'Magai brings many leading AI models into one workspace so users can switch models, keep context, collaborate and use connected AI workflows.'},
 'tool-opusclip':{name:'OpusClip',category:'AI video clipping and editing',official:'https://www.opus.pro/',query:'OpusClip',desc:'OpusClip turns long videos into short clips with AI-assisted clipping, captioning, reframing, editing and publishing workflows.'},
 'tool-codestral':{name:'Codestral',category:'AI coding model by Mistral',official:'https://mistral.ai/news/codestral/',query:'Codestral Mistral',desc:'Codestral is Mistral AI’s code-focused model family for code generation, completion, fill-in-the-middle and developer workflows.'},
 'tool-leonardo-ai':{name:'Leonardo AI',category:'AI image and video generation',official:'https://leonardo.ai/',query:'Leonardo AI',desc:'Leonardo AI is a generative creative platform for producing and editing images and video with AI-assisted visual tools.'},
 'tool-voicemod-ai':{name:'Voicemod AI',category:'Real-time AI voice tools',official:'https://www.voicemod.net/en/ai-voices/',query:'Voicemod AI',desc:'Voicemod provides real-time AI voice transformation, voice effects and soundboard tools for games, streaming and communication apps.'}
};
const SOURCE_PAGES=new Set(['bleepingcomputer','hacker-news','securityweek','ars-security','dark-reading','the-record','cybernews','techpowerup','the-register']);
const OWN_REFRESH=new Set([...SOURCE_PAGES,'breaking','ai-tools',...Object.keys(TOOLS)]);
function newsCard(n){return `<article class="card"><a class="art" href="${esc(n.link)}" target="_blank" rel="noreferrer"><img class="news-img" src="${esc(n.image||'')}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer"></a><div class="body"><div class="meta">${esc(n.source||'News')} · ${ago(n.publishedAt)}</div><h3><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.title)}</a></h3><p>${esc(n.description||'Latest related technology news.')}</p><div class="foot"><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.source||'News')} · Read source ↗</a></div></div></article>`}
function cleanHearts(){document.querySelectorAll('.card .foot span,.story-save').forEach(s=>{if(s.matches('.story-save')||/[♡♥☆★]/.test(s.textContent||''))s.remove()})}
function restoreScroll(){try{const k='ainn-scroll:'+location.pathname+location.search,v=sessionStorage.getItem(k);if(v!==null){sessionStorage.removeItem(k);requestAnimationFrame(()=>requestAnimationFrame(()=>scrollTo(0,+v||0)))}}catch{}}
function feedKey(){return key==='search'||key==='daily-brief'?'all-news':key}
let lastSignature='';
async function checkForNewsChange(){if(OWN_REFRESH.has(key)||key==='about')return;try{const q=key==='search'?new URLSearchParams(location.search).get('q')||'':'';const url='/api/news?category='+encodeURIComponent(feedKey())+(q?'&q='+encodeURIComponent(q):'')+'&_livecheck='+Date.now();const r=await fetch(url,{cache:'no-store'});if(!r.ok)return;const j=await r.json(),sig=(j.news||[]).slice(0,12).map(x=>x.id||x.link||x.title).join('|');if(!sig)return;if(!lastSignature){lastSignature=sig;return}if(sig===lastSignature)return;lastSignature=sig;try{sessionStorage.setItem('ainn-scroll:'+location.pathname+location.search,String(scrollY))}catch{}location.reload()}catch{}}
function scheduleGlobalRefresh(){if(OWN_REFRESH.has(key)||key==='about')return;setTimeout(checkForNewsChange,5000);setInterval(()=>{if(document.visibilityState==='visible')checkForNewsChange()},REFRESH_MS)}
async function fetchRelated(tool){try{const r=await fetch('/api/news?category=all-news&q='+encodeURIComponent(tool.query)+'&_t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(String(r.status));const j=await r.json();return (j.news||[]).slice(0,24)}catch{return[]}}
async function renderToolPage(tool){const app=document.getElementById('app');if(!app)return;const y=scrollY,items=await fetchRelated(tool);app.className='';app.innerHTML=`<main class="tool-detail"><section class="tool-detail-hero"><div><a class="back" href="/">← AI News Now</a><span class="live">● VERIFIED AI TOOL</span><h1>${esc(tool.name)}</h1><p>${esc(tool.desc)}</p><span class="live-refresh-pill">Checks for new ${esc(tool.name)} news every 60 seconds · stories older than 15 days are removed</span></div><aside class="tool-official-card"><small>Official website</small><strong>${esc(tool.name)}</strong><span>${esc(tool.category)}</span><a class="tool-official-btn" href="${esc(tool.official)}" target="_blank" rel="noreferrer">Open Official Site ↗</a></aside></section><section class="tool-live-section"><div class="brief-section-title"><h2>Latest ${esc(tool.name)} news</h2><span>${items.length} recent stories</span></div>${items.length?`<div class="sectiongrid">${items.map(newsCard).join('')}</div>`:`<div class="tool-empty">No matching ${esc(tool.name)} news has been published in the last 15 days. This page checks again every 60 seconds.</div>`}<p class="tool-source-note">AI News Now links to the official product site above. News stories remain with their original publishers.</p></section></main>`;document.title=tool.name+' — AI News Now';requestAnimationFrame(()=>scrollTo(0,y));cleanHearts()}
function toolTile(t){return `<a class="tool" href="/${t.slug}/"><span class="toolicon"><span class="live-tool-glyph">${esc(t.name.slice(0,2).toUpperCase())}</span></span><span><strong>${esc(t.name)}</strong><small>${esc(t.category)}</small></span><b>VERIFIED</b></a>`}
function discoveryTile(d){const title=(d.title||'New AI tool').replace(/\s+-\s+[^-]+$/,'').slice(0,52);return `<a class="tool" href="${esc(d.link)}" target="_blank" rel="noreferrer"><span class="toolicon"><span class="live-tool-glyph">NEW</span></span><span><strong>${esc(title)}</strong><small class="live-tool-source">${esc(d.source||'Latest AI tool report')}</small></span><b data-live-badge="1">NEW</b></a>`}
async function getTools(){try{const r=await fetch('/api/ai-tools?_t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(String(r.status));return await r.json()}catch{return{verified:Object.entries(TOOLS).map(([slug,t])=>({slug,...t})),discoveries:[]}}}
async function updateHomeTools(){if(key!=='home')return;const j=await getTools(),row=document.querySelector('.toolrow'),panel=row?.closest('.tools');if(!row)return;const discoveries=(j.discoveries||[]).slice(0,2),verified=(j.verified||[]).filter(v=>v.slug).slice(0,5-discoveries.length);row.innerHTML=[...discoveries.map(discoveryTile),...verified.map(toolTile)].join('');const view=panel?.querySelector('.pt a');if(view){view.href='/ai-tools/';view.textContent='View all →'}}
async function renderToolsIndex(){const app=document.getElementById('app');if(!app)return;const j=await getTools(),verified=j.verified||[],discoveries=j.discoveries||[],y=scrollY;app.className='';app.innerHTML=`<main class="section"><div class="sectionhero"><div><a class="back" href="/">← AI News Now</a><span class="live">● LIVE AI TOOL WATCH</span><h1>New AI Tools</h1><p>Verified AI tools plus newly reported AI-tool launches from the last 15 days.</p><span class="live-refresh-pill">Updates every 60 seconds · unverified discoveries are labeled as news reports</span></div><div class="stat"><strong>${verified.length+discoveries.length}</strong><span>tools & discoveries</span><small>60-second refresh</small></div></div><section class="panel tools"><div class="pt"><span>VERIFIED AI TOOLS</span></div><div class="toolrow">${verified.map(toolTile).join('')}</div></section><section class="tool-live-section" id="latest"><div class="brief-section-title"><h2>Latest AI tool launch reports</h2><span>Last 15 days</span></div>${discoveries.length?`<div class="sectiongrid">${discoveries.map(n=>newsCard({...n,image:'/api/article-image?article='+encodeURIComponent(n.link)+'&seed='+encodeURIComponent(n.id||n.title)})).join('')}</div>`:`<div class="tool-empty">No new AI-tool launch reports have passed the live filter yet. This page checks again every 60 seconds.</div>`}</section></main>`;document.title='New AI Tools — AI News Now';requestAnimationFrame(()=>scrollTo(0,y));cleanHearts()}
function startOwnRefresh(){if(TOOLS[key]){renderToolPage(TOOLS[key]);setInterval(()=>{if(document.visibilityState==='visible')renderToolPage(TOOLS[key])},REFRESH_MS);return}if(key==='ai-tools'){renderToolsIndex();setInterval(()=>{if(document.visibilityState==='visible')renderToolsIndex()},REFRESH_MS);return}}
restoreScroll();
cleanHearts();setTimeout(cleanHearts,100);setTimeout(cleanHearts,1200);setInterval(cleanHearts,REFRESH_MS);
updateHomeTools();if(key==='home')setInterval(()=>{if(document.visibilityState==='visible')updateHomeTools()},REFRESH_MS);
startOwnRefresh();scheduleGlobalRefresh();
})();
