(()=>{
const META={
  'bleepingcomputer':{title:'BleepingComputer',desc:'Live BleepingComputer coverage of cybersecurity, Windows, ransomware, vulnerabilities, malware and technology.',refresh:60},
  'hacker-news':{title:'The Hacker News',desc:'Live The Hacker News coverage of hacking campaigns, malware, vulnerabilities, threat actors and cyber defense.',refresh:60},
  'securityweek':{title:'SecurityWeek',desc:'Live SecurityWeek reporting on enterprise security, zero-days, CISA alerts, cloud security, breaches and security vendors.',refresh:60},
  'ars-security':{title:'Ars Technica Security',desc:'Live Ars Technica security reporting with deeper technical coverage of vulnerabilities, privacy, hacking and security research.',refresh:60},
  'dark-reading':{title:'Dark Reading',desc:'Live Dark Reading coverage of application security, cloud security, threat intelligence, vulnerabilities and security operations.',refresh:60},
  'the-record':{title:'The Record',desc:'Live cyber news from Recorded Future News covering cybercrime, ransomware, nation-state operations, vulnerabilities and critical infrastructure.',refresh:60},
  'cybernews':{title:'Cybernews',desc:'Latest Cybernews security reporting covering cybercrime, vulnerabilities, breaches, malware, ransomware, privacy, threat actors and critical infrastructure.',refresh:900},
  'techpowerup':{title:'TechPowerUp',desc:'Live TechPowerUp hardware, PC technology and security news covering GPUs, CPUs, components, vulnerabilities and platform updates.',refresh:60},
  'the-register':{title:'The Register',desc:'Live The Register coverage of enterprise IT, cloud, software, hardware, security, AI, infrastructure and system administration.',refresh:60}
};
const key=location.pathname.split('/').filter(Boolean)[0]||'';const meta=META[key];if(!meta)return;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=d=>{let m=Math.max(1,Math.floor((Date.now()-new Date(d))/60000));return m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
const refreshText=meta.refresh>=900?'15 minutes':meta.refresh+' seconds';
function card(n){return `<article class="card"><a class="art" href="${esc(n.link)}" target="_blank" rel="noreferrer"><img class="news-img" src="${esc(n.image)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer"></a><div class="body"><div class="meta">${esc(n.source)} · ${ago(n.publishedAt)}</div><h3><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.title)}</a></h3><p>${esc(n.description)}</p><div class="foot"><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.source)} · Read source ↗</a></div></div></article>`}
let lastFingerprint='';
async function render(){const app=document.getElementById('app');try{const r=await fetch('/api/source-news?source='+encodeURIComponent(key)+'&_t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Source feed '+r.status);const j=await r.json(),items=j.news||[],fingerprint=items.slice(0,8).map(x=>x.id||x.link).join('|');if(fingerprint&&fingerprint===lastFingerprint&&app.querySelector('.source-live-page'))return;lastFingerprint=fingerprint;const y=window.scrollY;app.className='';app.innerHTML=`<main class="section source-live-page"><div class="sectionhero"><div><a class="back" href="/">← AI News Now</a><span class="live">● LIVE FEED</span><h1>${esc(meta.title)}</h1><p>${esc(meta.desc)}</p><span class="live-refresh-pill">Checks every ${refreshText} · stories older than 15 days are removed</span></div><div class="stat"><strong>${items.length}</strong><span>stories loaded</span><small>Refreshes every ${refreshText}</small></div></div>${items.length?`<div class="sectiongrid">${items.slice(0,50).map(card).join('')}</div>`:`<div class="simple"><div class="box"><h2>No live stories are available right now.</h2><p>The publisher feed will check again automatically in ${refreshText}.</p></div></div>`}</main>`;document.title=meta.title+' — AI News Now';requestAnimationFrame(()=>window.scrollTo(0,y))}catch(err){if(!app.querySelector('.source-live-page')){app.className='';app.innerHTML=`<main class="section source-live-page"><div class="sectionhero"><div><a class="back" href="/">← AI News Now</a><span class="live">● LIVE FEED</span><h1>${esc(meta.title)}</h1><p>${esc(meta.desc)}</p></div></div><div class="simple"><div class="box"><h2>Feed temporarily unavailable.</h2><p>This page will retry automatically in ${refreshText}.</p></div></div></main>`}}}
const app=document.getElementById('app');if(!app)return;let started=false;const start=()=>{if(started)return;started=true;setTimeout(render,30);setInterval(()=>{if(document.visibilityState==='visible')render()},meta.refresh*1000)};if(app.querySelector('.section'))start();else{const o=new MutationObserver(()=>{if(app.querySelector('.section')){o.disconnect();start()}});o.observe(app,{childList:true,subtree:true});setTimeout(()=>{o.disconnect();start()},3000)}
})();
