const TOOL_PAGES={
  'tool-magai':{title:'Magai',subtitle:'AI Presentation Maker',desc:'Live Magai news, product updates, creator workflows and related AI presentation coverage.',terms:['magai']},
  'tool-opusclip':{title:'OpusClip 2.0',subtitle:'AI Video Editor',desc:'Live OpusClip news, AI video editing updates, creator tools and short-form video coverage.',terms:['opusclip','opus clip']},
  'tool-codestral':{title:'Codestral',subtitle:'AI Coding Assistant',desc:'Live Codestral and Mistral coding-model news, developer tools, releases and AI coding coverage.',terms:['codestral','mistral']},
  'tool-leonardo-ai':{title:'Leonardo AI',subtitle:'Image Generation',desc:'Live Leonardo AI news, image-generation updates, creative tools and visual AI coverage.',terms:['leonardo ai','leonardo.ai','leonardo']},
  'tool-voicemod-ai':{title:'Voicemod AI',subtitle:'Voice Changer',desc:'Live Voicemod news, AI voice tools, speech generation, creator audio and voice-changing coverage.',terms:['voicemod']}
};
const FALLBACK='https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1800&q=90';
const e=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=x=>{let m=Math.max(1,Math.floor((Date.now()-new Date(x))/60000));return m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
const text=n=>(n.title+' '+n.description+' '+n.source).toLowerCase();
function loadFixCss(){if(!document.querySelector('link[href="/media-fix.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/media-fix.css';document.head.appendChild(l)}}
function upgradeHeader(){const top=document.querySelector('.top');if(!top)return;top.classList.add('reference-header');const brand=top.querySelector('.brand');if(brand)brand.innerHTML='<span class="brand-favicon-shell"><img class="brand-favicon" src="/favicon.svg" alt="AI News Now"></span><span class="brand-copy"><strong>AI NEWS NOW</strong><small>Your Daily Source for Everything AI</small></span>';const search=top.querySelector('.search');if(search){const b=search.querySelector('button');if(b)b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"></circle><path d="m16 16 4 4"></path></svg>';search.onsubmit=ev=>{ev.preventDefault();const q=search.querySelector('input').value.trim();if(q)location.href='/search/?q='+encodeURIComponent(q)}}const actions=top.querySelector('.actions');if(actions)actions.innerHTML='<button class="reference-action" id="theme" type="button" aria-label="Toggle light and dark theme" title="Toggle theme"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3.4"></circle><path d="M12 2.2v2.1M12 19.7v2.1M4.2 4.2l1.5 1.5M18.3 18.3l1.5 1.5M2.2 12h2.1M19.7 12h2.1M4.2 19.8l1.5-1.5M18.3 5.7l1.5-1.5"></path></svg></button><a class="reference-action bell" href="/breaking/" aria-label="Breaking news" title="Breaking news"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 9.8a5.5 5.5 0 0 1 11 0c0 6 2.2 6.1 2.2 6.1H4.3s2.2-.1 2.2-6.1"></path><path d="M9.8 19a2.5 2.5 0 0 0 4.4 0"></path></svg></a>';const theme=document.getElementById('theme');if(theme)theme.onclick=()=>document.documentElement.classList.toggle('light')}
function img(n,i){const src=/^https?:\/\//i.test(n.image||'')?n.image:FALLBACK;return `<img class="news-img" src="${e(src)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src='${FALLBACK}'">`}
function card(n,i){return `<article class="card"><a class="art" href="${e(n.link)}" target="_blank" rel="noreferrer">${img(n,i)}</a><div class="body"><div class="meta">${e(n.source)} · ${ago(n.publishedAt)}</div><h3><a href="${e(n.link)}" target="_blank" rel="noreferrer">${e(n.title)}</a></h3><p>${e(n.description||'Open the original story for full details.')}</p><div class="foot"><a href="${e(n.link)}" target="_blank" rel="noreferrer">${e(n.source)} · Read source ↗</a><span>♡</span></div></div></article>`}
function fill(primary,all,count=30){const out=[],seen=new Set();for(const n of [...primary,...all]){const k=n.link||n.id||n.title;if(!k||seen.has(k))continue;seen.add(k);out.push(n);if(out.length===count)break}return out}
async function run(){loadFixCss();upgradeHeader();const key=location.pathname.split('/').filter(Boolean)[0],cfg=TOOL_PAGES[key],app=document.getElementById('app');if(!cfg){location.replace('/ai-models/');return}document.title=`${cfg.title} News — AI News Now`;try{const r=await fetch('/api/news?category='+encodeURIComponent(key),{cache:'no-store'});if(!r.ok)throw Error('Live feed unavailable');const j=await r.json(),all=j.news||[],exact=all.filter(n=>cfg.terms.some(t=>text(n).includes(t))),items=fill(exact,all,30);app.className='';app.innerHTML=`<main class="section"><div class="sectionhero"><div><a class="back" href="/">← AI News Now</a><span class="live">● LIVE TOOL FEED</span><h1>${e(cfg.title)}</h1><p>${e(cfg.desc)}</p></div><div class="stat"><strong>${items.length}</strong><span>stories loaded</span><small>Refreshes automatically</small></div></div><div class="sectiongrid">${items.map(card).join('')}</div></main>`}catch(err){app.className='';app.innerHTML=`<main class="simple"><div class="box"><h1>${e(cfg.title)}</h1><p>The live feed is temporarily unavailable. Refresh this page in a moment.</p><a href="/">← Back to AI News Now</a></div></main>`}}
run();
