(()=>{
const KEY=location.pathname.split('/').filter(Boolean)[0]||'home';
const TOOLS={
  'tool-magai':{name:'Magai',label:'Multi-model AI workspace',official:'https://magai.co/',desc:'Magai brings many leading AI models into one workspace with model switching, reusable instructions, integrations and team collaboration.',glyph:'M'},
  'tool-opusclip':{name:'OpusClip',label:'AI video clipping & editing',official:'https://www.opus.pro/',desc:'OpusClip turns long videos into short clips and provides AI clipping, captioning, reframing and publishing workflows.',glyph:'O'},
  'tool-codestral':{name:'Codestral',label:'AI coding model by Mistral AI',official:'https://mistral.ai/news/codestral/',desc:'Codestral is Mistral AI’s code-focused model designed for code generation, completion and developer workflows.',glyph:'C'},
  'tool-leonardo-ai':{name:'Leonardo AI',label:'Generative image & video platform',official:'https://leonardo.ai/',desc:'Leonardo AI is a creator-focused generative platform for images, visual editing, custom styles and AI-powered motion/video workflows.',glyph:'L'},
  'tool-voicemod-ai':{name:'Voicemod AI',label:'AI voice changer & soundboard',official:'https://www.voicemod.com/',desc:'Voicemod provides real-time AI voices, voice effects and soundboard tools for gaming, streaming, calls and online communication.',glyph:'V'}
};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ago=x=>{const m=Math.max(1,Math.floor((Date.now()-new Date(x))/60000));return m<60?m+'m ago':m<1440?Math.floor(m/60)+'h ago':Math.floor(m/1440)+'d ago'};
function safeHttp(u=''){try{const x=new URL(u,location.href);return /^https?:$/.test(x.protocol)?x.href:''}catch{return''}}
function card(n){return `<article class="card"><a class="art" href="${esc(n.link)}" target="_blank" rel="noreferrer"><img class="news-img" src="${esc(n.image||'')}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer"></a><div class="body"><div class="meta">${esc(n.source||'News')} · ${ago(n.publishedAt)}</div><h3><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.title)}</a></h3><p>${esc(n.description||'Latest related AI-tool news.')}</p><div class="foot"><a href="${esc(n.link)}" target="_blank" rel="noreferrer">${esc(n.source||'Source')} · Read source ↗</a></div></div></article>`}
let toolFingerprint='';
async function renderVerified(cfg,key){const app=document.getElementById('app');if(!app)return;let items=[];try{const r=await fetch('/api/news?category='+encodeURIComponent(key)+'&_t='+Date.now(),{cache:'no-store'});if(r.ok){const j=await r.json();items=(j.news||[]).slice(0,18)}}catch{}const fp=items.slice(0,8).map(x=>x.id||x.link).join('|');if(fp&&fp===toolFingerprint&&app.querySelector('.tool-detail'))return;toolFingerprint=fp;const y=window.scrollY;app.className='';app.innerHTML=`<main class="tool-detail"><section class="tool-detail-hero"><div><a class="back" href="/">← AI News Now</a><span class="live">● VERIFIED AI TOOL</span><h1>${esc(cfg.name)}</h1><p>${esc(cfg.desc)}</p><span class="live-refresh-pill">Checks for related news every 60 seconds · only the last 15 days are shown</span></div><aside class="tool-official-card"><small>Official website</small><strong>${esc(cfg.label)}</strong><a class="tool-official-btn" href="${esc(cfg.official)}" target="_blank" rel="noreferrer">Open ${esc(cfg.name)} ↗</a><span class="tool-source-note">Official link verified by AI News Now. Related reporting below comes from the live news collector.</span></aside></section><section class="tool-live-section"><div class="brief-section-title"><h2>Latest ${esc(cfg.name)} news</h2><span>Newest first · refreshed every 60 seconds</span></div>${items.length?`<div class="sectiongrid">${items.map(card).join('')}</div>`:`<div class="tool-empty"><strong>No related stories from the last 15 days right now.</strong><br>The official tool page above remains available, and this page will check again automatically.</div>`}</section></main>`;document.title=cfg.name+' — AI News Now';requestAnimationFrame(()=>window.scrollTo(0,y))}
async function renderLiveTool(){const p=new URLSearchParams(location.search),name=(p.get('name')||'New AI Tool').slice(0,80),source=safeHttp(p.get('source')||''),headline=(p.get('headline')||'').slice(0,180),q=name.replace(/[^a-z0-9 ._-]/gi,' ').trim()||'AI tool';const app=document.getElementById('app');if(!app)return;let items=[];try{const r=await fetch('/api/news?category=all-news&q='+encodeURIComponent(q)+'&_t='+Date.now(),{cache:'no-store'});if(r.ok){const j=await r.json();items=(j.news||[]).slice(0,18)}}catch{}app.className='';app.innerHTML=`<main class="tool-detail"><section class="tool-detail-hero"><div><a class="back" href="/">← AI News Now</a><span class="live">● NEW AI TOOL WATCH</span><h1>${esc(name)}</h1><p>${headline?esc(headline):'A recently detected AI-tool launch or product update from the live technology feed.'}</p><span class="live-refresh-pill">Re-checks every 60 seconds · only recent coverage is kept</span></div><aside class="tool-official-card"><small>Launch / reporting source</small><strong>${esc(name)}</strong>${source?`<a class="tool-official-btn" href="${esc(source)}" target="_blank" rel="noreferrer">Open source ↗</a>`:'<span class="tool-source-note">No verified official product URL has been identified yet.</span>'}<span class="tool-source-note">Newly detected tools remain labeled as news discoveries until an official product link is verified.</span></aside></section><section class="tool-live-section"><div class="brief-section-title"><h2>Related recent coverage</h2><span>Newest first</span></div>${items.length?`<div class="sectiongrid">${items.map(card).join('')}</div>`:'<div class="tool-empty">No additional matching coverage is available yet.</div>'}</section></main>`;document.title=name+' — New AI Tool Watch'}
function waitForApp(fn){const app=document.getElementById('app');if(!app)return;let done=false;const go=()=>{if(done)return;done=true;obs.disconnect();fn()};const obs=new MutationObserver(()=>go());obs.observe(app,{childList:true});setTimeout(go,1800)}
function launchish(n){const t=(n.title+' '+(n.description||'')).toLowerCase();return /\b(ai|artificial intelligence|agent|copilot|model)\b/.test(t)&&/\b(launch|launches|launched|unveil|unveils|unveiled|introduce|introduces|introduced|release|releases|released|debuts?|new tool|new app|new platform|new assistant)\b/.test(t)&&/\b(tool|app|platform|assistant|agent|editor|generator|workspace|studio|copilot|model|service)\b/.test(t)}
function shortName(title=''){let s=title.replace(/\s+[\-|—:]\s+.*$/,'').trim();const m=s.match(/(?:launches?|unveils?|introduces?|releases?|debuts?)\s+(?:its\s+|a\s+|an\s+|new\s+)?([A-Z0-9][A-Za-z0-9.+_-]{1,28}(?:\s+[A-Z0-9][A-Za-z0-9.+_-]{1,24})?)/);if(m)s=m[1];if(s.length>42)s=s.slice(0,39)+'…';return s||'New AI Tool'}
function verifiedCards(){return Object.entries(TOOLS).map(([key,t])=>({key,name:t.name,label:t.label,href:'/'+key+'/',glyph:t.glyph,badge:'VERIFIED'}))}
async function updateHomeTools(){const row=document.querySelector('.tools .toolrow');if(!row)return;let fresh=[];try{const r=await fetch('/api/news?category=all-news&_tools='+Date.now(),{cache:'no-store'});if(r.ok){const j=await r.json();fresh=(j.news||[]).filter(launchish).slice(0,2)}}catch{}const live=fresh.map(n=>{const name=shortName(n.title);return{name,label:'New AI tool / product launch',href:'/tool-live/?name='+encodeURIComponent(name)+'&source='+encodeURIComponent(n.link)+'&headline='+encodeURIComponent(n.title),glyph:'AI',badge:'NEW',source:n.source}});const fallback=verifiedCards().filter(v=>!live.some(x=>x.name.toLowerCase()===v.name.toLowerCase())).slice(0,5-live.length);const items=[...live,...fallback].slice(0,5);row.innerHTML=items.map(t=>`<a class="tool" href="${t.href}"><span class="toolicon"><span class="live-tool-glyph">${esc(t.glyph)}</span></span><span><strong>${esc(t.name)}</strong><small>${esc(t.label)}</small>${t.source?`<small class="live-tool-source">${esc(t.source)}</small>`:''}</span><b data-live-badge="1">${esc(t.badge)}</b></a>`).join('')}
function startHomeTools(){const tryStart=()=>{if(document.querySelector('.tools .toolrow')){updateHomeTools();setInterval(()=>{if(document.visibilityState==='visible')updateHomeTools()},60000);return true}return false};if(tryStart())return;const app=document.getElementById('app');if(!app)return;const o=new MutationObserver(()=>{if(tryStart())o.disconnect()});o.observe(app,{childList:true,subtree:true});setTimeout(()=>o.disconnect(),5000)}
if(TOOLS[KEY]){waitForApp(()=>{renderVerified(TOOLS[KEY],KEY);setInterval(()=>{if(document.visibilityState==='visible')renderVerified(TOOLS[KEY],KEY)},60000)})}
else if(KEY==='tool-live'){waitForApp(()=>{renderLiveTool();setInterval(()=>{if(document.visibilityState==='visible')renderLiveTool()},60000)})}
else if(KEY==='home')startHomeTools();
})();
