import Link from "next/link";
import { notFound } from "next/navigation";
import { CheckCircle2, Clock3, FlaskConical, Lightbulb, TerminalSquare } from "lucide-react";
import { books, getBook, getChapter } from "@/lib/books";
import { BookProgress } from "@/components/book-progress";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";

export function generateStaticParams() { return books.flatMap((book) => book.chapters.map((chapter) => ({ book: book.slug, chapter: chapter.slug }))); }

export default async function ChapterPage({ params }: { params: Promise<{ book: string; chapter: string }> }) {
  const values = await params; const book = getBook(values.book); if (!book) notFound(); const chapter = getChapter(book, values.chapter); if (!chapter) notFound(); const number = book.chapters.indexOf(chapter) + 1;
  return <div className="space-y-6">
    <BookProgress bookSlug={book.slug} chapterSlug={chapter.slug} chapters={book.chapters} />
    <article className="mx-auto max-w-5xl">
      <header className="network-card rounded-2xl p-6 sm:p-9"><Link href={`/books/${book.slug}`} className="font-mono text-xs text-primary hover:underline">{book.shortTitle} / TABLE OF CONTENTS</Link><div className="mt-4 flex flex-wrap gap-2"><Badge>Chapter {number}</Badge><Badge variant="outline">{chapter.level}</Badge><Badge variant="outline"><Clock3 />60-minute guided session</Badge></div><h1 className="mt-5 text-3xl font-bold tracking-tight sm:text-5xl">{chapter.title}</h1><p className="mt-4 text-lg leading-8 text-muted-foreground">{chapter.summary}</p><div className="mt-7 rounded-xl border bg-background/40 p-5"><p className="font-mono text-xs text-primary">LEARNING OBJECTIVES</p><ul className="mt-3 grid gap-2 sm:grid-cols-2">{chapter.objectives.map((item) => <li key={item} className="flex gap-2 text-sm leading-6"><CheckCircle2 className="mt-1 size-4 shrink-0 text-emerald-400" />{item}</li>)}</ul></div></header>
      <div className="my-6 grid grid-cols-4 overflow-hidden rounded-xl border text-center text-xs"><div className="bg-primary/15 p-3"><strong className="block text-primary">25 min</strong>Deep read</div><div className="p-3"><strong className="block">20 min</strong>Guided lab</div><div className="bg-primary/5 p-3"><strong className="block">10 min</strong>Recall</div><div className="p-3"><strong className="block">5 min</strong>Review</div></div>
      <div className="space-y-6">{chapter.sections.map((section, index) => <section key={section.title} id={`section-${index + 1}`} className="network-card rounded-2xl p-6 sm:p-8"><p className="font-mono text-xs text-primary">SECTION {number}.{index + 1}</p><h2 className="mt-2 text-2xl font-bold">{section.title}</h2><div className="mt-5 space-y-4 text-[16px] leading-8 text-muted-foreground">{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="mt-6 rounded-xl border border-primary/20 bg-primary/5 p-4"><p className="flex items-center gap-2 font-semibold"><Lightbulb className="size-4 text-primary" />Checkpoint</p><ul className="mt-3 space-y-2">{section.checkpoints.map((item) => <li key={item} className="flex gap-2 text-sm leading-6"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary" />{item}</li>)}</ul></div></section>)}</div>
      <section className="network-card mt-6 rounded-2xl p-6 sm:p-8"><div className="flex items-center gap-3 text-primary"><FlaskConical /><p className="font-mono text-xs">GUIDED LAB · APPROX. 20 MINUTES</p></div><h2 className="mt-3 text-2xl font-bold">{chapter.lab.title}</h2><p className="mt-3 leading-7 text-muted-foreground">{chapter.lab.scenario}</p><ol className="mt-5 space-y-3">{chapter.lab.steps.map((step, index) => <li key={step} className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-primary/10 font-mono text-xs text-primary">{index + 1}</span><span className="pt-0.5 leading-6">{step}</span></li>)}</ol><div className="mt-6 rounded-xl bg-slate-950 p-5 text-slate-100"><p className="flex items-center gap-2 font-mono text-xs text-cyan-300"><TerminalSquare className="size-4" />VERIFICATION STANDARD</p><ul className="mt-3 space-y-2">{chapter.lab.verify.map((item) => <li key={item} className="text-sm leading-6">✓ {item}</li>)}</ul></div></section>
      <section className="network-card mt-6 rounded-2xl p-6 sm:p-8"><p className="eyebrow">Retrieval review</p><h2 className="mt-2 text-2xl font-bold">Answer before revealing</h2><Accordion type="multiple" className="mt-4">{chapter.review.map((item, index) => <AccordionItem key={item.question} value={`q-${index}`}><AccordionTrigger><span className="pr-4 text-left">{index + 1}. {item.question}</span></AccordionTrigger><AccordionContent><p className="rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-4 leading-7">{item.answer}</p></AccordionContent></AccordionItem>)}</Accordion></section>
    </article>
  </div>;
}
