export type BookChapter = {
  slug: string;
  title: string;
  level: string;
  summary: string;
  objectives: string[];
  sections: { title: string; paragraphs: string[]; checkpoints: string[] }[];
  lab: { title: string; scenario: string; steps: string[]; verify: string[] };
  review: { question: string; answer: string }[];
};

export type NetworkBook = {
  slug: string;
  shortTitle: string;
  title: string;
  subtitle: string;
  audience: string;
  accent: string;
  chapters: BookChapter[];
};

const section = (title: string, paragraphs: string[], checkpoints: string[]) => ({ title, paragraphs, checkpoints });
const chapter = (
  slug: string,
  title: string,
  level: string,
  summary: string,
  objectives: string[],
  sections: BookChapter["sections"],
  lab: BookChapter["lab"],
  review: BookChapter["review"],
): BookChapter => ({ slug, title, level, summary, objectives, sections, lab, review });

const standardReview = (topic: string, proof: string, failure: string): BookChapter["review"] => [
  { question: `Explain ${topic} without using an acronym.`, answer: proof },
  { question: "Which evidence should you collect before changing configuration?", answer: `Record the current state, expected state, interface or protocol counters, and the exact scope of the failure. ${proof}` },
  { question: "What is the safest troubleshooting sequence?", answer: `Define the symptom, establish the boundary, test one hypothesis, make one controlled change, verify service, and document the result. A likely fault in this chapter is ${failure}.` },
];

const ccnaChapters: BookChapter[] = [
  chapter("networking-first-principles", "Networking from Zero", "Foundation", "Build the mental model that every later chapter uses: endpoints exchange data through links and intermediary devices according to agreed rules.",
    ["Identify hosts, switches, routers, access points, and firewalls", "Distinguish LAN, WAN, Internet, and cloud networks", "Trace one message from an application to a remote server"],
    [
      section("Why networks exist", ["A network lets independent devices exchange information and share services. A phone requesting a web page is a client for that moment; the system answering is a server. The request is divided into manageable units, identified with addresses, carried across one or more links, and reassembled at the destination. Networking is therefore not one device or cable—it is a coordinated delivery system.", "Endpoints create and consume data. Intermediary devices move or protect it. A switch usually forwards frames inside a local network by using MAC addresses. A router connects IP networks and chooses a next hop. An access point bridges wireless clients into a wired LAN, while a firewall applies security policy to traffic crossing a boundary."], ["A role describes behavior, not device size", "One device can provide several services", "Always identify source, destination, path, and policy"]),
      section("LANs, WANs, and the Internet", ["A LAN covers a local administrative area such as a home, floor, or campus segment. Ethernet and Wi-Fi dominate the access layer. A WAN connects separated locations using a service provider or an overlay across the Internet. The Internet is a network of independently operated networks that exchange reachability; it is not a single cloud or company.", "Bandwidth is the maximum transmission capacity of a link. Throughput is the useful rate achieved. Latency is delay, jitter is variation in delay, and loss is data that never arrives. Voice is sensitive to latency and jitter; backups usually care more about throughput. Good design starts with the application's behavior rather than a fashionable device."], ["LAN and WAN describe scope and ownership", "Bandwidth does not guarantee throughput", "Measure latency, jitter, loss, and utilization separately"]),
      section("A packet's first journey", ["When a user enters a URL, the host commonly resolves a name through DNS, determines whether the destination is local, discovers the next-hop link-layer address, and sends an Ethernet frame. A switch forwards that frame toward the default gateway. The router removes the incoming frame, examines the IP packet, selects a route, decreases the IPv4 TTL, and builds a new frame for the next link.", "The frame changes at every routed hop; the end-to-end IP source and destination normally remain the same unless a translator changes them. Application data is encapsulated as it moves down the stack and decapsulated at the receiver. This distinction explains why a remote server's MAC address never appears on your home LAN."], ["Frames are local-hop containers", "Packets cross routed boundaries", "The default gateway handles off-subnet destinations"]),
    ],
    { title: "Map a real packet path", scenario: "A laptop on Wi-Fi opens a public website through a home or lab router.", steps: ["Draw the laptop, access point, switch/router, ISP, and server.", "Label the local IP address, prefix, default gateway, and DNS server.", "Run ipconfig /all or ip addr, then ping the gateway.", "Run nslookup and tracert/traceroute to the site.", "For every hop, state what can change and what should remain end to end."], verify: ["The gateway replies locally", "DNS returns at least one address", "The trace demonstrates routed hops even if some routers suppress replies"] },
    standardReview("packet delivery", "A host encapsulates application data, sends local frames toward a gateway, and routers forward the IP packet one hop at a time.", "an incorrect address, gateway, DNS setting, or physical link")),

  chapter("models-and-encapsulation", "OSI, TCP/IP, and Encapsulation", "Foundation", "Use layered models as practical troubleshooting maps rather than vocabulary lists.",
    ["Map common protocols to TCP/IP and OSI layers", "Describe encapsulation and decapsulation", "Choose the correct layer for a symptom"],
    [
      section("Layers divide responsibility", ["The OSI model separates communication into seven conceptual layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application. The TCP/IP model combines these into Link, Internet, Transport, and Application. Real protocols do not always respect perfect boundaries, but the models give engineers a shared language and a disciplined order for diagnosis.", "At Layer 1, bits become electrical, optical, or radio signals. Layer 2 provides local delivery with frames and MAC addresses. Layer 3 provides logical addressing and routing. Layer 4 identifies application conversations with ports and offers TCP reliability or UDP simplicity. Upper layers represent application formats and services."], ["Models organize functions; they do not generate traffic", "A symptom can span several layers", "Start with facts, then use the model to narrow scope"]),
      section("Encapsulation", ["An application produces data. TCP may add source and destination ports, sequence information, and flags to create a segment; UDP creates a datagram with a smaller header. IP adds logical addresses to form a packet. Ethernet adds MAC addresses and error-detection information to create a frame. The physical medium carries encoded bits.", "At a router, Layer 2 encapsulation is removed and replaced for the outgoing link. At the final host, headers are interpreted in reverse order and the payload is delivered to the correct process. Protocol data unit names—data, segment/datagram, packet, frame, bits—help pinpoint what a capture or counter actually measures."], ["Encapsulation adds control information", "Routers rewrite Layer 2 headers", "Ports identify conversations, not physical sockets"]),
      section("TCP and UDP", ["TCP establishes state, numbers bytes, acknowledges received data, retransmits loss, and controls flow. Its three-way handshake synchronizes a connection before application exchange. UDP has no handshake, delivery guarantee, or built-in ordering; that lowers overhead and lets the application choose how to handle loss. DNS can use either, voice commonly uses UDP, and HTTPS normally uses TCP or QUIC over UDP.", "Reliability is an end-to-end behavior, not proof that the network is healthy. Repeated TCP retransmissions may reveal congestion, loss, duplex problems, or an overloaded server. A successful ping only tests selected ICMP behavior; it does not prove that a TCP service port or application is available."], ["TCP is stateful and reliable", "UDP favors simplicity and application control", "Test the protocol actually used by the service"]),
    ],
    { title: "Read a packet capture", scenario: "Use Wireshark while opening a site and translate observed fields into a layered story.", steps: ["Start a capture on the active adapter.", "Resolve a hostname and open its HTTPS page.", "Filter for dns, arp, icmp, and tcp.", "Select one frame and expand Ethernet, IP, and TCP or UDP.", "Write the source/destination identifier used at each layer."], verify: ["DNS maps a name to an IP address", "A frame contains a packet and transport payload", "TCP flags or UDP length match the selected exchange"] },
    standardReview("encapsulation", "Each layer adds information for its scope; the receiver processes those headers in reverse order.", "testing the wrong layer or assuming ping proves the application")),

  chapter("ethernet-and-cabling", "Ethernet, Cabling, and Switching", "Foundation", "Learn how bits become frames and how a switch builds local forwarding intelligence.",
    ["Select copper, fiber, and wireless media", "Explain MAC learning and frame forwarding", "Interpret interface status and errors"],
    [
      section("Media and interfaces", ["Copper Ethernet uses twisted pairs and is limited by cable category, distance, interference, and transceiver capability. Fiber carries light, supports longer distances and high rates, and comes in multimode and single-mode forms. The connector must fit, but the optic wavelength, fiber type, and supported distance must also match. Auto-negotiation normally chooses the best common speed and duplex.", "An interface that is administratively down was disabled in configuration. Down/down commonly indicates a physical problem; up/down points toward a data-link issue. Counters such as CRC errors, input errors, drops, and late collisions provide evidence. Replace or reseat components only after confirming the fault domain."], ["Match cable, optic, wavelength, and distance", "Full duplex has no collisions", "Interface state and counters tell different parts of the story"]),
      section("MAC learning and forwarding", ["A switch learns the source MAC address of every valid incoming frame and associates it with the ingress port and VLAN. It then looks up the destination MAC. A known unicast is sent only toward the learned port; an unknown unicast is flooded within the VLAN. Broadcasts are also flooded, while a frame destined to the source port is filtered.", "Entries age out so the table can adapt when devices move. The table is per VLAN because each VLAN is a separate Layer 2 broadcast domain. A switch does not learn from the destination field. These rules let you predict behavior from show mac address-table rather than guessing."], ["Learn source; forward by destination", "Flooding stays inside the VLAN", "A MAC table is dynamic state, not configuration"]),
      section("Ethernet frame integrity", ["Ethernet frames include destination and source MAC addresses, a type/length field, payload, and a frame check sequence. The receiver calculates a value and discards a frame when the FCS does not match. Layer 2 detects corruption but does not retransmit the frame; higher layers or applications decide whether recovery is needed.", "MTU limits the Layer 3 payload a frame can carry. A mismatch can cause fragmentation, drops, or applications that partially work. Troubleshoot with interface counters, consistent speed/duplex, and appropriately sized pings where supported."], ["FCS detects corruption", "Ethernet itself does not repair loss", "MTU problems can be path- and application-specific"]),
    ],
    { title: "Prove switch learning", scenario: "Two hosts communicate through a Cisco switch while you observe the table.", steps: ["Record interface status with show interfaces status.", "Clear the dynamic MAC table in a safe lab.", "Ping between hosts.", "Display show mac address-table dynamic.", "Disconnect one host or move it to another port and observe relearning."], verify: ["Source MAC addresses appear on expected ports", "Both hosts remain in the same VLAN", "Interface counters do not show growing physical errors"] },
    standardReview("Ethernet switching", "A switch learns source MAC addresses and forwards using the destination MAC within one VLAN.", "bad cabling, mismatched settings, or the wrong VLAN")),

  chapter("ipv4-and-subnetting", "IPv4 Addressing and Subnetting", "Core", "Turn binary boundaries into a repeatable method for designing and troubleshooting subnets.",
    ["Convert between prefix length and mask", "Calculate network, broadcast, and usable host ranges", "Create a VLSM addressing plan"],
    [
      section("Address and prefix", ["An IPv4 address is 32 bits. The prefix identifies the network portion; remaining bits identify an interface within that subnet. A /24 mask contains 24 leading ones, leaving eight host bits. Hosts compare their own address and destination against the mask to decide whether to send directly or through the default gateway.", "Private ranges are 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16. They are not routed across the public Internet and are commonly translated at an edge. APIPA 169.254.0.0/16 often indicates that a host could not obtain DHCP service."], ["The mask defines locality", "Addresses alone do not reveal subnet size", "Private does not automatically mean secure"]),
      section("A reliable calculation method", ["Find the interesting octet—the mask octet that is neither 255 nor 0. The block size is 256 minus that mask value. Multiples of the block size mark subnet boundaries. The containing boundary is the network; the next boundary minus one is the broadcast. Values between them are ordinary host addresses for conventional subnets.", "For /27, the mask is 255.255.255.224 and block size is 32. Subnets begin at .0, .32, .64, and so forth. Address 192.0.2.77/27 belongs to 192.0.2.64/27, broadcasts at .95, and has conventional usable addresses .65 through .94."], ["Block size = 256 − interesting mask octet", "Network addresses align to the block", "Show your boundary work to prevent mistakes"]),
      section("VLSM and route summaries", ["Variable-length subnet masking assigns different prefix sizes according to need. Allocate the largest subnet first, then continue on valid boundaries. A point-to-point link can use a very small subnet, while a user VLAN requires room for clients, infrastructure, and growth. Avoid overlapping allocations and document reserved addresses.", "Summarization advertises one larger prefix that covers several contiguous, properly aligned subnets. It reduces routing state but can attract traffic for an unused component range, so a matching discard route may be required. A summary must never claim destinations reachable through a different path."], ["Allocate largest requirements first", "Every subnet begins on its own boundary", "Summaries require contiguity and alignment"]),
    ],
    { title: "Design a branch address plan", scenario: "Allocate 10.44.0.0/24 for 90 users, 40 voice devices, 20 servers, and two point-to-point links.", steps: ["Convert each requirement to required host bits.", "Allocate the largest block first.", "Record network, prefix, gateway convention, usable range, and broadcast.", "Assign remaining links without overlap.", "Check each sample host by binary or block-size method."], verify: ["Every requirement fits with growth margin", "All networks are aligned and nonoverlapping", "Gateways are usable addresses and masks are consistent"] },
    standardReview("IPv4 subnetting", "The prefix determines network and host bits; calculate boundaries before assigning any address.", "a wrong mask, overlapping subnet, or invalid gateway")),

  chapter("ipv6", "IPv6 Addressing and Neighbor Discovery", "Core", "Understand IPv6 notation, address scopes, SLAAC, and the ICMPv6 functions that replace ARP.",
    ["Compress and expand IPv6 addresses", "Distinguish global, link-local, multicast, and unique-local scope", "Explain SLAAC and neighbor discovery"],
    [
      section("Address structure", ["IPv6 addresses are 128 bits written as eight hexadecimal hextets. Leading zeros within a hextet may be omitted, and one continuous run of zero hextets may be replaced by ::. The double-colon rule can be used only once because the final address must still expand unambiguously to eight hextets.", "Global unicast addresses are commonly allocated from 2000::/3. Link-local addresses use FE80::/10 and are required for many local control functions. Unique-local FC00::/7 space is intended for internal use. IPv6 has multicast and anycast but no broadcast."], ["One hextet represents 16 bits", "Use :: only once", "Scope determines where an address is valid"]),
      section("SLAAC and DHCPv6", ["A router advertisement tells hosts the prefix and how to obtain addressing information. With SLAAC, a host combines an advertised /64 prefix with an interface identifier, then performs duplicate address detection. DHCPv6 can provide stateful addresses or additional information. The RA flags guide behavior, but the default gateway is learned from router advertisements, not a DHCPv6 default-router option.", "A stable plan normally uses /64 on host-facing links. Randomized temporary addresses can improve privacy, so one endpoint may hold several global addresses. Troubleshooting must examine source-address selection, prefix length, RA reception, and neighbor state."], ["SLAAC depends on router advertisements", "A host can have multiple valid addresses", "Default-router learning remains an RA function"]),
      section("Neighbor Discovery", ["IPv6 Neighbor Discovery uses ICMPv6 messages for router discovery, address resolution, reachability, and duplicate detection. Neighbor Solicitation and Advertisement replace ARP behavior using multicast. Because ICMPv6 also supports essential control and Path MTU Discovery, blindly blocking it can break otherwise valid communication.", "A router decreases the IPv6 Hop Limit at each hop. Routers do not fragment transit packets; endpoints adjust size using Path MTU information. Security controls should permit required ICMPv6 types while rejecting inappropriate traffic."], ["NDP is built on ICMPv6", "IPv6 routers do not fragment transit packets", "ICMPv6 is operationally essential"]),
    ],
    { title: "Build a dual-stack LAN", scenario: "Enable IPv4 and IPv6 between two router LANs and compare control-plane behavior.", steps: ["Assign global and link-local IPv6 addresses.", "Enable IPv6 routing and confirm router advertisements.", "Inspect host addresses and neighbor tables.", "Ping by link-local address with the required interface scope.", "Trace global IPv6 reachability."], verify: ["Each LAN uses a distinct /64", "Neighbors resolve without ARP", "Routes and source addresses match the intended path"] },
    standardReview("IPv6 delivery", "Hosts use prefixes, router advertisements, and ICMPv6 Neighbor Discovery to establish local and routed communication.", "a missing RA, wrong prefix, filtered ICMPv6, or bad route")),

  chapter("ios-operations", "Cisco IOS and Device Operations", "Core", "Configure safely, verify deliberately, and preserve a known-good device state.",
    ["Navigate IOS modes and contextual help", "Secure management access with SSH", "Save, back up, and validate configuration"],
    [
      section("CLI state and configuration", ["IOS separates user EXEC, privileged EXEC, global configuration, and subconfiguration modes. The prompt shows your context. Use ? for context-aware help, Tab for completion, and do show from configuration mode where supported. A command takes effect in the running configuration; it does not automatically survive a restart.", "The startup configuration is loaded during boot. copy running-config startup-config saves intentional changes. Before a large change, capture the current configuration and essential show output, define rollback criteria, and avoid pasting commands you cannot explain."], ["Prompt context prevents misplaced commands", "Running and startup configurations are different", "Verification is part of every change"]),
      section("Secure management plane", ["Set a unique hostname, protect privileged access with a secret, create named administrative users, enable SSH version 2, and restrict VTY lines to SSH. RSA key generation requires a hostname and domain name on many platforms. Local authentication is useful in a lab; centralized AAA is preferred at scale.", "Place management on a controlled subnet or dedicated VRF when available. Apply an access class so only trusted sources can reach the device. Disable unused services and never treat an encrypted-looking legacy password as strong protection."], ["Use SSH, not Telnet", "Limit both identity and source network", "The management plane deserves its own policy"]),
      section("Operational evidence", ["show running-config reveals intended configuration; show interfaces and show ip interface brief reveal operational state. Protocol-specific commands such as show ip route, show vlan brief, and show spanning-tree prove learned or computed state. Logs and time synchronization add chronology.", "A configuration line is not proof of success. Translate every requirement into at least one verification command and an expected observation. When results differ, preserve evidence before clearing counters or restarting a process."], ["Configured state and operational state can disagree", "Expected output should be defined in advance", "Preserve evidence before resetting it"]),
    ],
    { title: "Secure a fresh IOS device", scenario: "Prepare a lab router or switch for safe local administration.", steps: ["Set identity, domain, user, and enable secret.", "Generate appropriate RSA keys and force SSH v2.", "Configure VTY login local and transport input ssh.", "Apply a source restriction in the lab.", "Save the configuration and reconnect using SSH."], verify: ["SSH succeeds with the named user", "Telnet is rejected", "The intended configuration survives a controlled reload"] },
    standardReview("safe IOS operation", "Work in the correct mode, make controlled changes, and prove operational state before saving.", "an unsaved configuration, permissive VTY access, or an unverified paste")),

  chapter("vlans-trunks", "VLANs, Trunks, and Inter-VLAN Routing", "Core", "Segment one switch fabric into intentional broadcast domains and connect them through Layer 3.",
    ["Configure access and trunk ports", "Explain 802.1Q tagging and native VLAN behavior", "Implement and verify inter-VLAN routing"],
    [
      section("VLAN boundaries", ["A VLAN creates a logical Layer 2 broadcast domain. Hosts in different VLANs require routing even when connected to the same physical switch. Access ports normally carry one data VLAN untagged toward an endpoint. The switch internally associates every learned MAC and forwarded frame with a VLAN.", "Segmentation reduces broadcast scope and supports policy, but a VLAN is not complete security by itself. Use a consistent naming, numbering, and addressing plan. Unused ports should be disabled and placed in an unused VLAN according to policy."], ["One VLAN equals one Layer 2 broadcast domain", "Different VLANs require a Layer 3 hop", "VLAN membership must match the endpoint purpose"]),
      section("802.1Q trunks", ["A trunk carries multiple VLANs by inserting an 802.1Q tag that includes a VLAN identifier. Native VLAN frames are ordinarily untagged, so both ends must agree. An allowed VLAN list limits which VLANs cross the link and should be explicit in controlled designs.", "A trunk can be physically up while one VLAN fails because it is missing, pruned, blocked, or inconsistently native. Verify administrative mode, operational mode, native VLAN, allowed VLANs, and forwarding VLANs rather than relying on one command."], ["Tags preserve VLAN identity across a link", "Native VLAN mismatches create risk and confusion", "Allowed and forwarding are different states"]),
      section("Routing between VLANs", ["Router-on-a-stick uses one router interface with 802.1Q subinterfaces. A multilayer switch instead uses switch virtual interfaces and hardware forwarding. Each VLAN receives a unique IP subnet and a gateway address within that subnet. ip routing must be enabled on a multilayer switch when it should route.", "A healthy gateway interface does not prove the access path. Confirm endpoint mask/gateway, access VLAN, VLAN existence, trunk carriage, SVI line protocol, and routing table in order. An SVI may stay down when no active Layer 2 port exists in that VLAN."], ["Each VLAN needs a distinct subnet", "An SVI is the Layer 3 presence of a VLAN", "Trace both Layer 2 and Layer 3 state"]),
    ],
    { title: "Create a two-VLAN campus", scenario: "Users and servers share two switches but must occupy separate IP networks.", steps: ["Create and name both VLANs.", "Assign endpoint ports as static access ports.", "Configure an 802.1Q trunk with an explicit allowed list.", "Create gateway SVIs or router subinterfaces.", "Test same-VLAN and inter-VLAN reachability."], verify: ["MAC addresses appear in the intended VLAN", "The trunk carries both VLANs", "Endpoints reach their gateway and permitted remote VLAN"] },
    standardReview("VLAN forwarding", "Access ports classify endpoint traffic, trunks retain VLAN identity, and a Layer 3 gateway connects different VLANs.", "a wrong access VLAN, missing allowed VLAN, native mismatch, or down SVI")),

  chapter("stp-etherchannel", "Spanning Tree and EtherChannel", "Core", "Build redundant Layer 2 paths without creating forwarding loops.",
    ["Predict root bridge and port roles", "Explain rapid spanning-tree convergence", "Configure and troubleshoot LACP EtherChannel"],
    [
      section("Why loops are dangerous", ["Ethernet has no hop-count field. A Layer 2 loop can circulate broadcasts and unknown unicasts indefinitely, consuming bandwidth and causing unstable MAC learning. Spanning Tree Protocol creates a loop-free logical tree while keeping redundant links available for recovery.", "Switches elect the lowest bridge ID as root. Each non-root switch selects its lowest-cost root port. Each segment receives a designated port; other redundant ports block or discard. Root placement should be intentional and aligned with gateway and traffic design."], ["Redundancy without control creates loops", "The lowest bridge ID wins root election", "Cost is evaluated toward the root"]),
      section("Rapid STP behavior", ["Rapid PVST+ runs a rapid spanning-tree instance per VLAN. It uses discarding, learning, and forwarding states and distinguishes alternate paths for faster convergence. Edge ports connected to single endpoints can transition quickly with PortFast, while BPDU Guard can disable an edge port if it unexpectedly receives BPDUs.", "PortFast does not disable spanning tree and should not be used blindly between switches. Root Guard, Loop Guard, and BPDU Guard protect different assumptions. Choose a control based on the failure you are preventing."], ["PortFast is for trusted edge behavior", "BPDU Guard protects the edge boundary", "Verify the root and roles per VLAN"]),
      section("EtherChannel", ["EtherChannel bundles compatible physical links into one logical port-channel. Spanning tree sees one link, while traffic is distributed according to a hash. LACP uses active and passive modes; at least one side must be active. All member links must agree on relevant Layer 2 characteristics.", "The hash typically selects a member per flow rather than splitting every packet evenly. One large flow may therefore use one physical link. Troubleshoot the port-channel first, then member consistency, negotiation state, and physical counters."], ["A port-channel is one logical STP link", "LACP active can initiate; passive only responds", "Load balance is hash-based, not guaranteed equal bandwidth"]),
    ],
    { title: "Build a resilient access layer", scenario: "Two switches use two parallel links without looping.", steps: ["Record the initial STP root and port roles.", "Configure matching LACP channel groups.", "Apply trunk settings consistently to the port-channel.", "Verify the bundle and spanning-tree view.", "Shut one member and measure continuity, then restore it."], verify: ["Both members show bundled state", "STP sees the port-channel", "Traffic continues after one member fails"] },
    standardReview("loop-free redundancy", "STP blocks redundant logical paths while EtherChannel combines compatible links into one controlled path.", "an unintended root, unsafe edge feature, or mismatched channel member")),

  chapter("routing-ospf", "Routing, Static Routes, and OSPF", "Advanced CCNA", "Read a routing table as a decision process, then exchange reachability dynamically with single-area OSPF.",
    ["Predict longest-prefix routing decisions", "Configure static, default, and floating routes", "Establish and verify single-area OSPFv2"],
    [
      section("The routing decision", ["A router selects the most specific matching prefix—longest prefix match. When routes describe the same prefix, administrative distance chooses among sources, and a routing protocol metric chooses among paths learned by that protocol. These are separate decisions and should not be blended.", "The selected route identifies an exit interface, a next hop, or both. Recursive lookup may be required to resolve a next-hop address. A route in the table does not guarantee the return path, that policy permits traffic, or that the destination service is running."], ["Longest prefix match comes first", "Administrative distance compares route sources", "Reachability requires forward and return paths"]),
      section("Static and default routes", ["A static route explicitly maps a prefix to a next hop or exit. A default route 0.0.0.0/0 matches when no more-specific route exists. A floating static route uses a higher administrative distance than the preferred dynamic route, becoming eligible only when that preferred route disappears.", "Pointing an Ethernet route only to an exit interface can create unnecessary neighbor resolution for many destinations. Fully specified routes can be useful on multiaccess links. Track the availability that matters; a directly connected interface may remain up even when a failure exists farther away."], ["Default is the least-specific route", "Floating routes need a deliberately higher distance", "Interface up is not end-to-end proof"]),
      section("Single-area OSPF", ["OSPF is a link-state protocol. Routers form adjacencies, describe links in LSAs, build a common link-state database, and run SPF to calculate routes. Neighbors must agree on key parameters including area, timer behavior on a link, network compatibility, and authentication where used.", "Router ID identifies the OSPF speaker. Interface cost influences path selection. On broadcast networks, DR and BDR election reduces adjacency overhead; it does not select the default gateway. Use passive interfaces on user LANs to advertise the subnet without seeking neighbors."], ["Neighbors exchange topology, not whole routing tables periodically", "Area 0 is the backbone", "Passive prevents adjacency but still advertises the connected network"]),
    ],
    { title: "Route a three-router topology", scenario: "Three routers need dynamic primary paths and a static backup exit.", steps: ["Address interfaces and prove direct neighbors.", "Enable OSPF process and set explicit router IDs.", "Place participating links in area 0 and make user LANs passive.", "Add a higher-distance floating default where appropriate.", "Fail one link and inspect adjacency and route changes."], verify: ["Neighbors reach FULL state where expected", "Routes show the correct OSPF code and next hop", "The backup appears only after preferred reachability is removed"] },
    standardReview("route selection and OSPF", "Routers select the longest matching prefix; OSPF computes paths from a synchronized link-state view.", "a missing return route, neighbor parameter mismatch, or incorrect network statement")),

  chapter("ip-services-security", "IP Services and Security Fundamentals", "Advanced CCNA", "Connect client networks to essential services while applying minimum necessary access.",
    ["Explain DHCP, DNS, NAT, NTP, SNMP, and syslog", "Apply standard and extended ACL logic", "Harden the access layer and management plane"],
    [
      section("Services make addressing usable", ["DHCP automates address, mask, gateway, and option delivery through Discover, Offer, Request, and Acknowledge exchanges. A relay forwards client broadcasts to a remote server and records the receiving subnet. DNS maps names to records; DNS failure can look like total connectivity loss even when IP routing works.", "NTP aligns clocks so logs correlate. Syslog exports events with severity. SNMP polls or receives notifications about managed objects. These services become operationally valuable only when time, source interfaces, credentials, and retention are designed consistently."], ["DHCP relay belongs on the client gateway", "Separate name resolution from raw reachability", "Correct time turns events into a timeline"]),
      section("NAT and ACL processing", ["Static NAT creates a fixed mapping. Dynamic NAT uses a pool. PAT distinguishes many inside sessions by transport identifiers while sharing fewer public addresses. NAT changes address information; it is not a security policy by itself and can complicate protocols or troubleshooting.", "ACLs are processed top down, stop at the first match, and end with an implicit deny. Standard ACLs match source IPv4 addresses; extended ACLs can match protocol, source, destination, and ports. Place entries intentionally, use remarks, and verify hit counters. An ACL applied in the wrong direction can appear correct but never see the intended traffic."], ["NAT translates; policy permits or denies", "ACL order is functional logic", "Direction is from the interface's perspective"]),
      section("Layer 2 and device hardening", ["Port security can restrict learned MAC addresses on access ports. DHCP snooping builds a trusted binding database; Dynamic ARP Inspection can validate ARP against it; IP Source Guard can restrict source use. These controls depend on correct trust boundaries and should be staged carefully.", "Use SSH, strong secrets, least-privilege AAA, protected management networks, disabled unused services, and current software. Security is layered: prevent, limit, detect, and recover. Backups and tested restoration are security controls because availability and integrity matter."], ["Trust only infrastructure-facing ports where required", "Layer 2 protections depend on accurate bindings", "Recovery capability is part of security"]),
    ],
    { title: "Secure and service a user VLAN", scenario: "A user VLAN needs DHCP, Internet PAT, restricted server access, and visible logs.", steps: ["Configure or relay DHCP and verify a lease.", "Configure PAT with clearly identified inside and outside interfaces.", "Write an extended ACL from an explicit policy table.", "Enable time and logging destinations.", "Test permitted and denied flows and examine counters."], verify: ["Clients receive correct options", "Translations appear only for intended sources", "ACL counters and timestamps match test traffic"] },
    standardReview("network services and policy", "Services provide addressing, naming, translation, time, and evidence; ACLs enforce ordered packet policy.", "a wrong helper address, NAT role, ACL order/direction, or unsynchronized clock")),

  chapter("wireless-automation-capstone", "Wireless, Automation, and the CCNA Capstone", "Advanced CCNA", "Connect radio fundamentals and controller-based networking to a repeatable automation mindset.",
    ["Explain WLAN architecture and RF tradeoffs", "Read JSON and REST API interactions", "Troubleshoot a complete small enterprise path"],
    [
      section("Wireless is a shared medium", ["Wi-Fi clients contend for airtime. Channel width, signal strength, interference, client capability, and retransmissions affect usable capacity. 2.4 GHz travels well but offers fewer non-overlapping channels; 5 and 6 GHz provide more spectrum with different range and client constraints. More access points are not automatically better when channels and power are poorly planned.", "An SSID is a service name, while the BSSID identifies a radio interface for that service. Enterprise WLANs may use controllers for policy and coordination. Authentication proves identity; encryption protects frames; segmentation and firewall policy still control what an authenticated client may reach."], ["Design for airtime, not only signal bars", "Coverage and capacity are separate goals", "WPA2/WPA3 security still needs network policy"]),
      section("Controller and API thinking", ["Controller-based networks separate intent and centralized policy from distributed forwarding. An underlay supplies IP reachability; an overlay creates logical connectivity on top. APIs let software request or inspect state using defined resources and methods rather than screen scraping.", "REST commonly uses GET to read, POST to create, PUT or PATCH to update, and DELETE to remove. JSON represents objects, arrays, strings, numbers, booleans, and null. Always inspect status codes, authentication requirements, schema, pagination, and error responses before trusting an automation."], ["An API is a contract", "JSON syntax and data meaning are different concerns", "Read and validate before making changes"]),
      section("Capstone troubleshooting", ["A complete incident can involve endpoint configuration, radio or cable, VLAN access, trunking, STP, gateway state, route selection, ACLs, NAT, DNS, and the application. Do not change all layers at once. Define a specific failed flow and compare it with a working flow to establish the smallest useful boundary.", "Build a hypothesis from evidence, predict what a test should show, and change one variable. After restoration, verify adjacent services and document root cause. This method is more valuable than memorizing one command because it transfers to unfamiliar networks."], ["A precise failed flow has source, destination, protocol, and time", "Comparison narrows the fault domain", "A fix without verified root cause may be temporary"]),
    ],
    { title: "CCNA integrated capstone", scenario: "A wireless user can reach the gateway but cannot open an internal application or the Internet.", steps: ["Record client address, WLAN, VLAN, gateway, DNS, and signal state.", "Test gateway, remote IP, DNS resolution, and application port separately.", "Trace VLAN/trunk/SVI, routing, ACL, and NAT state.", "Retrieve interface state from a sample JSON/API response or supplied file.", "Repair one planted fault and write an evidence-based incident note."], verify: ["The application works by name", "Policy permits only intended traffic", "Your note identifies root cause, proof, change, and post-change validation"] },
    standardReview("wireless and automated operations", "Reliable service combines healthy RF and access layers with validated intent, APIs, routing, policy, and applications.", "interference, wrong VLAN, broken DNS, filtered traffic, or unsafe automation")),
];

const encorChapters: BookChapter[] = [
  chapter("enterprise-architecture", "Enterprise Architecture and Design", "ENCOR Core", "Translate business requirements into modular, resilient campus, branch, WAN, and cloud boundaries.", ["Compare two-tier, three-tier, fabric, and cloud designs", "Choose redundancy by failure domain", "Relate control, management, and data planes"], [
    section("Modularity and failure domains", ["A modular design groups functions into repeatable blocks with clear boundaries. Campus access connects endpoints, distribution aggregates policy and Layer 3 boundaries, and core transport provides fast resilient connectivity. A collapsed core combines distribution and core roles for smaller environments. The right model follows scale, convergence, operations, and risk—not a fixed number of boxes.", "Redundancy should remove a specific single point of failure without multiplying uncontrolled states. Device, link, power, control-plane, provider, and geographic failures require different answers. Document what must survive, for how long, and with what reduced capacity."], ["Design around services and failure domains", "Redundancy has operational cost", "Convergence targets must be measurable"]),
    section("Planes and forwarding", ["The data plane forwards user traffic, the control plane builds forwarding knowledge, and the management plane supports configuration and observation. Hardware platforms may use specialized forwarding tables such as CEF's FIB and adjacency table so packets do not require a routing-process lookup on every hop.", "Protecting the management plane does not automatically protect the control plane. Rate limits, protocol authentication, infrastructure ACLs, out-of-band access, and telemetry contribute to different layers of resilience."], ["Separate where traffic moves from how state is learned", "Hardware forwarding depends on programmed state", "Protect each plane according to its exposure"]),
  ], { title: "Defend an enterprise design", scenario: "Design a two-building campus with redundant Internet and a cloud application.", steps: ["List business services and recovery objectives.", "Draw access, aggregation, core/edge, WAN, and cloud boundaries.", "Mark every failure domain and the surviving path.", "Select Layer 2 versus Layer 3 boundaries.", "Define three measurable acceptance tests."], verify: ["No critical service depends on one undocumented component", "Routing and gateway ownership are clear", "Operational complexity matches team capability"] }, standardReview("enterprise architecture", "A modular design places clear policy and failure boundaries around measurable service requirements.", "unexamined shared fate or an ambiguous Layer 2 boundary")),

  chapter("virtualization-overlays", "Virtualization, VRFs, and Overlays", "ENCOR Core", "Separate tenants and transport logical networks across shared infrastructure.", ["Explain device, path, and network virtualization", "Use VRF and GRE concepts", "Trace VXLAN and LISP control/data roles"], [
    section("Separation on shared hardware", ["Virtualization lets one physical system support multiple logical contexts. VRFs maintain separate routing tables so identical prefixes can exist without exchanging traffic. VLANs separate Layer 2 domains; VRFs separate Layer 3 decisions. Route leaking is an explicit policy operation, not an automatic consequence of sharing a device.", "A virtual switch, firewall context, or hypervisor adds operational boundaries that may not match physical cabling. Troubleshooting must identify the tenant, table, namespace, and encapsulation before interpreting a route or capture."], ["Always name the forwarding context", "Isolation and reachability are deliberate policies", "Physical adjacency does not imply logical adjacency"]),
    section("Tunnels and overlays", ["GRE encapsulates a passenger packet inside another IP packet and supports multiple Layer 3 protocols, but it does not provide confidentiality by itself. IPsec can add authentication and encryption. VXLAN carries Layer 2 segments over an IP underlay using VNIs and tunnel endpoints, expanding segmentation beyond traditional VLAN limits.", "LISP separates endpoint identity from routing location and maps one to the other. In fabric designs, the underlay must first provide stable IP reachability; the overlay then expresses endpoint connectivity and policy. A broken overlay can therefore be a symptom of an underlay fault."], ["Encapsulation adds overhead and MTU requirements", "Underlay reachability precedes overlay health", "Control-plane mapping and data-plane tunneling are distinct"]),
  ], { title: "Trace an overlay packet", scenario: "Two endpoints in one virtual network communicate through an IP fabric.", steps: ["Label endpoint identity, VNI, tunnel endpoints, and underlay next hops.", "Calculate header overhead and required MTU.", "Verify the underlay route between tunnel endpoints.", "Inspect control-plane mapping.", "Follow encapsulation and decapsulation in each direction."], verify: ["The underlay never needs endpoint MAC knowledge", "Both tunnel endpoints agree on segmentation", "Return mapping and MTU are valid"] }, standardReview("network virtualization", "Logical tables and encapsulations isolate services while a stable underlay carries their packets.", "wrong VRF, missing mapping, unreachable tunnel endpoint, or insufficient MTU")),

  chapter("advanced-campus", "Advanced Campus: STP, EtherChannel, and FHRP", "ENCOR Infrastructure", "Engineer predictable Layer 2 and gateway resilience with aligned control-plane roles.", ["Tune MST/Rapid PVST root placement", "Diagnose multi-chassis and LACP behavior", "Compare HSRP, VRRP, and gateway redundancy"], [
    section("Campus convergence", ["Root placement, gateway active role, and uplink preference should align so ordinary traffic does not cross an unnecessary peer link. MST maps many VLANs to fewer spanning-tree instances, but switches must agree on region name, revision, and VLAN mapping; a mismatch creates a region boundary.", "Loop protections encode design assumptions. Root Guard rejects a superior root where one should never appear. Loop Guard protects against a unidirectional loss of BPDUs on non-designated links. UDLD can detect one-way physical connectivity on supported media."], ["Align Layer 2 root and Layer 3 gateway", "MST region consistency is exact", "Each protection addresses a different failure"]),
    section("First-hop resilience", ["HSRP and VRRP present a virtual default gateway while routers coordinate active ownership. Priority and tracking influence which device forwards. Preemption allows a preferred device to resume ownership but can cause churn if upstream health is unstable.", "The gateway protocol can be healthy while upstream routing is broken. Track an object representing real service reachability and test failover, failback, ARP refresh, and capacity. Stateful services may need additional symmetry planning."], ["Virtual gateway reachability is only the first hop", "Tracking should represent the important dependency", "Test convergence in both directions"]),
  ], { title: "Align a resilient distribution pair", scenario: "Two distribution switches serve several access switches and VLAN gateways.", steps: ["Set explicit STP primary/secondary roles per VLAN group.", "Align FHRP active ownership with the preferred root.", "Bundle compatible uplinks with LACP.", "Add safe edge and loop protections.", "Fail each uplink and distribution device separately."], verify: ["Normal traffic follows the intended path", "No test creates a Layer 2 loop", "Gateway recovery meets the defined target"] }, standardReview("campus resilience", "Align spanning-tree, port-channel, and first-hop roles to produce a predictable surviving path.", "role misalignment, inconsistent MST data, or tracking the wrong object")),

  chapter("enterprise-routing", "OSPF, EIGRP, BGP, and Route Policy", "ENCOR Infrastructure", "Control reachability and path choice across multiple routing domains without confusing protocol-specific decisions.", ["Interpret OSPF and EIGRP neighbor/path state", "Explain BGP best-path attributes", "Apply redistribution and filtering safely"], [
    section("IGP scaling", ["OSPF areas constrain link-state flooding and SPF impact. ABRs connect areas to backbone area 0 and can summarize appropriate ranges. EIGRP uses DUAL to select successors and loop-free feasible successors based on reported and feasible distance. Stubs limit query scope.", "Adjacency is only the first health signal. Confirm database or topology information, installed routes, next-hop resolution, and forwarding. Summaries, passive interfaces, authentication, MTU, and policy can produce partial reachability."], ["Scale control-plane scope deliberately", "Neighbor up does not equal route installed", "Summarization must match topology"]),
    section("BGP and policy", ["BGP advertises reachable prefixes with path attributes. Weight and local preference influence outbound choice within an organization; AS path length and origin are evaluated later; MED can suggest an inbound entry to a neighbor. Exact order and platform behavior matter, but policy intent matters more than memorized lists.", "Route maps combine match conditions and set actions. Prefix lists match address ranges with length constraints. Redistribution crosses routing information between domains and can create feedback loops, suboptimal paths, or lost attributes. Tag routes and define one-way ownership wherever possible."], ["BGP is a policy protocol", "Prefix length conditions change prefix-list meaning", "Redistribution needs loop prevention and seed metrics"]),
  ], { title: "Build a controlled routing boundary", scenario: "A campus IGP connects to two edge routers that exchange selected prefixes with BGP.", steps: ["Establish IGP and BGP adjacencies independently.", "Advertise only owned, validated prefixes.", "Set local preference for the primary outbound edge.", "Filter invalid or overly specific routes.", "Fail the primary edge and inspect control and forwarding planes."], verify: ["No unintended prefixes cross the boundary", "Selected paths match policy", "Failure converges without a redistribution loop"] }, standardReview("enterprise routing policy", "IGPs calculate internal reachability while BGP and policy control which prefixes and paths cross domains.", "an unfiltered advertisement, unresolved next hop, or redistribution feedback loop")),

  chapter("wireless-enterprise", "Enterprise Wireless Architecture", "ENCOR Infrastructure", "Design and troubleshoot controller-based wireless from RF cells through tunnels and policy.", ["Compare centralized, FlexConnect, and cloud management", "Explain CAPWAP and AP modes", "Diagnose roaming, authentication, and RF health"], [
    section("Control, data, and RF", ["A lightweight AP commonly forms CAPWAP control and possibly data tunnels to a controller. Central switching concentrates policy; FlexConnect can switch selected traffic locally at a branch. AP modes such as local, monitor, sniffer, bridge, and sensor serve different operational goals.", "RF design starts with measured coverage, capacity, interference, and client behavior. Receive signal, signal-to-noise ratio, channel utilization, retries, and data rates reveal more than a coverage icon. A wide channel increases theoretical capacity but consumes more spectrum and can raise contention."], ["Know where client data is switched", "Controller reachability and user forwarding can fail separately", "Capacity planning is client and airtime planning"]),
    section("Identity and roaming", ["Enterprise authentication often uses 802.1X/EAP with a RADIUS server, while WPA2/WPA3 protects the wireless link. The EAP method determines credential and certificate requirements. A client can associate at Layer 2 yet fail authorization, DHCP, DNS, or policy later.", "Roaming depends on overlapping coverage, consistent WLAN/security, client decisions, and possibly fast-transition support. Troubleshoot the timeline: discovery, authentication, association, address continuity, and application impact."], ["Association is not full service", "Certificates require trusted identity and correct time", "Roaming is largely client-driven"]),
  ], { title: "Troubleshoot a roaming user", scenario: "A voice client drops calls while moving between two AP cells.", steps: ["Collect RSSI, SNR, retry, channel, and roam timestamps.", "Confirm WLAN, security, VLAN, and policy consistency.", "Check authentication latency and certificate validity.", "Compare controller/AP events with client evidence.", "Adjust one RF or policy variable and retest the same path."], verify: ["The roam completes within the application tolerance", "No coverage hole or excessive overlap remains", "Addressing and policy persist as designed"] }, standardReview("enterprise WLAN operation", "Wireless service combines RF, AP/controller transport, authentication, addressing, and policy in a measurable timeline.", "poor SNR, channel contention, slow authentication, or mismatched WLAN policy")),

  chapter("assurance-security", "Network Assurance and Infrastructure Security", "ENCOR Operations", "Turn telemetry into defensible evidence and protect management, control, and data planes.", ["Use syslog, SNMP, NetFlow, SPAN, IP SLA, and telemetry", "Build a structured troubleshooting hypothesis", "Apply device and infrastructure security controls"], [
    section("Evidence sources", ["Syslog records discrete events; SNMP exposes managed state and sends notifications; NetFlow summarizes conversations; SPAN copies packets; IP SLA generates synthetic tests; streaming telemetry publishes structured measurements. Each answers a different question. Correlate them using reliable time and stable device identity.", "Baselines define normal ranges by time and service. An alert without baseline or service context creates noise. Start with the user-visible symptom, choose the evidence source that can disprove a hypothesis, and preserve raw observations."], ["Choose evidence to answer a question", "Time synchronization enables correlation", "A baseline makes thresholds meaningful"]),
    section("Defense in depth", ["Control Plane Policing protects device processing capacity. Infrastructure ACLs restrict traffic destined to infrastructure addresses. AAA centralizes authentication, authorization, and accounting. MACsec can protect Ethernet links, while segmentation and TrustSec concepts express policy between groups.", "Secure APIs with authenticated encrypted transport, least privilege, input validation, secret management, and logging. Do not embed production credentials in scripts. A technically correct control can still cause an outage when staged without reachability tests and rollback."], ["Protect management, control, and data planes separately", "Least privilege applies to automation identities", "Security changes require an access-preserving rollback"]),
  ], { title: "Investigate and harden a routed edge", scenario: "An edge router shows intermittent latency and abnormal management attempts.", steps: ["Define normal latency and traffic baselines.", "Correlate syslog, flow, interface, and IP SLA evidence.", "Identify management and control-plane destinations.", "Draft least-privilege infrastructure and management policy.", "Stage controls and prove legitimate administration remains available."], verify: ["The incident timeline uses synchronized evidence", "Untrusted management traffic is blocked", "Routing protocols and monitoring still work"] }, standardReview("assurance and infrastructure security", "Correlated telemetry tests hypotheses while layered controls limit access to each device plane.", "unsynchronized evidence, noisy thresholds, or an overbroad security rule")),

  chapter("sdn-automation", "SD-WAN, SD-Access, APIs, and Automation", "ENCOR Advanced", "Understand controller domains and automate validation safely with structured data.", ["Explain SD-WAN and SD-Access component roles", "Interpret REST, NETCONF, RESTCONF, YANG, and JSON", "Write safe Python-style automation logic"], [
    section("Intent-based domains", ["Cisco SD-WAN separates orchestration, management, control, and edge forwarding roles. Policies can influence application-aware paths across multiple transports. SD-Access uses a fabric underlay and overlay, endpoint mapping, segmentation, and policy to simplify campus intent.", "Controllers reduce device-by-device work but create dependencies on identity, certificate, time, reachability, and consistent source-of-truth data. Always identify which component owns intended state and which system reports operational truth."], ["Controllers centralize intent, not physical forwarding", "Underlays remain foundational", "Certificates and time are infrastructure dependencies"]),
    section("Programmability safely", ["YANG models define data structure. NETCONF commonly exchanges XML over SSH and supports datastores and transactions. RESTCONF exposes modeled data through HTTP concepts. Other REST APIs often use JSON. An API response must be checked for status, schema, and completeness before its values drive a change.", "A safe workflow discovers state, validates preconditions, calculates a bounded change, previews the difference, applies to a small scope, verifies, and can roll back. Idempotent logic reaches the intended state repeatedly without accumulating duplicate configuration."], ["Model, encoding, transport, and protocol are separate", "Handle errors and pagination explicitly", "Idempotence reduces repeated-run risk"]),
  ], { title: "Automate a compliance check", scenario: "Validate interface descriptions and administrative state from structured device data.", steps: ["Define the intended schema and required fields.", "Read a sample JSON response and reject missing values.", "Compare actual with intended state without changing anything.", "Produce a proposed change list and human-readable report.", "Simulate one failed request and one partial response."], verify: ["No change occurs during discovery", "Errors stop unsafe execution", "A second compliant run proposes no changes"] }, standardReview("controller-based automation", "Modeled APIs expose intent and state; safe automation validates data, limits scope, verifies results, and remains repeatable.", "trusting incomplete data, missing rollback, or an unstable underlay")),

  chapter("encor-capstone", "ENCOR Troubleshooting Capstone", "ENCOR Mastery", "Integrate architecture, infrastructure, wireless, assurance, security, and automation into one operational method.", ["Build multi-layer fault trees", "Prioritize evidence and blast radius", "Communicate root cause and prevention"], [
    section("Fault isolation at enterprise scale", ["Begin with a service statement: who cannot do what, from where, using which protocol, and since when. Compare a working path. Map dependencies across access, fabric, routing, security, DNS, application, and external providers. The best next test divides plausible causes rather than merely collecting more output.", "Control-plane health, RIB state, FIB programming, adjacency resolution, and application success are distinct checkpoints. In virtualized networks, add VRF and tunnel context. In wireless networks, add RF and authentication timelines."], ["Define the failed service precisely", "Use tests that split the fault tree", "Check intended, learned, and forwarded state"]),
    section("Recovery and learning", ["Stabilize the service with the least risky reversible action, but do not confuse mitigation with root cause. Capture evidence before resets. After recovery, prove the original flow, adjacent services, redundancy, monitoring, and persistence.", "A strong incident record states impact, timeline, evidence, root cause, contributing conditions, corrective action, and preventive follow-up. It avoids blaming individuals and connects each conclusion to observable facts."], ["Mitigation restores; correction removes cause", "Post-change validation must exceed one ping", "Prevention should address system conditions"]),
  ], { title: "Operate the ENCOR capstone", scenario: "After a change, one branch loses SaaS access, one campus VLAN is slow, and monitoring shows a tunnel alarm.", steps: ["Separate symptoms that share a timeline from those sharing a cause.", "Map the service dependencies and current change set.", "Collect targeted client, interface, route, flow, tunnel, and policy evidence.", "Restore the highest-impact service with a reversible action.", "Write root cause, validation, rollback, and prevention notes."], verify: ["Each conclusion cites evidence", "All intended paths and redundancy tests pass", "The prevention item is specific and owned"] }, standardReview("enterprise troubleshooting", "Precise scope and hypothesis-driven tests connect user impact to control, forwarding, policy, and application evidence.", "treating correlated alarms as proven cause or changing multiple variables")),
];

const enterpriseChapters: BookChapter[] = [
  chapter("choose-your-path", "Understanding CCNP Enterprise", "Track Orientation", "Plan the certification and skill path correctly: CCNP Enterprise is earned through the ENCOR core exam plus one concentration exam.", ["Distinguish the certification from its exams", "Match concentration options to job goals", "Build a lab-centered study plan"], [
    section("Core plus concentration", ["CCNP Enterprise is a professional-level certification track, not a single exam. The core ENCOR exam establishes shared enterprise knowledge across architecture, virtualization, infrastructure, assurance, security, and automation. A concentration exam then proves depth in a chosen specialty.", "Concentration choices evolve, so verify Cisco's current official list before scheduling. Common skill directions include advanced routing and services, enterprise design, SD-WAN, wireless design, wireless implementation, and automation. Choose for the work you want to perform, not merely the title that seems easiest."], ["ENCOR provides breadth", "A concentration provides depth", "Always verify the current official exam program"]),
    section("Professional study method", ["Professional-level preparation requires explanation, configuration, verification, and troubleshooting. Build small labs that isolate one control-plane behavior, then combine them into failure scenarios. Read command output as evidence and explain why rejected alternatives are wrong.", "Maintain a lab journal with intent, topology, configuration delta, expected result, observed result, failure injected, and recovery. This converts repetition into reusable operational knowledge and portfolio material without exposing proprietary environments."], ["Study protocols as state machines and decisions", "Failure injection reveals hidden assumptions", "Document sanitized evidence of mastery"]),
  ], { title: "Create your CCNP plan", scenario: "Choose a concentration and translate its blueprint into a 12-week lab plan.", steps: ["Write the target job responsibilities.", "Compare current official concentration blueprints.", "Score each domain by knowledge and hands-on confidence.", "Assign one explain/configure/verify/troubleshoot lab per weak domain.", "Schedule review and two integrated capstones."], verify: ["The chosen concentration maps to job goals", "Every domain has a measurable lab outcome", "The schedule includes retrieval practice and recovery time"] }, standardReview("the CCNP Enterprise path", "Earn the track by passing ENCOR and one current concentration, then demonstrate the skills through hands-on evidence.", "treating the certification as one exam or studying only definitions")),
  ...encorChapters.slice(0, 7),
];

export const books: NetworkBook[] = [
  { slug: "ccna", shortTitle: "CCNA Book", title: "CCNA: From First Packet to Network Mastery", subtitle: "An original, beginner-first course that grows from zero experience into confident routing, switching, security, wireless, automation, and troubleshooting.", audience: "No networking experience required", accent: "cyan", chapters: ccnaChapters },
  { slug: "encor", shortTitle: "CCNP ENCOR", title: "CCNP ENCOR: Enterprise Core in Practice", subtitle: "A systems-level guide to enterprise architecture, virtualization, infrastructure, assurance, security, and automation.", audience: "For CCNA-level learners moving into enterprise core", accent: "violet", chapters: encorChapters },
  { slug: "ccnp-enterprise", shortTitle: "CCNP Enterprise", title: "CCNP Enterprise: Professional Track Guide", subtitle: "A professional roadmap that joins ENCOR breadth with concentration-level thinking, deep labs, and operational capstones.", audience: "For engineers pursuing the full CCNP Enterprise track", accent: "emerald", chapters: enterpriseChapters },
];

export function getBook(slug: string) {
  return books.find((book) => book.slug === slug);
}

export function getChapter(book: NetworkBook, slug: string) {
  return book.chapters.find((item) => item.slug === slug);
}
