import { ccnaDomain, type CcnaCase } from "./ccna-ticket-types";

export const ccnaTicketCatalog1: CcnaCase[] = [
...ccnaDomain("Physical interfaces and cabling", [
{title:"Desk port link is up but large transfers fail with CRC errors",rootCause:"A damaged copper patch cable on Gi1/0/18 is generating FCS/CRC errors under load.",change:"The desk was moved and the patch lead was pinched under a rolling cabinet.",complaint:"The user can browse simple pages, but Teams calls freeze and large file copies fail.",evidence:"ACC1# show interfaces gi1/0/18 | include line protocol|CRC|input error\nGigabitEthernet1/0/18 is up, line protocol is up\n  9321 input errors, 9107 CRC, 0 frame, 0 overrun",fix:"! Replace the patch cable with a certified known-good cable\nclear counters GigabitEthernet1/0/18"},
{title:"Legacy printer runs at half duplex while switch is full duplex",rootCause:"The printer NIC is fixed at 100/half while the switch port is fixed at 100/full, creating a duplex mismatch.",change:"The printer was replaced but the old fixed switch-port settings were kept.",complaint:"Print jobs eventually complete, but the printer is extremely slow during busy periods.",evidence:"ACC2# show interfaces gi1/0/24 | include Duplex|collision|CRC\n  Full-duplex, 100Mb/s\n  812 late collisions, 1193 collisions, 64 CRC",fix:"interface GigabitEthernet1/0/24\n speed 100\n duplex half\n! Or return both sides to auto-negotiation if the printer supports it"},
{title:"Fiber uplink stays down after patch-panel work",rootCause:"The transmit and receive fiber strands were crossed incorrectly so each side transmits into the other transmitter instead of its receiver.",change:"The building uplink was moved to a new LC patch-panel position.",complaint:"The switch sees the SFP but the uplink remains down/down.",evidence:"ACC3# show interfaces transceiver detail | section Te1/1/1\nTx Power -2.3 dBm\nRx Power -40.0 dBm\nACC3# show interface te1/1/1 status\nTe1/1/1 notconnect",fix:"! Correct fiber polarity so local TX reaches remote RX and remote TX reaches local RX\ninterface TenGigabitEthernet1/1/1\n no shutdown"},
{title:"Wrong optic type prevents link after switch replacement",rootCause:"A 10G-LR optic was installed on one side while the far end still uses a 10G-SR optic over multimode fiber.",change:"A replacement switch was staged with the wrong spare transceiver.",complaint:"The fiber is known-good but the new switch never establishes link to distribution.",evidence:"ACC4# show inventory | include SFP\nNAME: \"Te1/1/1\" DESCR: \"SFP-10G-LR\"\nDIST1# show inventory | include SFP\nNAME: \"Te1/0/5\" DESCR: \"SFP-10G-SR\"",fix:"! Install matching optics appropriate for the fiber plant on both ends\n! Verify wavelength/fiber type and optical power before restoring service"},
{title:"PoE phone keeps rebooting because switch power budget is exhausted",rootCause:"The access switch has insufficient remaining PoE budget after multiple high-power APs were added.",change:"Six new access points were connected to the same switch stack earlier that morning.",complaint:"Several desk phones repeatedly power-cycle even though their Ethernet ports remain configured correctly.",evidence:"ACC5# show power inline\nAvailable: 0.0(w) Used: 740.0(w) Remaining: 0.0(w)\nGi1/0/32  auto  off  0.0  n/a  n/a",fix:"! Restore adequate PoE capacity: rebalance powered devices, add/restore PSU capacity, or move endpoints\nshow power inline"},
{title:"Interface is administratively down after maintenance",rootCause:"Gi1/0/10 was left in shutdown state after a maintenance test.",change:"The cabling team disabled the port while tracing a wall jack and never re-enabled it.",complaint:"A desktop shows no network connection and the switch LED is dark.",evidence:"ACC1# show ip interface brief | include Gi1/0/10\nGigabitEthernet1/0/10 unassigned YES unset administratively down down",fix:"interface GigabitEthernet1/0/10\n no shutdown"},
{title:"Access link flaps because of a loose patch-panel termination",rootCause:"An intermittent physical termination at the patch panel causes repeated link up/down events.",change:"A closet cleanup moved cable bundles and placed tension on the termination.",complaint:"The user loses network access for a few seconds several times per hour.",evidence:"ACC6# show logging | include Gi1/0/14\n%LINK-3-UPDOWN: Interface Gi1/0/14, changed state to down\n%LINK-3-UPDOWN: Interface Gi1/0/14, changed state to up\n%LINK-3-UPDOWN: Interface Gi1/0/14, changed state to down",fix:"! Reseat/reterminate the patch-panel connection and replace suspect patch leads\nclear counters GigabitEthernet1/0/14"},
{title:"User port is forced to 100 Mbps instead of 1 Gbps",rootCause:"The switch interface has a manual `speed 100` setting left from an old endpoint.",change:"A new gigabit-capable workstation replaced a legacy device on the same port.",complaint:"The workstation works but file transfers are capped near Fast Ethernet speeds.",evidence:"ACC7# show interfaces gi1/0/7 | include BW|Duplex\n  MTU 1500 bytes, BW 100000 Kbit/sec\n  Full-duplex, 100Mb/s",fix:"interface GigabitEthernet1/0/7\n speed auto\n duplex auto"},
{title:"Input errors increase only during high temperature periods",rootCause:"A marginal copper transceiver/media converter is failing when the closet temperature rises.",change:"The closet HVAC was turned off overnight for building maintenance.",complaint:"A remote camera feed becomes unreliable every afternoon but appears normal early in the morning.",evidence:"ACC8# show interfaces gi1/0/44 | include input error|CRC\n  4682 input errors, 4511 CRC\nACC8# show environment all | include Temperature\nInlet Temperature: 42 C",fix:"! Restore environmental cooling and replace the marginal media converter/transceiver\n! Verify errors remain stable after the repair"},
{title:"Cable length beyond specification causes intermittent gigabit errors",rootCause:"A copper horizontal run exceeds supported Ethernet distance and is producing signal errors.",change:"A temporary office was connected using an additional long extension cable.",complaint:"The endpoint links at 1 Gbps but randomly drops packets and renegotiates.",evidence:"ACC9# show interfaces gi1/0/11 counters errors\nPort Align-Err FCS-Err Xmit-Err Rcv-Err\nGi1/0/11 0 1847 0 1912",fix:"! Replace the over-length copper path with a standards-compliant run or fiber\n! Remove the temporary extension and certify the permanent cable"}
]),
...ccnaDomain("IPv4 addressing and subnetting", [
{title:"PC configured with /16 instead of /24 treats remote subnet as local",rootCause:"The workstation mask is 255.255.0.0 while the production VLAN is 10.20.30.0/24.",change:"The user manually copied an old static addressing example.",complaint:"The PC reaches some local devices but cannot reliably reach another 10.20.x.x subnet through the router.",evidence:"PC> ipconfig\nIPv4 Address . . . : 10.20.30.55\nSubnet Mask  . . . : 255.255.0.0\nDefault Gateway . : 10.20.30.1",fix:"! Correct the host mask to 255.255.255.0 or restore DHCP\n! Renew addressing and verify ARP versus routed behavior"},
{title:"Static server uses the wrong default gateway",rootCause:"The server gateway is configured as 10.40.20.254 instead of the SVI gateway 10.40.20.1.",change:"The server was migrated from a network that used .254 as its gateway convention.",complaint:"Local VLAN access works, but the server cannot reply to clients on other subnets.",evidence:"SERVER> ipconfig\nIPv4 Address: 10.40.20.50\nMask: 255.255.255.0\nGateway: 10.40.20.254\nDIST1# show ip interface brief | include Vlan420\nVlan420 10.40.20.1 YES manual up up",fix:"! Set server default gateway to 10.40.20.1\n! Verify remote ping and return traffic"},
{title:"Two printers were assigned the same static IPv4 address",rootCause:"Both printers use 10.55.10.25, causing ARP entries to alternate between two MAC addresses.",change:"A new printer was installed using a duplicated spreadsheet row.",complaint:"Users print to the wrong device and both printers periodically disappear.",evidence:"DIST1# show ip arp 10.55.10.25\nInternet 10.55.10.25 0 3c52.82aa.7710 ARPA Vlan551\n<later>\nInternet 10.55.10.25 0 aabb.ccdd.ee11 ARPA Vlan551",fix:"! Assign a unique IP address to one printer and update DNS/print-server records\nclear ip arp 10.55.10.25"},
{title:"New subnet overlaps an existing routed network",rootCause:"A branch LAN was configured as 10.70.0.0/23 while an existing site already owns 10.70.1.0/24, creating overlap.",change:"The branch subnet was expanded without checking IPAM.",complaint:"Traffic to 10.70.1.x follows inconsistent local and WAN paths.",evidence:"BR1# show ip route connected | include 10.70\nC 10.70.0.0/23 is directly connected, Vlan70\nCORE# show ip route 10.70.1.0\nO 10.70.1.0/24 via 10.1.1.2",fix:"! Renumber the branch to a non-overlapping prefix approved in IPAM\n! Remove the overlapping interface subnet and update DHCP/routing"},
{title:"Broadcast address was assigned to a host",rootCause:"A static device was given 192.168.44.255 on a /24 network, which is the subnet broadcast address.",change:"A technician selected the highest-looking address without checking subnet boundaries.",complaint:"The device cannot communicate normally even though the cable and switch port are healthy.",evidence:"DEVICE: 192.168.44.255/24 gateway 192.168.44.1\nSW1# show mac address-table interface gi1/0/9\n<MAC learned normally>",fix:"! Assign a valid host address from 192.168.44.1-254 excluding reserved infrastructure addresses"},
{title:"Host address belongs to a different /26 than its gateway",rootCause:"The client is 10.88.14.70/26 while its configured gateway 10.88.14.1 belongs to 10.88.14.0/26.",change:"A static address was copied from the next subnet without changing the gateway.",complaint:"The workstation cannot ARP for its configured default gateway.",evidence:"PC> ipconfig\nIP 10.88.14.70\nMask 255.255.255.192\nGateway 10.88.14.1",fix:"! Use the correct gateway for the 10.88.14.64/26 subnet or assign an address from the gateway's subnet"},
{title:"Point-to-point link uses addresses from different /30 networks",rootCause:"R1 is 10.1.5.1/30 while R2 is 10.1.5.6/30, so the interfaces are not on the same subnet.",change:"One side was configured from the wrong row in the circuit worksheet.",complaint:"Both router interfaces are up/up but direct ping to the peer fails.",evidence:"R1# show ip interface brief | include Gi0/0\nGi0/0 10.1.5.1 YES manual up up\nR2# show ip interface brief | include Gi0/0\nGi0/0 10.1.5.6 YES manual up up",fix:"! Correct one side so both addresses belong to the same approved /30\n! Example: R2 Gi0/0 = 10.1.5.2 255.255.255.252"},
{title:"Host uses public-looking address inside private LAN after manual change",rootCause:"A user statically configured 172.32.10.44 believing all 172.x.x.x addresses are private; the approved subnet is 172.20.10.0/24.",change:"DHCP was bypassed during troubleshooting.",complaint:"The PC can no longer reach the local gateway or internal applications.",evidence:"PC> ipconfig\nIPv4 172.32.10.44\nMask 255.255.255.0\nGateway 172.20.10.1",fix:"! Restore DHCP or configure an approved address in 172.20.10.0/24\n! Document that RFC1918 172/12 is 172.16.0.0-172.31.255.255"},
{title:"Wrong /27 mask places half the users outside the local subnet",rootCause:"The gateway SVI is /27 while the DHCP scope hands out addresses intended for a /26.",change:"The subnet was expanded but the SVI mask was not updated.",complaint:"Clients with lower addresses work; clients above the /27 boundary fail to reach the gateway correctly.",evidence:"DIST2# show run interface vlan 90\n ip address 10.90.0.1 255.255.255.224\nDHCP scope: 10.90.0.0/26",fix:"interface Vlan90\n ip address 10.90.0.1 255.255.255.192"},
{title:"Secondary IP subnet removed before legacy hosts were migrated",rootCause:"The old 10.100.20.0/24 secondary SVI address was removed while several static hosts still use that subnet.",change:"A cleanup change assumed all endpoints had moved to 10.100.30.0/24.",complaint:"Most users work, but a small group of legacy devices suddenly lost their default gateway.",evidence:"DIST1# show ip interface vlan 100\nInternet address is 10.100.30.1/24\nLEGACY1: 10.100.20.45/24 gateway 10.100.20.1",fix:"interface Vlan100\n ip address 10.100.20.1 255.255.255.0 secondary\n! Then complete the planned host migration before removing it again"}
]),
...ccnaDomain("IPv6 addressing and neighbor discovery", [
{title:"IPv6 client receives no global address because router advertisements are suppressed",rootCause:"The user SVI has `ipv6 nd ra suppress all`, preventing SLAAC and default-router discovery.",change:"A server-VLAN hardening template was copied to a user VLAN.",complaint:"IPv4 works, but clients show only FE80:: link-local addresses for IPv6.",evidence:"DIST1# show ipv6 interface vlan 620\nIPv6 is enabled\nND router advertisements are suppressed (all)",fix:"interface Vlan620\n no ipv6 nd ra suppress all"},
{title:"Wrong IPv6 /64 typed on the gateway SVI",rootCause:"The SVI uses 2001:db8:63:1::1/64 while IPAM assigns 2001:db8:63::/64 to the VLAN.",change:"The address was entered manually during dual-stack deployment.",complaint:"IPv4 works but IPv6 hosts cannot reach the expected default gateway prefix.",evidence:"DIST2# show ipv6 interface brief | include Vlan630\nVlan630 [up/up]\n  2001:DB8:63:1::1",fix:"interface Vlan630\n no ipv6 address 2001:db8:63:1::1/64\n ipv6 address 2001:db8:63::1/64"},
{title:"Duplicate manually configured IPv6 address causes neighbor-cache churn",rootCause:"Two lab servers use the same static IPv6 address 2001:db8:70::50.",change:"A VM was cloned without changing its static IPv6 configuration.",complaint:"Connections to the server randomly land on different machines or fail.",evidence:"DIST1# show ipv6 neighbors | include 2001:DB8:70::50\n2001:DB8:70::50 0 aaaa.bbbb.cc01 REACH Vlan700\n<later> 2001:DB8:70::50 0 aaaa.bbbb.cc02 STALE Vlan700",fix:"! Assign a unique IPv6 address to the cloned VM and clear stale neighbor entries if needed"},
{title:"IPv6 default route points to an unreachable global next hop",rootCause:"The static IPv6 default route references 2001:db8:ffff::1, but the WAN next hop is only reachable by link-local FE80::1 on Gi0/0.",change:"The provider changed the handoff addressing model.",complaint:"The router reaches local IPv6 networks but cannot reach the Internet over IPv6.",evidence:"R1# show ipv6 route ::/0\nS ::/0 [1/0] via 2001:DB8:FFFF::1\nR1# show ipv6 neighbors | include FE80\nFE80::1 ... REACH Gi0/0",fix:"no ipv6 route ::/0 2001:db8:ffff::1\nipv6 route ::/0 GigabitEthernet0/0 FE80::1"},
{title:"Link-local next hop was configured without an exit interface",rootCause:"An IPv6 static route uses only FE80::2 as next hop; IOS requires the outgoing interface with a link-local next hop.",change:"A route was added from an IPv4-style template.",complaint:"The static IPv6 route is rejected or unusable even though the peer is directly connected.",evidence:"R2# show running-config | include ipv6 route\nipv6 route 2001:db8:200::/64 FE80::2",fix:"no ipv6 route 2001:db8:200::/64 FE80::2\nipv6 route 2001:db8:200::/64 GigabitEthernet0/1 FE80::2"},
{title:"Client uses a /128 instead of /64 and cannot discover neighbors correctly",rootCause:"A statically configured endpoint has prefix length /128 instead of the VLAN /64.",change:"The address field was copied from a loopback configuration example.",complaint:"The endpoint has a valid-looking IPv6 address but cannot reach peers or the gateway normally.",evidence:"CLIENT: 2001:db8:80::25/128 gateway FE80::1\nExpected VLAN prefix: 2001:db8:80::/64",fix:"! Change client prefix length to /64 and re-establish neighbor discovery"},
{title:"IPv6 routing is disabled globally on a router with configured addresses",rootCause:"Interfaces have IPv6 addresses but `ipv6 unicast-routing` is missing.",change:"A replacement router restored interface configs but not the global feature.",complaint:"The router responds to its own interface addresses but does not route IPv6 between networks.",evidence:"R3# show run | include ipv6 unicast-routing\n<no output>\nR3# show ipv6 interface brief\nGi0/0 [up/up] 2001:DB8:30::1",fix:"ipv6 unicast-routing"},
{title:"IPv6 DNS works but AAAA record points to retired server",rootCause:"The application AAAA record still returns 2001:db8:90::25 after the service moved to ::40.",change:"Only the IPv4 A record was updated during application migration.",complaint:"Dual-stack clients prefer IPv6 and fail to open the application while IPv4-only clients work.",evidence:"CLIENT> nslookup app.example.local\nAAAA 2001:db8:90::25\nR1# ping 2001:db8:90::40\n!!!!!",fix:"! Update the authoritative AAAA record to 2001:db8:90::40 and expire stale caches"},
{title:"IPv6 RA advertises the wrong prefix after VLAN renumbering",rootCause:"The SVI still owns an old IPv6 /64, so hosts autoconfigure addresses from both old and new prefixes.",change:"The VLAN was renumbered but the old interface IPv6 address was left configured.",complaint:"Clients show multiple global addresses and choose paths that intermittently fail.",evidence:"DIST3# show ipv6 interface vlan 910\n2001:DB8:91::1/64\n2001:DB8:191::1/64\nND advertised prefixes include both",fix:"interface Vlan910\n no ipv6 address 2001:db8:91::1/64\n! Keep only the approved current prefix"},
{title:"IPv6 neighbor discovery fails because RA Guard is applied to the router-facing port",rootCause:"RA Guard blocks legitimate Router Advertisements on the uplink toward the authorized first-hop router.",change:"A user-edge security policy was mistakenly applied to all ports in the access switch.",complaint:"Hosts keep link-local addresses but never learn an IPv6 default router.",evidence:"ACC10# show ipv6 nd raguard policy\nPolicy EDGE-HOSTS applied to Gi1/0/48\nACC10# show logging | include RA_GUARD\nDropped IPv6 RA on Gi1/0/48",fix:"interface GigabitEthernet1/0/48\n no ipv6 nd raguard attach-policy EDGE-HOSTS\n! Keep RA Guard on true host-facing ports only"}
]),
...ccnaDomain("Switching, MAC learning and ARP", [
{title:"MAC address table points to the wrong port after a desk move",rootCause:"A small unmanaged switch creates a looped path and the endpoint MAC rapidly moves between two access interfaces.",change:"The user connected both wall jacks to the same unmanaged switch.",complaint:"The user's connectivity flaps and the switch logs repeated MAC movement.",evidence:"ACC1# show logging | include MACFLAP\n%SW_MATM-4-MACFLAP_NOTIF: Host 0011.2233.4455 in vlan 110 is flapping between port Gi1/0/12 and Gi1/0/13",fix:"! Remove the accidental Layer-2 loop/unmanaged dual connection\n! Verify the MAC stabilizes on one access port"},
{title:"Static MAC entry sends traffic to a retired server port",rootCause:"A static MAC table entry still maps the server MAC to Gi1/0/20 after the server moved to Gi1/0/30.",change:"The server rack was reorganized but the static switch entry was not updated.",complaint:"The server transmits traffic but other devices cannot reliably reach it.",evidence:"SW1# show mac address-table address 0050.56aa.bbcc\n 500 0050.56aa.bbcc STATIC Gi1/0/20",fix:"no mac address-table static 0050.56aa.bbcc vlan 500 interface GigabitEthernet1/0/20\n! Allow dynamic learning or add the correct approved static mapping"},
{title:"ARP cache still points to replaced firewall MAC",rootCause:"The gateway retains a stale ARP entry for a firewall IP after the firewall appliance was replaced.",change:"The firewall was swapped without clearing the upstream ARP cache or using gratuitous ARP.",complaint:"The new firewall is up, but traffic from the LAN still fails until ARP ages out.",evidence:"DIST1# show ip arp 10.50.0.254\nInternet 10.50.0.254 18 0011.1111.1111 ARPA Vlan500\nNew firewall MAC: 0022.2222.2222",fix:"clear ip arp 10.50.0.254\n! Confirm the new MAC is learned and traffic resumes"},
{title:"Switch reaches MAC table capacity because of a bridging loop",rootCause:"An unmanaged loop causes thousands of source MAC addresses to be learned/churned across the same access switch.",change:"Temporary event cabling connected two access ports together through an unmanaged switch.",complaint:"New devices intermittently flood traffic and the switch CPU rises.",evidence:"ACC2# show mac address-table count\nTotal Mac Address Space Available: 16384\nTotal Mac Addresses In Use: 16380\nACC2# show logging | include MACFLAP\n<rapid MAC flaps>",fix:"! Locate and remove the Layer-2 loop\n! Verify STP protections and MAC-table count return to normal"},
{title:"Unknown unicast flooding exposes a failed uplink learning path",rootCause:"The destination MAC is never learned because the downstream server-facing trunk is blocking the VLAN.",change:"A trunk allowed-VLAN list was edited during maintenance.",complaint:"Packet captures show repeated unknown-unicast flooding for one server MAC.",evidence:"DIST1# show mac address-table address 00aa.bbcc.dd01\n<no entry>\nDIST1# show interfaces trunk\nVLAN 510 not forwarding on Po12",fix:"! Restore VLAN 510 forwarding on the intended trunk and verify the server MAC is learned dynamically"},
{title:"ARP entry is incomplete because host is on wrong access VLAN",rootCause:"The router ARPs for a local host in VLAN 120, but the endpoint port is actually assigned to VLAN 130.",change:"A port was moved to a new jack and the access VLAN was not matched to the old location.",complaint:"The gateway cannot ping one local host while nearby hosts work.",evidence:"DIST1# show ip arp 10.120.0.55\nInternet 10.120.0.55 0 Incomplete ARPA Vlan120\nACC3# show interfaces gi1/0/22 switchport | include Access\nAccess Mode VLAN: 130",fix:"interface GigabitEthernet1/0/22\n switchport access vlan 120"},
{title:"MAC learning disabled by port-security sticky entry from old laptop",rootCause:"A sticky secure MAC from the previous laptop prevents the replacement laptop MAC from being accepted.",change:"A laptop was replaced without clearing the port's sticky secure address.",complaint:"The new laptop gets no network access even though the same jack worked for the old laptop.",evidence:"ACC4# show port-security interface gi1/0/16\nPort Status: Secure-shutdown\nLast Source Address:Violation: 00de.adbe.ef02\nConfigured secure MAC: 00de.adbe.ef01",fix:"interface GigabitEthernet1/0/16\n no switchport port-security mac-address sticky 00de.adbe.ef01\n shutdown\n no shutdown\n! Relearn only the authorized replacement endpoint"},
{title:"CAM lookup appears wrong because traffic is in a different VLAN",rootCause:"The engineer searched the MAC address table without the correct VLAN context and assumed the host was missing.",change:"The endpoint was intentionally moved from VLAN 20 to VLAN 220.",complaint:"Troubleshooting stalled because the host MAC is not found where the team expects it.",evidence:"SW1# show mac address-table vlan 20 | include 00aa.bbcc.2200\n<no output>\nSW1# show mac address-table vlan 220 | include 00aa.bbcc.2200\n220 00aa.bbcc.2200 DYNAMIC Gi1/0/8",fix:"! Use the actual VLAN/interface context and verify the endpoint's intended VLAN before making changes"},
{title:"ARP inspection drops packets because DHCP snooping binding is missing",rootCause:"Dynamic ARP Inspection is enabled, but the statically addressed printer has no DHCP snooping binding or ARP ACL entry.",change:"DAI was enabled on the VLAN during a security rollout.",complaint:"The static printer can send some traffic but ARP replies are dropped by the access switch.",evidence:"ACC5# show ip arp inspection statistics vlan 230\nForwarded 122 Dropped 148\nACC5# show ip dhcp snooping binding | include Gi1/0/28\n<no binding>",fix:"! Add an approved ARP ACL/static binding method for the legitimate static device or move it to a design that supports validation\n! Do not disable DAI globally"},
{title:"Proxy ARP masks an incorrect host subnet mask",rootCause:"Hosts with an overly broad subnet mask appear to work because the router answers ARP on behalf of remote destinations using proxy ARP.",change:"A DHCP option accidentally distributed /16 instead of /24.",complaint:"Users work inconsistently and troubleshooting shows clients ARPing for addresses that should be routed.",evidence:"PC capture: ARP Who has 10.30.50.20?\nGateway replies with its own MAC\nDIST1# show ip interface vlan 30 | include Proxy ARP\nProxy ARP is enabled",fix:"! Correct the DHCP subnet mask to /24 and renew clients\n! Do not use proxy ARP to hide incorrect host addressing"}
]),
...ccnaDomain("VLANs and access ports", [
{title:"Accounting PC placed in the voice VLAN",rootCause:"Gi1/0/18 uses access VLAN 210 (VOICE) instead of data VLAN 110 while the voice VLAN is also 210.",change:"A phone-and-PC desk was moved and a voice-only port template was pasted.",complaint:"The phone registers, but the attached PC receives a voice-subnet address and cannot reach accounting servers.",evidence:"ACC1# show interfaces gi1/0/18 switchport\nAccess Mode VLAN: 210 (VOICE)\nVoice VLAN: 210 (VOICE)",fix:"interface GigabitEthernet1/0/18\n switchport mode access\n switchport access vlan 110\n switchport voice vlan 210"},
{title:"New user VLAN was never created on the local access switch",rootCause:"VLAN 330 is referenced by access ports but does not exist in the local VLAN database.",change:"The distribution SVI was created, but one access switch was omitted from the VLAN rollout.",complaint:"Users on ACC3 remain offline while the same VLAN works from other closets.",evidence:"ACC3# show vlan id 330\n% VLAN 330 not found in current VLAN database\nACC3# show interfaces gi1/0/12 switchport | include Access\nAccess Mode VLAN: 330 (Inactive)",fix:"vlan 330\n name LAB-USERS"},
{title:"Access port left in dynamic auto instead of static access",rootCause:"A user-facing interface inherited dynamic trunking behavior and can negotiate unexpectedly with connected equipment.",change:"A lab switch configuration was copied onto a production user port.",complaint:"The endpoint works intermittently and the port mode does not match the access-port standard.",evidence:"ACC4# show interfaces gi1/0/25 switchport\nAdministrative Mode: dynamic auto\nOperational Mode: static access",fix:"interface GigabitEthernet1/0/25\n switchport mode access\n switchport access vlan 125"},
{title:"Phone works but PC fails because data access VLAN is missing",rootCause:"The interface has a voice VLAN configured but its access VLAN is still VLAN 1 instead of the user data VLAN.",change:"A phone was added to an existing unconfigured desk port.",complaint:"The Cisco phone registers, but the PC behind it gets an address from the wrong network.",evidence:"ACC5# show interfaces gi1/0/27 switchport\nAccess Mode VLAN: 1 (default)\nVoice VLAN: 220 (VOICE)",fix:"interface GigabitEthernet1/0/27\n switchport access vlan 120\n switchport voice vlan 220"},
{title:"Printer moved to guest VLAN by incorrect port template",rootCause:"Gi1/0/31 is assigned to VLAN 900 GUEST instead of VLAN 310 PRINTERS.",change:"A contractor used the nearest template name rather than the printer template.",complaint:"The printer receives an IP address but cannot reach the corporate print server.",evidence:"ACC6# show interfaces gi1/0/31 switchport | include Access\nAccess Mode VLAN: 900 (GUEST)\nExpected: VLAN 310 PRINTERS",fix:"interface GigabitEthernet1/0/31\n switchport access vlan 310"},
{title:"VLAN name suggests wrong purpose and causes provisioning mistake",rootCause:"VLAN 410 is correctly numbered for cameras but is mislabeled `CORP-USERS`, leading technicians to assign endpoints incorrectly.",change:"The VLAN was renamed during a documentation cleanup without checking actual use.",complaint:"New camera ports are being placed into the wrong VLAN because the switch label is misleading.",evidence:"ACC7# show vlan id 410\n410 CORP-USERS active Gi1/0/40,Gi1/0/41\nIPAM: VLAN 410 = CAMERAS",fix:"vlan 410\n name CAMERAS\n! Correct any ports provisioned based on the misleading label"},
{title:"User port placed in shutdown by an unused-port template",rootCause:"An active wall jack was accidentally included in an interface range used to disable unused ports.",change:"A security cleanup applied `shutdown` to Gi1/0/1-20, including occupied Gi1/0/18.",complaint:"One active user lost network access immediately after the unused-port hardening change.",evidence:"ACC8# show interfaces status | include Gi1/0/18\nGi1/0/18 Desk-218 disabled 999 auto auto",fix:"interface GigabitEthernet1/0/18\n description Desk-218\n switchport mode access\n switchport access vlan 118\n no shutdown"},
{title:"Access VLAN exists but SVI for the subnet is missing upstream",rootCause:"VLAN 515 is active on the access switch, but the multilayer distribution switch has no Vlan515 SVI/default gateway.",change:"The Layer-2 portion of a new department rollout was completed before the Layer-3 change.",complaint:"Clients communicate with each other locally but cannot reach any other subnet.",evidence:"ACC9# show vlan id 515\n515 DESIGN active Gi1/0/1-12\nDIST1# show ip interface brief | include Vlan515\n<no output>",fix:"interface Vlan515\n ip address 10.51.5.1 255.255.255.0\n no shutdown\n! Add routing/relay policy required by the approved design"},
{title:"Wrong voice VLAN ID advertised to phones",rootCause:"The port advertises voice VLAN 225 while DHCP and call-control services are built for VLAN 220.",change:"A typo was introduced while configuring a small range of desk ports.",complaint:"Phones on one row never register while PCs behind them work normally.",evidence:"ACC10# show interfaces gi1/0/20 switchport\nAccess Mode VLAN: 120\nVoice VLAN: 225\nExpected voice VLAN: 220",fix:"interface GigabitEthernet1/0/20\n switchport voice vlan 220"},
{title:"VLAN removed from database while access ports still reference it",rootCause:"VLAN 610 was deleted during cleanup even though active access ports are still assigned to it.",change:"An engineer believed VLAN 610 was unused based only on an outdated spreadsheet.",complaint:"A group of lab PCs simultaneously lost connectivity even though their switch ports remain physically up.",evidence:"ACC11# show interfaces gi1/0/5 switchport | include Access\nAccess Mode VLAN: 610 (Inactive)\nACC11# show vlan brief | include 610\n<no output>",fix:"vlan 610\n name LAB-DEVICES\n! Reconcile VLAN usage with source-of-truth before future deletions"}
])
];
