import { ccnaDomain, type CcnaCase } from "./ccna-ticket-types";

export const ccnaTicketCatalog4: CcnaCase[] = [
...ccnaDomain("Layer 2 security", [
{title:"Port security shuts down phone-plus-PC desk after second MAC appears",rootCause:"The access port allows only one secure MAC address even though a phone and attached PC legitimately use two MAC addresses.",change:"A single-endpoint port-security template was applied to a converged voice/data desk.",complaint:"The phone works until the PC connects, then the port becomes secure-shutdown.",evidence:"ACC1# show port-security interface gi1/0/21\nPort Status: Secure-shutdown\nMaximum MAC Addresses: 1\nSecurity Violation Count: 1",fix:"interface GigabitEthernet1/0/21\n switchport port-security maximum 2\n shutdown\n no shutdown"},
{title:"Sticky secure MAC from former employee blocks replacement laptop",rootCause:"The port retains a sticky secure MAC for the old laptop, so the new authorized laptop triggers a violation.",change:"The employee laptop was replaced but the sticky entry was not cleared.",complaint:"The new laptop cannot connect on the same desk jack that worked for the old laptop.",evidence:"ACC2# show port-security address interface gi1/0/10\nSecure Mac Address 00aa.bbcc.0011 Sticky\nViolation MAC 00aa.bbcc.0022",fix:"interface GigabitEthernet1/0/10\n no switchport port-security mac-address sticky 00aa.bbcc.0011\n shutdown\n no shutdown\n! Relearn only the approved endpoint"},
{title:"DHCP snooping trusts a user-facing port",rootCause:"A normal access port is configured as DHCP snooping trusted, allowing a rogue DHCP server connected by a user to send offers.",change:"The trust command was copied from the uplink interface template.",complaint:"Some clients receive the wrong gateway and DNS from an unauthorized DHCP server.",evidence:"ACC3# show ip dhcp snooping\nTrusted Interfaces:\nGi1/0/17 yes\nGi1/0/48 yes\nGi1/0/17 is a user desk port",fix:"interface GigabitEthernet1/0/17\n no ip dhcp snooping trust\n! Keep trust only on approved DHCP/uplink paths"},
{title:"DHCP snooping drops legitimate offers on the uplink",rootCause:"The uplink toward the authorized DHCP server is not trusted, so server Offer/Ack packets are dropped.",change:"DHCP snooping was enabled globally but trust was not configured on the upstream port.",complaint:"All new clients in protected VLANs fail to obtain leases.",evidence:"ACC4# show ip dhcp snooping\nGi1/0/48 Trusted: no\nDropped DHCP server packets increasing",fix:"interface GigabitEthernet1/0/48\n ip dhcp snooping trust"},
{title:"Dynamic ARP Inspection blocks static printer without binding",rootCause:"DAI validates ARP against DHCP snooping bindings, but the printer is statically addressed and has no approved ARP ACL/static validation entry.",change:"DAI was enabled on the printer VLAN.",complaint:"The printer link is up but ARP replies are dropped and users cannot print.",evidence:"ACC5# show ip arp inspection statistics vlan 310\nForwarded 45 Dropped 326\nACC5# show ip dhcp snooping binding | include Gi1/0/31\n<no entry>",fix:"! Add an approved ARP ACL/static validation for the legitimate static printer or use a supported binding method\n! Do not disable DAI globally"},
{title:"DAI trust is missing on inter-switch trunk",rootCause:"The trunk carrying legitimate ARP replies from upstream is untrusted for Dynamic ARP Inspection.",change:"Security configuration was applied to a replacement access switch but the uplink trust exception was missed.",complaint:"Multiple statically and dynamically addressed hosts lose gateway reachability at once.",evidence:"ACC6# show ip arp inspection interfaces\nGi1/0/48 Untrusted Rate 15\nDrops increase on uplink",fix:"interface GigabitEthernet1/0/48\n ip arp inspection trust"},
{title:"Storm control threshold is set too low and drops normal broadcast traffic",rootCause:"Broadcast storm-control is configured at an extremely low level, causing legitimate ARP/DHCP broadcasts to be discarded during busy periods.",change:"A percentage value was entered as a decimal using the wrong scale.",complaint:"Clients intermittently fail ARP and DHCP during morning login bursts.",evidence:"ACC7# show storm-control interface gi1/0/48\nBroadcast level 0.01%\nDrop counters increasing during normal traffic",fix:"interface GigabitEthernet1/0/48\n storm-control broadcast level <approved-threshold>\n! Validate against normal baseline traffic"},
{title:"Port security violation mode restrict silently drops new MAC",rootCause:"The port is in violation mode restrict and has reached its secure-MAC limit, so additional frames are dropped without shutting the interface.",change:"A small approved docking station changed the endpoint MAC behavior.",complaint:"The interface stays up, but the user's new dock has no network connectivity.",evidence:"ACC8# show port-security interface gi1/0/14\nPort Status: Secure-up\nViolation Mode: Restrict\nMaximum MAC Addresses: 1\nSecurity Violation Count: 84",fix:"! Confirm approved endpoint count, then adjust the maximum or secure address policy\ninterface GigabitEthernet1/0/14\n switchport port-security maximum 2"},
{title:"RA Guard is attached to router-facing port",rootCause:"IPv6 RA Guard intended for host-facing ports is also applied to the uplink, dropping legitimate Router Advertisements.",change:"A security template was applied to an interface range that included the uplink.",complaint:"IPv6 clients retain link-local addresses but no longer learn a default router.",evidence:"ACC9# show logging | include RA_GUARD\nDropped IPv6 Router Advertisement on Gi1/0/48\nGi1/0/48 is upstream router link",fix:"interface GigabitEthernet1/0/48\n no ipv6 nd raguard attach-policy EDGE-HOSTS\n! Keep RA Guard on true endpoint-facing ports"},
{title:"Unused switch ports are active in user VLAN",rootCause:"Several unused ports remain enabled in the production user VLAN instead of being shut and placed in an unused VLAN.",change:"A new switch was installed with default access-port settings.",complaint:"Security audit flags open wall jacks that provide corporate access without an approved endpoint.",evidence:"ACC10# show interfaces status | include notconnect\nGi1/0/35 notconnect 110 auto auto\nGi1/0/36 notconnect 110 auto auto",fix:"interface range GigabitEthernet1/0/35-36\n switchport mode access\n switchport access vlan 999\n shutdown"}
]),
...ccnaDomain("AAA, TACACS+, RADIUS and management authentication", [
{title:"TACACS+ server address is wrong after migration",rootCause:"The router still sends TACACS+ requests to 10.250.30.10 after the AAA service moved to 10.250.30.20.",change:"Identity services were migrated and one network device was missed.",complaint:"Administrators fall back to local login while other routers use centralized authentication normally.",evidence:"R1# show aaa servers\nTACACS: 10.250.30.10 State: DEAD\nCurrent TACACS server: 10.250.30.20",fix:"! Update the TACACS server definition to the approved current address and test with an active local fallback session"},
{title:"AAA method list has no local fallback during server outage",rootCause:"The login authentication method list references TACACS+ only and omits local fallback.",change:"A hardening change removed `local` from the method list.",complaint:"When TACACS+ becomes unreachable, all remote admin logins fail even with a valid local emergency account.",evidence:"R2# show run | include aaa authentication login\naaa authentication login default group tacacs+\nR2# show aaa servers\nTACACS server DEAD",fix:"aaa authentication login default group tacacs+ local\n! Test fallback safely before ending the maintenance session"},
{title:"RADIUS shared secret mismatch rejects wireless authentication",rootCause:"The network device and RADIUS server use different shared secrets.",change:"The server-side secret was rotated but the controller/device configuration was not updated.",complaint:"Users reach the SSID but 802.1X authentication fails for every account.",evidence:"WLC log: RADIUS request sent; Access-Reject / invalid authenticator\nRADIUS server: shared-secret mismatch event",fix:"! Update the network device and RADIUS server with the same approved secret using secure change handling"},
{title:"Device uses RADIUS for admin command authorization instead of expected TACACS+",rootCause:"The AAA configuration was changed to RADIUS for management authorization, but the environment relies on TACACS+ command authorization.",change:"A wireless AAA template was copied to a router.",complaint:"Admins authenticate but do not receive the expected command authorization behavior.",evidence:"R3# show run | section aaa\naaa authentication login default group radius local\naaa authorization exec default group radius local",fix:"! Restore the approved management AAA method list using the organization's TACACS+ group and local fallback"},
{title:"AAA server is reachable by ping but source address is not permitted",rootCause:"TACACS+ packets source from the WAN interface instead of the registered management loopback, so the server rejects the unknown client.",change:"A replacement router lost its AAA source-interface configuration.",complaint:"AAA tests fail even though the server IP responds to ping.",evidence:"R4# show aaa servers\nServer 10.250.30.20 State: DEAD\nServer logs: unknown client 10.1.4.2\nExpected client: 10.255.4.4",fix:"ip tacacs source-interface Loopback0\n! Verify server has the matching registered client address"},
{title:"VTY line ignores configured AAA method list",rootCause:"The custom AAA login method list exists but the VTY lines still use `login local` instead of `login authentication ADMIN`.",change:"AAA was staged but not attached to the VTY lines.",complaint:"Admins are still authenticated locally and centralized login accounting shows no sessions.",evidence:"R5# show run | include aaa authentication login ADMIN\naaa authentication login ADMIN group tacacs+ local\nR5# show run | section line vty\n login local",fix:"line vty 0 15\n login authentication ADMIN"},
{title:"Clock drift breaks certificate-based RADIUS authentication",rootCause:"The network device clock is far outside valid certificate time, causing secure RADIUS/802.1X validation to fail.",change:"NTP reachability was lost during a management-network change.",complaint:"Authentication starts failing on one device while credentials remain valid elsewhere.",evidence:"SW6# show clock\n*00:12:14.000 UTC Jan 1 2000\nSW6# show ntp status\nClock is unsynchronized",fix:"! Restore NTP reachability and synchronize time before changing credentials or certificates"},
{title:"Local emergency account password was rotated only in documentation",rootCause:"The password vault was updated but the local device account was never changed, so the documented fallback credential is invalid.",change:"Quarterly credential rotation was partially completed.",complaint:"During an AAA outage the team discovers the recorded local emergency password does not work.",evidence:"Console login with vaulted credential: authentication failed\nR7# show run | include username emergency\nusername emergency privilege 15 secret <existing-secret>",fix:"username emergency privilege 15 secret <approved-new-secret>\n! Verify access and update the controlled credential record"},
{title:"RADIUS server is configured but management route is missing",rootCause:"The switch has no route from its management VRF/subnet to the RADIUS server network.",change:"The management gateway changed during switch replacement.",complaint:"All centralized authentication requests time out from one switch only.",evidence:"SW8# ping 10.250.40.20\n.....\nSW8# show ip route 10.250.40.20\n% Network not in table",fix:"! Restore the approved management default/static route or gateway so the AAA server is reachable"},
{title:"AAA accounting server is reachable but accounting is not enabled",rootCause:"Authentication uses TACACS+ correctly, but no exec/command accounting statements are configured.",change:"A new router was built from a minimal AAA template.",complaint:"Security can see login success but has no centralized record of admin sessions/commands.",evidence:"R9# show run | section aaa\naaa authentication login default group tacacs+ local\n<no aaa accounting lines>",fix:"! Add the organization's approved TACACS+ accounting configuration and verify records are received"}
]),
...ccnaDomain("QoS basics, application transport and VPN concepts", [
{title:"Voice packets lose priority because switch does not trust phone markings",rootCause:"The access port resets DSCP/CoS instead of trusting the approved Cisco phone trust boundary, so voice traffic enters the network unmarked.",change:"A generic data-port QoS template replaced the voice-port template.",complaint:"Calls sound acceptable off-hours but break up when the WAN is congested.",evidence:"ACC1# show policy-map interface gi1/0/22\nVoice class matches 0 packets\nPacket capture from phone shows markings removed after access switch",fix:"! Restore the approved voice trust/classification policy on the phone-facing port\n! Verify DSCP EF is preserved only for authorized voice traffic"},
{title:"QoS policy is configured but applied in wrong direction",rootCause:"The WAN service-policy is attached inbound while congestion and queueing occur on outbound egress.",change:"The policy was added quickly during a voice-quality incident.",complaint:"QoS counters stay at zero and voice degrades during uploads.",evidence:"R1# show policy-map interface gi0/0\nService-policy input: WAN-QOS\nOutput policy: none",fix:"interface GigabitEthernet0/0\n no service-policy input WAN-QOS\n service-policy output WAN-QOS"},
{title:"WAN shaper is set above provider circuit rate",rootCause:"The router shapes at 100 Mbps on a 50-Mbps provider circuit, so congestion occurs in the carrier where local QoS queues cannot control it.",change:"The site upgraded router hardware but not the service-policy rate.",complaint:"Voice suffers under load even though the router's priority queue shows few local drops.",evidence:"R2# show policy-map interface gi0/0\nShape average 100000000\nProvider CIR: 50000000",fix:"! Set the parent shaper to the approved carrier CIR and verify child class behavior under load"},
{title:"Application uses UDP but firewall test checked only TCP port",rootCause:"The troubleshooting team validated TCP/5000 while the real application uses UDP/5000, so the wrong transport test produced a false conclusion.",change:"A vendor upgraded the application from TCP to UDP transport.",complaint:"Basic connectivity works, but the application times out even though a TCP test appears successful.",evidence:"Vendor spec: UDP/5000\nTest performed: TCP connect to port 5000 succeeds\nPacket capture: UDP/5000 unanswered",fix:"! Test and permit the actual UDP transport flow end-to-end according to policy\n! Document protocol plus port, not port number alone"},
{title:"DNS uses UDP normally but large response requires TCP and fails",rootCause:"A security policy allows UDP/53 but blocks TCP/53, so larger DNS responses that retry over TCP fail.",change:"A restrictive ACL was created with only the common UDP DNS rule.",complaint:"Most DNS lookups work but certain large responses consistently time out.",evidence:"Packet capture: UDP DNS response truncated (TC=1), client retries TCP/53, SYN times out",fix:"! Permit approved DNS server/client TCP/53 as well as UDP/53 according to policy"},
{title:"Site-to-site VPN issue is really missing route to protected network",rootCause:"The router has VPN configuration but no route for the remote protected subnet toward the VPN peer/tunnel path.",change:"A new subnet was added behind the remote site.",complaint:"Existing VPN networks work, but the new remote subnet is unreachable.",evidence:"R3# show ip route 10.77.20.0\n% Network not in table\nVPN peer itself reachable",fix:"! Add/learn the approved route for the new protected subnet and ensure VPN policy includes it\n! Do not recreate the entire tunnel before checking routing"},
{title:"Remote-access VPN users receive overlapping home and corporate subnet",rootCause:"The VPN address pool uses 192.168.1.0/24, which commonly overlaps users' home LANs, causing local-versus-VPN route conflicts.",change:"A temporary lab VPN pool was reused for production.",complaint:"Some users can connect to VPN but cannot reach corporate resources that share their home subnet.",evidence:"VPN client address: 192.168.1.50/24\nHome LAN: 192.168.1.0/24\nCorporate resource: 192.168.1.100",fix:"! Move the VPN client pool/corporate addressing to a non-overlapping approved range and update routes/policies"},
{title:"Voice VLAN has correct QoS markings but WAN interface is saturated",rootCause:"The WAN link is fully utilized and no effective outbound QoS policy reserves priority service for voice.",change:"A nightly backup job was moved into business hours.",complaint:"Calls become choppy only while large backups are running.",evidence:"R4# show interfaces gi0/0 | include output rate|drops\n5 minute output rate 49900000 bits/sec on 50 Mbps circuit\nOutput drops increasing\nshow policy-map interface: no service-policy",fix:"! Apply the approved outbound WAN QoS policy and reschedule/control bulk traffic as appropriate"},
{title:"TCP application fails because server listens on different port after upgrade",rootCause:"The application moved from TCP/8080 to TCP/8443 but monitoring and ACL checks still target the old port.",change:"The application was upgraded overnight.",complaint:"Users report the app is down while ping and general routing are normal.",evidence:"Server listening: tcp/8443\nNetwork ACL permits tcp/8080 only\nTCP/8080 test fails",fix:"! Update the approved ACL/monitoring/application URL to TCP/8443 after confirming the new service port"},
{title:"ICMP is blocked so PMTUD fails across VPN path",rootCause:"Required ICMP fragmentation-needed/Packet Too Big messages are filtered, so large packets stall across a lower-MTU VPN path.",change:"A broad ICMP deny was added during firewall hardening.",complaint:"Small pings and web pages work, but large uploads or certain HTTPS sessions hang.",evidence:"ping <remote> size 1400 df-bit fails\nping <remote> size 1200 df-bit succeeds\nICMP control messages not observed",fix:"! Permit the required ICMP messages for Path MTU Discovery according to security policy or adjust tunnel/MSS design appropriately"}
]),
...ccnaDomain("Automation, APIs, JSON and configuration management", [
{title:"REST API script uses GET when it intends to create a resource",rootCause:"The automation calls HTTP GET instead of POST for a create operation, so no configuration object is created.",change:"A script was adapted from a read-only inventory example.",complaint:"The script reports a successful HTTP response but no new network object appears.",evidence:"Request: GET /api/v1/sites\nResponse: 200 OK with existing site list\nExpected operation: create new site",fix:"! Use the API's documented POST endpoint/body for creation and verify the returned resource/task before continuing"},
{title:"Automation treats HTTP 401 as an empty result",rootCause:"The script catches an authentication failure and incorrectly interprets it as 'no devices found'.",change:"Error handling was simplified during a quick prototype.",complaint:"The automation claims the site has zero devices and attempts incorrect follow-up actions.",evidence:"API response: 401 Unauthorized\nScript log: devices=[]; proceeding with remediation",fix:"! Fail closed on authentication/retrieval errors; refresh credentials/token and only process data after a successful response"},
{title:"JSON parser expects `hostname` but API returns `hostName`",rootCause:"The script uses the wrong case-sensitive JSON key and therefore reads device names as undefined.",change:"The controller API version changed its schema field naming.",complaint:"Inventory export contains blank hostnames even though the API response includes them.",evidence:"API JSON: {\"hostName\":\"ACC1\",\"managementIpAddress\":\"10.1.1.10\"}\nScript reads item[\"hostname\"]",fix:"! Update the parser to the documented schema and validate required keys before generating output"},
{title:"REST token expired but script keeps retrying the same request",rootCause:"The API bearer token is expired and retry logic never performs reauthentication, causing repeated 401 responses.",change:"A long-running job exceeded the token lifetime.",complaint:"Automation works initially then stops midway through the device list.",evidence:"HTTP 401 Unauthorized\nToken expiration timestamp is earlier than current time\nRetry count increasing",fix:"! Reauthenticate/refresh the token according to API design, then resume idempotently from the last confirmed item"},
{title:"Script ignores API pagination and manages only first 100 devices",rootCause:"The program reads the first response page but never follows the returned next cursor/link.",change:"The environment grew beyond the API's default page size.",complaint:"Automation consistently updates the first group of devices but misses the rest.",evidence:"Response: count=100 total=247 next=/devices?offset=100\nScript processed 100 records and exited",fix:"! Follow pagination until the server indicates no remaining page, then validate processed count against total"},
{title:"Ansible inventory points to management addresses from old subnet",rootCause:"The inventory file still contains pre-migration switch management IP addresses.",change:"Management VLANs were renumbered but the automation inventory was not updated.",complaint:"Manual SSH works to the new addresses but Ansible reports every migrated switch unreachable.",evidence:"Inventory: ACC1 ansible_host=10.10.1.10\nCurrent ACC1 management: 10.20.1.10",fix:"! Update the authoritative inventory/source of truth and verify connectivity with a read-only play before changes"},
{title:"Terraform plan shows destructive replacement because resource identifier changed",rootCause:"A managed object's immutable identifier was edited, so Terraform proposes destroy/recreate instead of an in-place update.",change:"An engineer renamed an object directly in the configuration without reviewing the plan.",complaint:"The planned change would replace a production network object unexpectedly.",evidence:"terraform plan: 1 to add, 0 to change, 1 to destroy\nResource replacement forced by identifier change",fix:"! Stop before apply; reconcile state/identifier using the supported workflow and obtain change approval for any replacement"},
{title:"Python script pushes configuration to every device instead of canary subset",rootCause:"The target filter defaults to all devices when the site variable is empty.",change:"A command-line argument was omitted during a maintenance run.",complaint:"A small intended test is about to affect the entire campus device list.",evidence:"Script log: site='' matched 186 devices\nChange ticket scope: 2 lab switches",fix:"! Abort before write, require an explicit non-empty target scope, and add a confirmation/dry-run guard"},
{title:"API PUT overwrites fields the script did not intend to change",rootCause:"The automation uses full-object PUT with an incomplete payload, resetting unspecified settings to defaults.",change:"A PATCH-style assumption was applied to an endpoint that requires complete representation.",complaint:"Changing one interface description also resets unrelated interface properties.",evidence:"Request: PUT /interfaces/12 body contains only description\nAfter response: speed/duplex fields reverted to defaults",fix:"! Use the endpoint's documented PATCH method if supported or send a complete validated PUT representation after reading current state"},
{title:"Automation reports success before asynchronous controller task finishes",rootCause:"The script treats HTTP 202 Accepted as completed work and never polls the returned task ID.",change:"A synchronous lab API example was reused against an asynchronous production controller.",complaint:"The script says configuration succeeded while devices still show old settings and some tasks later fail.",evidence:"Response: 202 Accepted {\"taskId\":\"abc123\"}\nScript log: success; exiting\nController task abc123: FAILED",fix:"! Poll the task endpoint until terminal success/failure, surface task errors, then verify device state independently"}
]),
...ccnaDomain("Network architecture, controllers, VRFs and operational design", [
{title:"Collapsed-core switch failure removes both routing and access for building",rootCause:"A single multilayer switch provides the building's only distribution/core function with no redundant path or peer.",change:"A second planned distribution switch was deferred during budget reduction.",complaint:"One hardware failure disconnects every VLAN in the building from the rest of campus.",evidence:"Topology: all access switches dual-homed logically to one physical DIST1\nDIST1 offline = no alternate gateway/uplink",fix:"! Restore the failed device for immediate service, then remediate design with independent redundant distribution/gateway paths according to requirements"},
{title:"Management VRF has no default route after switch replacement",rootCause:"The switch's out-of-band management interface is in Mgmt-vrf but no route/default gateway exists inside that VRF.",change:"A replacement switch restored the management IP but not the VRF route.",complaint:"Production forwarding works, but SSH, NTP and monitoring from the management network fail.",evidence:"SW1# show ip route vrf Mgmt-vrf\nGateway of last resort is not set\nSW1# show ip interface brief vrf Mgmt-vrf\nGi0/0 10.250.1.20 up up",fix:"ip route vrf Mgmt-vrf 0.0.0.0 0.0.0.0 10.250.1.1"},
{title:"Traffic is tested in global table but service lives in a VRF",rootCause:"The engineer uses a normal ping/show route in the global routing table while the management destination exists only in Mgmt-vrf.",change:"Management was recently moved into a dedicated VRF.",complaint:"The team believes the monitoring server is unreachable even though the VRF path is healthy.",evidence:"SW2# show ip route 10.250.10.50\n% Network not in table\nSW2# show ip route vrf Mgmt-vrf 10.250.10.50\nS 10.250.10.0/24 via 10.250.1.1",fix:"! Test in the correct routing context\nping vrf Mgmt-vrf 10.250.10.50\nshow ip route vrf Mgmt-vrf"},
{title:"Controller shows device unreachable because management IP changed",rootCause:"The controller inventory still references the old device management address after VLAN renumbering.",change:"The switch management SVI moved from 10.10.1.20 to 10.20.1.20.",complaint:"The switch works locally, but controller-based assurance and automation show it offline.",evidence:"Controller inventory ACC1 management IP: 10.10.1.20\nACC1# show ip interface brief | include Vlan99\nVlan99 10.20.1.20 up up",fix:"! Update/re-discover the device using the approved controller workflow and verify credentials/reachability to the new management IP"},
{title:"Cloud-managed branch appliance is online but wrong site template is assigned",rootCause:"The device is enrolled successfully but attached to a template for another branch with different VLANs and addressing.",change:"Two new branch devices were swapped in the staging inventory.",complaint:"The appliance reaches the cloud controller but local users receive the wrong network configuration.",evidence:"Controller: device serial ABC123 assigned Site-West template\nPhysical location: Site-East\nExpected VLANs differ",fix:"! Assign the device to the correct approved site/template, review diff, and verify LAN/WAN settings before applying"},
{title:"Access switch uplinks share same upstream chassis and power domain",rootCause:"Two cables appear redundant but both terminate on the same distribution switch, creating a common failure domain.",change:"A second distribution switch was available but cabling followed the nearest patch-panel path.",complaint:"A distribution chassis reload takes down both supposedly redundant access uplinks.",evidence:"CDP neighbors: Gi1/0/47 -> DIST1, Gi1/0/48 -> DIST1\nDesign expected DIST1 and DIST2",fix:"! Rehome one uplink to the independent peer according to the campus design and validate STP/LACP/routing behavior"},
{title:"Server virtualization host trunk omits one VM VLAN",rootCause:"The switch trunk to a hypervisor permits VLANs 100-120 but new VM network VLAN 130 is not allowed.",change:"A new virtual network was created in the hypervisor before the physical switch trunk was updated.",complaint:"VMs in existing networks work but VMs attached to the new network have no connectivity.",evidence:"SW3# show interfaces trunk\nGi1/0/40 allowed: 100-120\nHypervisor vSwitch/port group: VLAN 130",fix:"interface GigabitEthernet1/0/40\n switchport trunk allowed vlan add 130"},
{title:"Containerized service is healthy internally but host route to service network is missing",rootCause:"The physical host/network has no route to the container service subnet exposed outside the host.",change:"A new container network was created with a previously unused prefix.",complaint:"The service works from the host itself but not from users on the campus.",evidence:"Host: service subnet 172.30.50.0/24 reachable locally\nGateway router: show ip route 172.30.50.0 -> not in table",fix:"! Add the approved routing advertisement/static route for the service subnet through the correct host/gateway design"},
{title:"Wireless controller management path works but AP VLAN is isolated by architecture",rootCause:"The controller is reachable from operations, but the AP management VLAN at a new site has no Layer-3 path to controller services.",change:"A new building was added with local VLANs but its routed uplink ACL/routing was incomplete.",complaint:"Admins can log into the controller, yet every AP in the new building remains offline.",evidence:"NOC -> WLC ping succeeds\nAP subnet -> WLC ping fails\nOther building AP subnets work",fix:"! Restore the approved routed/ACL path from the new AP management subnet to controller services and verify AP join"},
{title:"Redundant Internet links exist but default route uses only failed provider",rootCause:"The edge router has two physical ISP links but only one static default route, so the second link provides no automatic forwarding during failure.",change:"Backup ISP was installed physically but routing failover was never completed.",complaint:"The backup circuit is up, yet an outage on ISP1 still disconnects the branch from the Internet.",evidence:"EDGE# show ip interface brief\nGi0/0 ISP1 up/down\nGi0/1 ISP2 up/up\nEDGE# show ip route 0.0.0.0\nS* via ISP1 next-hop only",fix:"! Implement the approved backup routing method, such as a higher-distance floating static/default tracking design, and test failover in a change window"}
])
];
