import { ccnaDomain, type CcnaCase } from "./ccna-ticket-types";

export const ccnaTicketCatalog3: CcnaCase[] = [
...ccnaDomain("Single-area OSPFv2 troubleshooting", [
{title:"OSPF neighbors never form because interfaces are in different areas",rootCause:"R1 places the transit link in area 0 while R2 places the same link in area 10.",change:"R2 was rebuilt from a branch template that used the LAN's area number on the WAN interface.",complaint:"The routers can ping each other directly but no OSPF routes are exchanged.",evidence:"R1# show ip ospf interface gi0/0 | include Area\n  Area 0\nR2# show ip ospf interface gi0/0 | include Area\n  Area 10",fix:"interface GigabitEthernet0/0\n ip ospf 10 area 0"},
{title:"Passive OSPF interface stops Hello packets on the WAN",rootCause:"The branch WAN interface is configured as passive under OSPF after a passive-interface default rollout.",change:"The required `no passive-interface Gi0/0` exception was omitted.",complaint:"The WAN subnet is up, but the branch has no OSPF neighbor and no learned enterprise routes.",evidence:"BR1# show ip protocols | section Passive\nPassive Interface(s):\n GigabitEthernet0/0\nBR1# show ip ospf neighbor\n<empty>",fix:"router ospf 10\n no passive-interface GigabitEthernet0/0"},
{title:"OSPF router ID duplicated after config clone",rootCause:"Two branch routers use the same manually configured OSPF router ID 7.7.7.7.",change:"BR8 was deployed from BR7's saved configuration without changing the router ID.",complaint:"Routes from the two branches appear unstable and the core logs duplicate router ID messages.",evidence:"CORE# show logging | include OSPF|DUP\n%OSPF-4-DUP_RTRID_NBR: duplicate router-id 7.7.7.7\nBR8# show ip ospf | include ID\nRouting Process \"ospf 10\" with ID 7.7.7.7",fix:"router ospf 10\n router-id 8.8.8.8\nend\nclear ip ospf process"},
{title:"OSPF network statement does not match the new LAN",rootCause:"The new 10.44.20.0/24 interface is not matched by any OSPF network statement.",change:"A second branch VLAN was added but routing configuration was not updated.",complaint:"The branch router reaches the new VLAN locally, but headquarters has no route back to it.",evidence:"BR2# show ip route connected | include 10.44.20\nC 10.44.20.0/24 is directly connected, Vlan20\nBR2# show ip protocols | section Routing for Networks\n10.44.10.0 0.0.0.255 area 0",fix:"router ospf 10\n network 10.44.20.0 0.0.0.255 area 0"},
{title:"OSPF adjacency stays down because subnet masks differ",rootCause:"R3 uses /30 on the transit link while R4 uses /29, causing connected-network and OSPF parameter mismatch.",change:"One side was configured from an outdated circuit worksheet.",complaint:"The link is physically up but direct communication and OSPF neighbor formation are inconsistent.",evidence:"R3# show ip interface gi0/0 | include Internet\nInternet address is 10.1.34.1/30\nR4# show ip interface gi0/0 | include Internet\nInternet address is 10.1.34.2/29",fix:"! Correct the peer interface mask to the approved transit prefix on both ends\ninterface GigabitEthernet0/0\n ip address 10.1.34.2 255.255.255.252"},
{title:"Manual OSPF cost sends traffic over slower backup path",rootCause:"The primary interface has `ip ospf cost 500` while the backup path has cost 20.",change:"A temporary path-selection test was never rolled back.",complaint:"OSPF is healthy but application traffic uses the slower backup circuit.",evidence:"R5# show ip ospf interface gi0/0 | include Cost\nCost: 500\nR5# show ip ospf interface gi0/1 | include Cost\nCost: 20",fix:"interface GigabitEthernet0/0\n no ip ospf cost"},
{title:"Loopback network advertised with wrong wildcard mask",rootCause:"The OSPF network statement for Loopback0 uses a wildcard that matches a different subnet and excludes the loopback.",change:"A wildcard mask was copied from a /24 interface instead of the /32 loopback.",complaint:"The router forms neighbors but its management loopback is not reachable from the rest of the network.",evidence:"R6# show ip interface brief | include Loopback0\nLoopback0 10.255.6.6 YES manual up up\nR6# show ip protocols | section Routing for Networks\n10.255.6.0 0.0.0.3 area 0",fix:"router ospf 10\n network 10.255.6.6 0.0.0.0 area 0"},
{title:"OSPF interface was accidentally removed from the routing process",rootCause:"The transit interface no longer matches OSPF configuration after a network statement was deleted.",change:"An engineer cleaned duplicate-looking network statements and removed the one covering Gi0/1.",complaint:"The adjacency dropped immediately after the cleanup while the interface itself stayed up.",evidence:"R7# show ip ospf interface brief\nInterface PID Area IP Address/Mask Cost State Nbrs F/C\n<Gi0/1 absent>\nR7# show ip interface brief | include Gi0/1\nGi0/1 10.1.77.2 YES manual up up",fix:"interface GigabitEthernet0/1\n ip ospf 10 area 0"},
{title:"OSPF neighbor resets because Hello and Dead timers do not match",rootCause:"One router uses Hello/Dead 5/20 while the peer uses the default 10/40 on the Ethernet link.",change:"A lab timer tuning configuration was copied onto one production router.",complaint:"Both routers see each other at Layer 3 but never reach FULL adjacency.",evidence:"R8# show ip ospf interface gi0/0 | include Timer\nHello 5, Dead 20\nR9# show ip ospf interface gi0/0 | include Timer\nHello 10, Dead 40",fix:"interface GigabitEthernet0/0\n no ip ospf hello-interval\n no ip ospf dead-interval\n! Or configure matching approved values on both ends"},
{title:"OSPF default route is not advertised because no default exists locally",rootCause:"The edge router has `default-information originate` but no default route in its RIB, so OSPF does not inject one.",change:"The ISP static default route was removed during WAN maintenance.",complaint:"Internal routers still learn enterprise prefixes but no longer have a default route toward the Internet edge.",evidence:"EDGE# show run | section router ospf\n default-information originate\nEDGE# show ip route 0.0.0.0\n% Network not in table",fix:"! Restore the approved local default route to the ISP, then verify OSPF default injection\nip route 0.0.0.0 0.0.0.0 <ISP-next-hop>"}
]),
...ccnaDomain("DHCP, DHCP relay and DNS", [
{title:"New user VLAN is missing a DHCP helper address",rootCause:"The SVI for VLAN 125 has no `ip helper-address`, so client broadcasts never reach the centralized DHCP server.",change:"A contractor VLAN was created quickly and the relay line was omitted.",complaint:"Clients self-assign 169.254/16 addresses while a statically addressed test laptop can reach the gateway.",evidence:"DIST1# show run interface vlan 125\ninterface Vlan125\n ip address 10.125.0.1 255.255.255.0\n no shutdown\nDIST1# show run interface vlan 120 | include helper\n ip helper-address 10.10.50.20",fix:"interface Vlan125\n ip helper-address 10.10.50.20"},
{title:"DHCP pool is exhausted after a training event",rootCause:"Every address in the /24 scope is leased because hundreds of temporary devices received long lease durations.",change:"Lease time was increased to seven days just before a large training event.",complaint:"Existing users stay online but new clients cannot obtain IPv4 addresses.",evidence:"R1# show ip dhcp pool USERS130\nTotal addresses: 254\nLeased addresses: 254\nExcluded addresses: 0",fix:"ip dhcp pool USERS130\n lease 0 8 0\n! Expand the approved scope only after address-plan review"},
{title:"DHCP relay still points to retired server",rootCause:"The SVI forwards DHCP to 10.10.50.15 even though the active server moved to 10.10.50.20.",change:"DHCP service migrated and one branch SVI was missed.",complaint:"One VLAN fails DHCP while other VLANs at the site obtain leases normally.",evidence:"BR2# show run interface vlan 160 | include helper\n ip helper-address 10.10.50.15\nBR2# ping 10.10.50.15 source vlan 160\n.....",fix:"interface Vlan160\n no ip helper-address 10.10.50.15\n ip helper-address 10.10.50.20"},
{title:"Default gateway option in DHCP scope is wrong",rootCause:"The DHCP pool hands out default-router 10.170.0.254 but the SVI gateway is 10.170.0.1.",change:"The scope was copied from another site that uses .254 gateways.",complaint:"Clients receive valid IP addresses but cannot reach anything off-subnet.",evidence:"BR3# show run | section ip dhcp pool USERS170\ndefault-router 10.170.0.254\nBR3# show ip interface brief | include Vlan170\nVlan170 10.170.0.1 YES manual up up",fix:"ip dhcp pool USERS170\n no default-router 10.170.0.254\n default-router 10.170.0.1"},
{title:"DHCP scope mask is /25 while gateway and design are /24",rootCause:"The DHCP pool advertises a 255.255.255.128 mask for a /24 client VLAN.",change:"A subnet expansion was completed on the SVI but not in DHCP.",complaint:"Some clients treat upper-half addresses as remote and experience inconsistent local connectivity.",evidence:"R4# show run | section ip dhcp pool USERS180\nnetwork 10.180.0.0 255.255.255.128\nDIST# show run interface vlan 180\nip address 10.180.0.1 255.255.255.0",fix:"ip dhcp pool USERS180\n network 10.180.0.0 255.255.255.0"},
{title:"DNS server option still lists decommissioned resolver",rootCause:"DHCP option 6 gives clients 10.10.60.11, which is no longer a DNS server.",change:"Internal DNS servers were replaced but the branch DHCP pool was not updated.",complaint:"Users can ping IP addresses but cannot open internal sites by name or browse normally.",evidence:"BR5# show run | section ip dhcp pool USERS190\n dns-server 10.10.60.11\nCurrent resolvers: 10.10.60.20 10.10.60.21",fix:"ip dhcp pool USERS190\n no dns-server 10.10.60.11\n dns-server 10.10.60.20 10.10.60.21"},
{title:"Internal A record still points to old application server",rootCause:"The DNS A record for payroll.corp.local resolves to 10.80.20.25 after the app moved to 10.80.30.40.",change:"The server migration completed but DNS was not part of the cutover checklist.",complaint:"Users can reach the new server by IP but the normal application name fails.",evidence:"CLIENT> nslookup payroll.corp.local\nAddress: 10.80.20.25\nCORE# ping 10.80.30.40\n!!!!!",fix:"! Update payroll.corp.local A record to 10.80.30.40 and expire/clear stale caches"},
{title:"CNAME points to hostname that no longer has an A record",rootCause:"The alias portal.corp.local points to web-old.corp.local, whose A record was removed.",change:"The old web server record was deleted before the CNAME alias was changed.",complaint:"Users get DNS errors for the portal while the replacement web server works by direct name.",evidence:"CLIENT> nslookup portal.corp.local\ncanonical name = web-old.corp.local\n*** server can't find web-old.corp.local: NXDOMAIN",fix:"! Update the CNAME to the current canonical hostname or restore the required A record according to DNS design"},
{title:"DHCP exclusion was removed and server leases the gateway address",rootCause:"10.200.0.1 is no longer excluded from the IOS DHCP pool and was leased to a client, conflicting with the SVI.",change:"The DHCP pool was rebuilt and exclusion statements were missed.",complaint:"Default-gateway connectivity flaps when the conflicting client is online.",evidence:"R6# show ip dhcp binding | include 10.200.0.1\n10.200.0.1 0100.5056.baaa.bb Automatic\nR6# show ip interface brief | include Vlan200\nVlan200 10.200.0.1 YES manual up up",fix:"ip dhcp excluded-address 10.200.0.1 10.200.0.20\nclear ip dhcp binding 10.200.0.1"},
{title:"PTR record is stale after server IP change",rootCause:"Reverse DNS still maps 10.90.50.40 to the old server name, causing applications that validate PTR records to reject sessions.",change:"The server IP and forward A record were updated, but reverse DNS was not.",complaint:"Basic connectivity works but one security-sensitive application reports hostname validation failures.",evidence:"CLIENT> nslookup 10.90.50.40\nName: old-app.corp.local\nForward lookup new-app.corp.local = 10.90.50.40",fix:"! Update the authoritative PTR record for 10.90.50.40 to the current approved hostname"}
]),
...ccnaDomain("NAT and PAT", [
{title:"PAT ACL does not include newly added branch subnet",rootCause:"The NAT source ACL permits 10.10.0.0/16 but omits new subnet 10.55.0.0/16.",change:"The branch was routed successfully but the Internet-edge NAT policy was not updated.",complaint:"Branch users reach private WAN resources but cannot reach the Internet.",evidence:"EDGE1# show access-lists NAT-SOURCES\n10 permit 10.10.0.0 0.0.255.255\nEDGE1# show ip nat translations | include 10.55\n<no output>",fix:"ip access-list standard NAT-SOURCES\n 20 permit 10.55.0.0 0.0.255.255"},
{title:"NAT inside and outside roles are reversed",rootCause:"The LAN interface is marked `ip nat outside` while the ISP interface is marked `ip nat inside`.",change:"Interface numbers changed during router replacement but NAT role lines stayed with the old numbering.",complaint:"Clients reach the router but no Internet translations are created.",evidence:"BR1# show ip nat statistics\nInside interfaces: GigabitEthernet0/1\nOutside interfaces: GigabitEthernet0/0\nExpected opposite roles",fix:"interface GigabitEthernet0/0\n no ip nat outside\n ip nat inside\ninterface GigabitEthernet0/1\n no ip nat inside\n ip nat outside"},
{title:"NAT overload statement points to wrong outside interface",rootCause:"PAT translates to Gi0/2 even though Internet traffic exits Gi0/1.",change:"The WAN interface changed during circuit migration.",complaint:"Users have a valid default route but NAT translations do not appear on the live ISP path.",evidence:"EDGE2# show run | include ip nat inside source\nip nat inside source list NAT-SOURCES interface GigabitEthernet0/2 overload\nEDGE2# show ip route 0.0.0.0\nS* via 198.51.100.1, GigabitEthernet0/1",fix:"no ip nat inside source list NAT-SOURCES interface GigabitEthernet0/2 overload\nip nat inside source list NAT-SOURCES interface GigabitEthernet0/1 overload"},
{title:"Static NAT publishes web server to old inside address",rootCause:"The static translation maps the public IP to 10.20.30.25 after the web server moved to 10.20.30.40.",change:"The server was rebuilt with a new internal address.",complaint:"Internal users reach the new server but external users hit a dead translation.",evidence:"EDGE3# show ip nat translations | include 203.0.113.25\nPro Inside global 203.0.113.25 Inside local 10.20.30.25\nCurrent server 10.20.30.40",fix:"no ip nat inside source static 10.20.30.25 203.0.113.25\nip nat inside source static 10.20.30.40 203.0.113.25"},
{title:"Dynamic NAT pool is exhausted",rootCause:"The configured public NAT pool contains only five addresses and all are in use during peak hours.",change:"A new department started using a translation pool originally sized for a small lab.",complaint:"Some users get Internet access while later sessions fail until existing translations age out.",evidence:"EDGE4# show ip nat statistics\nPool PUBLIC-POOL: netmask 255.255.255.248\nAllocated: 5 (100%)\nMisses increasing",fix:"! Expand the approved public pool or convert the use case to PAT/overload if design allows\n! Do not clear all translations during production without impact review"},
{title:"NAT ACL is written backward and matches no inside clients",rootCause:"The standard ACL used for NAT matches the public destination range instead of the private inside source network.",change:"An engineer confused firewall matching with NAT source classification.",complaint:"Routing is correct but the NAT translation table remains empty.",evidence:"EDGE5# show access-lists 10\n10 permit 8.8.8.0 0.0.0.255 (0 matches)\nInside clients: 10.25.0.0/16",fix:"no access-list 10\naccess-list 10 permit 10.25.0.0 0.0.255.255"},
{title:"New server subnet lacks `ip nat inside` on its SVI",rootCause:"The new server VLAN is routed but its Layer-3 interface is not marked as NAT inside.",change:"A new server SVI was added after the NAT configuration was created.",complaint:"Older internal subnets reach the Internet, but servers in the new VLAN cannot create translations.",evidence:"EDGE6# show ip nat statistics\nInside interfaces: Vlan100,Vlan110\nNew subnet on Vlan120 absent",fix:"interface Vlan120\n ip nat inside"},
{title:"Outside interface lost `ip nat outside` after defaulting port",rootCause:"The Internet interface was reset and re-addressed, but the NAT outside role was not restored.",change:"The ISP handoff port was defaulted during troubleshooting.",complaint:"All internal users lose Internet access even though the default route and public interface address are correct.",evidence:"EDGE7# show ip nat statistics\nOutside interfaces:\n <none>\nEDGE7# show ip interface brief | include Gi0/1\nGi0/1 203.0.113.2 up up",fix:"interface GigabitEthernet0/1\n ip nat outside"},
{title:"Port-forward static PAT uses wrong TCP port",rootCause:"The public translation maps TCP 8443 to inside port 8443, but the application listens on inside TCP 443.",change:"A new secure web service was published using an incorrect example.",complaint:"External clients reach the router but the application never responds on the published port.",evidence:"EDGE8# show run | include ip nat inside source static tcp\nip nat inside source static tcp 10.30.0.50 8443 203.0.113.50 8443\nServer listens on tcp/443",fix:"no ip nat inside source static tcp 10.30.0.50 8443 203.0.113.50 8443\nip nat inside source static tcp 10.30.0.50 443 203.0.113.50 8443"},
{title:"Stale NAT translations persist after server address change",rootCause:"Existing long-lived translations still reference the old inside-local address after a planned server move.",change:"A static/dynamic translation rule was updated while sessions were active.",complaint:"New connections work but some existing users continue hitting the retired server path.",evidence:"EDGE9# show ip nat translations | include 10.40.0.25\n<old active translations remain>\nNew server: 10.40.0.40",fix:"! Remove only the affected stale translations during an approved window and verify new sessions use the new mapping\nclear ip nat translation <specific-entry>"}
]),
...ccnaDomain("IPv4 access control lists", [
{title:"ACL is applied outbound instead of inbound on user SVI",rootCause:"The user restriction ACL is attached outbound on Vlan310, so it filters return traffic instead of traffic entering from users.",change:"The engineer interpreted direction from the user's perspective instead of the interface perspective.",complaint:"The intended web restriction does not work and unrelated return traffic is affected.",evidence:"DIST1# show ip interface vlan 310 | include access list\nOutgoing access list is USER-WEB\nInbound access list is not set",fix:"interface Vlan310\n no ip access-group USER-WEB out\n ip access-group USER-WEB in"},
{title:"Broad deny appears before specific application permit",rootCause:"A deny for 10.42.0.0/16 to 10.90.0.0/16 is sequenced before the HTTPS permit to the inventory server.",change:"A security deny was inserted without reviewing ACL order.",complaint:"The inventory application is unreachable from warehouse users while DNS and routing remain healthy.",evidence:"DIST2# show access-lists WH-TO-DC\n10 permit udp 10.42.0.0 0.0.255.255 host 10.10.60.20 eq domain\n20 deny ip 10.42.0.0 0.0.255.255 10.90.0.0 0.0.255.255 (482 matches)\n30 permit tcp 10.42.0.0 0.0.255.255 host 10.90.15.25 eq 443 (0 matches)",fix:"ip access-list extended WH-TO-DC\n 15 permit tcp 10.42.0.0 0.0.255.255 host 10.90.15.25 eq 443\n no 30"},
{title:"Implicit deny blocks traffic after last permit was removed",rootCause:"The final broad permit was deleted, leaving required traffic to hit the ACL's implicit deny.",change:"An engineer removed `permit ip any any` while planning to add specific rules later.",complaint:"Multiple previously working applications fail immediately after an ACL cleanup.",evidence:"R1# show access-lists BRANCH-IN\n10 permit udp any host 10.10.60.20 eq domain\n20 permit tcp any host 10.90.10.10 eq 443\n<no rule for other approved traffic>",fix:"! Add the specifically approved permits required by policy before relying on the implicit deny\nip access-list extended BRANCH-IN\n <approved-sequence> permit <approved-flow>"},
{title:"Wildcard mask is written as subnet mask",rootCause:"The ACL uses 255.255.255.0 as a wildcard for a /24 network instead of 0.0.0.255, matching unintended addresses.",change:"A subnet mask was pasted into a wildcard-mask field.",complaint:"The ACL blocks/permits a much broader set of sources than intended.",evidence:"R2# show access-lists 25\n10 permit 10.20.30.0 255.255.255.0",fix:"no access-list 25\naccess-list 25 permit 10.20.30.0 0.0.0.255"},
{title:"Standard ACL is placed too close to the source",rootCause:"A standard ACL matching only source addresses is applied near the user VLAN, unintentionally blocking that source from all destinations instead of one server network.",change:"The ACL was attached to the nearest convenient interface.",complaint:"Users lose access to several unrelated services when only one destination was supposed to be restricted.",evidence:"DIST3# show ip interface vlan 220 | include access list\nInbound access list is BLOCK-220\nStandard ACL BLOCK-220 denies 10.22.0.0/16",fix:"! Move the standard ACL closer to the intended destination or use a properly scoped extended ACL\ninterface Vlan220\n no ip access-group BLOCK-220 in"},
{title:"Extended ACL uses wrong TCP direction for SSH",rootCause:"The rule permits source port 22 instead of destination port 22, so normal client-to-server SSH sessions are not matched.",change:"The ACL was written without considering which endpoint initiates the TCP session.",complaint:"Admins cannot SSH to the router from the management subnet though ping works.",evidence:"R3# show access-lists MGMT-IN\n10 permit tcp 10.250.0.0 0.0.0.255 eq 22 host 10.255.3.3\nHit count 0",fix:"ip access-list extended MGMT-IN\n no 10\n 10 permit tcp 10.250.0.0 0.0.0.255 host 10.255.3.3 eq 22"},
{title:"ACL applied to wrong interface filters unrelated branch traffic",rootCause:"A server ACL intended for Vlan500 is applied inbound on the branch WAN Gi0/0.",change:"The interface command was entered while still under the WAN interface context.",complaint:"Several branch applications fail even though the server VLAN policy itself looks correct.",evidence:"BR4# show ip interface gi0/0 | include access list\nInbound access list is SERVER-FILTER\nBR4# show ip interface vlan 500 | include access list\nInbound access list is not set",fix:"interface GigabitEthernet0/0\n no ip access-group SERVER-FILTER in\ninterface Vlan500\n ip access-group SERVER-FILTER in"},
{title:"ACL blocks DHCP replies because UDP ports are reversed",rootCause:"The ACL permits UDP 67-to-68 in the wrong direction and denies the actual relay/server return flow.",change:"A restrictive SVI ACL was added without testing DHCP renewal.",complaint:"Existing clients continue temporarily but new devices cannot obtain addresses.",evidence:"DIST4# show access-lists USERS-IN\npermit udp any eq bootps any eq bootpc\n<client relay flow counters do not increment>",fix:"! Add the correctly directed DHCP client/relay/server permits required by the topology and verify lease renewal\n! Keep the rule narrowly scoped to approved DHCP servers"},
{title:"Management ACL forgot the new jump host subnet",rootCause:"VTY access-class permits only the old admin subnet and omits the new jump-host network.",change:"Administration moved to a new secured management subnet.",complaint:"The router is reachable by ping but SSH connections from the new jump host are refused.",evidence:"R5# show run | section line vty\n access-class MGMT-SOURCES in\nR5# show access-lists MGMT-SOURCES\n10 permit 10.250.10.0 0.0.0.255\nNew jump subnet: 10.250.20.0/24",fix:"ip access-list standard MGMT-SOURCES\n 20 permit 10.250.20.0 0.0.0.255"},
{title:"ACL hit counters prove the network is blocking the application",rootCause:"A newly added deny entry explicitly matches the failed TCP/1521 database sessions.",change:"A segmentation change added a broad deny between user and database networks.",complaint:"Only the database application fails; web and DNS services remain available.",evidence:"DIST5# show access-lists USER-DB\n20 deny tcp 10.30.0.0 0.0.255.255 10.90.40.0 0.0.0.255 eq 1521 (1284 matches)\n30 permit ip any any",fix:"! Insert the approved narrow database permit before the deny if business/security policy authorizes it\nip access-list extended USER-DB\n 15 permit tcp <approved-source> <approved-destination> eq 1521"}
]),
...ccnaDomain("Device management, SSH, NTP, syslog and SNMP", [
{title:"SSH fails because RSA keys were never generated",rootCause:"The router has local usernames and SSH transport configured but no RSA key pair, so the SSH server cannot start.",change:"A new router was hardened manually and the key-generation step was skipped.",complaint:"Telnet is disabled as intended, but administrators cannot connect by SSH.",evidence:"R1# show ip ssh\nSSH Disabled - version 1.99\n% Please create RSA keys to enable SSH",fix:"ip domain-name corp.local\ncrypto key generate rsa modulus 2048\nip ssh version 2"},
{title:"VTY lines still allow Telnet instead of SSH only",rootCause:"The VTY transport input is `telnet ssh`, violating the secure-management standard.",change:"A legacy device configuration was copied to a new switch.",complaint:"Security audit discovers plaintext Telnet is still accepted on the management interface.",evidence:"SW1# show run | section line vty\nline vty 0 4\n transport input telnet ssh",fix:"line vty 0 15\n transport input ssh"},
{title:"NTP remains unsynchronized because source interface is wrong",rootCause:"NTP packets source from the WAN interface, but the server ACL permits only the management loopback address.",change:"A router replacement lost the `ntp source Loopback0` command.",complaint:"Device logs show the wrong time and no longer line up with other infrastructure.",evidence:"R2# show ntp status\nClock is unsynchronized, stratum 16\nR2# show ntp associations\n10.10.90.10 reach 0",fix:"ntp source Loopback0\nntp server 10.10.90.10 prefer"},
{title:"Syslog server is configured with old IP address",rootCause:"The device still sends logging to retired collector 10.250.10.40 instead of new collector 10.250.10.50.",change:"The SIEM/syslog platform was migrated last week.",complaint:"Local logs exist but the central collector shows no events from this switch.",evidence:"SW2# show logging | include Logging to\nLogging to 10.250.10.40 (udp port 514)\nCurrent collector: 10.250.10.50",fix:"no logging host 10.250.10.40\nlogging host 10.250.10.50"},
{title:"SNMP polling fails because source ACL omits new monitoring server",rootCause:"The SNMP source ACL permits the old NMS but not the new collector address.",change:"Monitoring was migrated to a new server.",complaint:"The switch is reachable by ping and SSH but shows as SNMP-down in monitoring.",evidence:"SW3# show access-lists NMS-SOURCES\n10 permit 10.250.20.10\nNew NMS: 10.250.20.25",fix:"ip access-list standard NMS-SOURCES\n 20 permit 10.250.20.25"},
{title:"Local username privilege is too low for expected admin tasks",rootCause:"The local backup administrator account is privilege 1 instead of privilege 15.",change:"The account was recreated after password rotation without its privilege level.",complaint:"An admin can log in during AAA outage but cannot enter required configuration commands.",evidence:"R3# show run | include username backupadmin\nusername backupadmin privilege 1 secret <hidden>",fix:"username backupadmin privilege 15 secret <new-approved-secret>\n! Follow organization policy for emergency local accounts"},
{title:"Console works but SSH fails because VTY uses `login` without password",rootCause:"VTY lines use line-password authentication but no VTY password is configured; local user authentication was intended.",change:"`login local` was accidentally replaced with `login`.",complaint:"Admins reach the router over the network but the SSH session immediately rejects authentication.",evidence:"R4# show run | section line vty\nline vty 0 4\n login\n transport input ssh\n<no password line>",fix:"line vty 0 15\n login local\n transport input ssh"},
{title:"NTP server is reachable but wrong timezone makes local timestamps confusing",rootCause:"The clock is synchronized to UTC correctly, but the device timezone is configured to the wrong local offset.",change:"A switch was shipped from another region and retained its timezone setting.",complaint:"Event order is accurate relative to NTP, but displayed local times are several hours off from helpdesk records.",evidence:"SW4# show clock detail\n08:15:22 PST Sat Sep 6 2026\nNTP synchronized\nSite timezone expected: Central",fix:"clock timezone CST -6 0\nclock summer-time CDT recurring\n! Use the organization's approved timezone/DST policy"},
{title:"Syslog severity threshold hides interface-down events",rootCause:"Remote logging is set to emergencies only, so normal link and configuration events never reach the collector.",change:"Logging level was tightened during troubleshooting and not restored.",complaint:"The SIEM receives only critical events and misses routine interface outages.",evidence:"SW5# show logging | include Trap logging\nTrap logging: level emergencies, 12 message lines logged",fix:"logging trap warnings\n! Set the approved severity level required by operations policy"},
{title:"SSH management fails because domain name was removed and keys were regenerated incorrectly",rootCause:"The device lost its domain name, and an attempted key regeneration left SSH disabled.",change:"A configuration cleanup removed `ip domain-name` before certificate/key work.",complaint:"The device is reachable by console and ping but no longer accepts SSH management.",evidence:"R5# show ip ssh\nSSH Disabled\nR5# show run | include ip domain-name\n<no output>",fix:"ip domain-name corp.local\ncrypto key generate rsa modulus 2048\nip ssh version 2\nline vty 0 15\n transport input ssh\n login local"}
])
];
