import { ccnaDomain, type CcnaCase } from "./ccna-ticket-types";

export const ccnaTicketCatalog2: CcnaCase[] = [
...ccnaDomain("802.1Q trunks, DTP and native VLANs", [
{title:"Production VLAN is missing from one trunk allowed list",rootCause:"VLAN 145 is not permitted on the access-switch uplink even though it is allowed on the distribution side.",change:"A cleanup change replaced the allowed list instead of adding and removing individual VLANs.",complaint:"Users in VLAN 145 work locally but cannot reach their default gateway upstream.",evidence:"ACC2# show interfaces trunk\nPort Gi1/0/48 Vlans allowed on trunk: 10,20,30,140,150\nDIST1# show interfaces trunk\nPort Gi1/0/3 Vlans allowed on trunk: 10,20,30,140-150",fix:"interface GigabitEthernet1/0/48\n switchport trunk allowed vlan add 145"},
{title:"Native VLAN mismatch appears after access switch replacement",rootCause:"The replacement access switch uses native VLAN 999 while the peer distribution trunk still uses native VLAN 1.",change:"Only one end received the hardened trunk template.",complaint:"Management traffic is inconsistent and CDP reports a native VLAN mismatch.",evidence:"%CDP-4-NATIVE_VLAN_MISMATCH: Native VLAN mismatch discovered on Gi1/0/48 (999), with DIST2 Gi1/0/8 (1)",fix:"interface GigabitEthernet1/0/8\n switchport trunk native vlan 999"},
{title:"Both ends use DTP dynamic auto so the uplink never becomes a trunk",rootCause:"Neither switch initiates DTP trunk negotiation because both interfaces are configured `dynamic auto`.",change:"Two access switches were restored from an old template that relies on negotiation.",complaint:"Only VLAN 1 crosses the link while all tagged VLANs fail.",evidence:"ACC6# show interfaces gi1/0/48 switchport\nAdministrative Mode: dynamic auto\nOperational Mode: static access",fix:"interface GigabitEthernet1/0/48\n switchport mode trunk\n switchport trunk native vlan 999"},
{title:"One trunk end is manually configured as an access port",rootCause:"The access-switch uplink is `switchport mode access` while the distribution peer is configured as a trunk.",change:"An interface was reset to defaults and rebuilt from the wrong template.",complaint:"The physical link is up but no production VLANs pass correctly between switches.",evidence:"ACC7# show interfaces gi1/0/48 switchport\nAdministrative Mode: static access\nOperational Mode: static access\nDIST1# show interfaces gi1/0/7 switchport\nAdministrative Mode: trunk",fix:"interface GigabitEthernet1/0/48\n switchport mode trunk\n switchport trunk allowed vlan 110,120,130,999\n switchport trunk native vlan 999"},
{title:"Trunk uses the wrong native VLAN for management traffic",rootCause:"The management VLAN is sent untagged as native VLAN 20 on one legacy link but the far end expects native VLAN 999.",change:"A legacy switch was connected to the standardized campus without normalizing trunk settings.",complaint:"The legacy switch's management address is unreachable even though user VLANs mostly work.",evidence:"LEGACY# show interfaces trunk\nNative vlan: 20\nDIST# show interfaces trunk\nNative vlan: 999",fix:"! Align the native VLAN on both ends according to the approved design\ninterface GigabitEthernet1/0/48\n switchport trunk native vlan 999"},
{title:"Voice VLAN is filtered from an uplink trunk",rootCause:"The uplink permits data VLANs but excludes voice VLAN 220.",change:"A new data VLAN was added using a replacement trunk list that omitted voice.",complaint:"PCs work across the closet, but phones lose DHCP and call-control connectivity.",evidence:"ACC8# show interfaces trunk\nGi1/0/48 allowed: 110,120,130,999\nExpected includes 220 VOICE",fix:"interface GigabitEthernet1/0/48\n switchport trunk allowed vlan add 220"},
{title:"Trunk encapsulation expectation differs on older switch",rootCause:"An older platform is set to negotiate trunk encapsulation while the peer is explicitly 802.1Q, leaving the operational mode inconsistent.",change:"A legacy distribution switch was brought back temporarily during a hardware RMA.",complaint:"The inter-switch link is up but trunking does not establish reliably.",evidence:"LEGACY# show interfaces gi0/1 switchport\nAdministrative Trunking Encapsulation: negotiate\nOperational Mode: static access\nPEER: dot1q trunk expected",fix:"interface GigabitEthernet0/1\n switchport trunk encapsulation dot1q\n switchport mode trunk\n! Command applies only on platforms that support encapsulation selection"},
{title:"Pruned trunk VLAN causes one closet outage",rootCause:"VLAN 275 is manually pruned from the trunk toward one access switch.",change:"An engineer removed supposedly unused VLANs but relied on stale port inventory.",complaint:"Only users in VLAN 275 on one closet lose access; all other closets work.",evidence:"DIST3# show interfaces trunk\nVlans allowed and active: 10,20,30,260-274,276-280\nVLAN 275 absent toward ACC9",fix:"interface GigabitEthernet1/0/9\n switchport trunk allowed vlan add 275"},
{title:"Unexpected VLAN 1 traffic crosses a hardened trunk",rootCause:"VLAN 1 remains in the trunk allowed list even though the design requires only explicit production VLANs and native VLAN 999.",change:"A new trunk was created with default allowed-VLAN behavior.",complaint:"Security review finds CDP/control and stray user traffic present in VLAN 1 between closets.",evidence:"ACC9# show interfaces trunk\nVlans allowed on trunk: 1-4094\nNative vlan: 999",fix:"interface GigabitEthernet1/0/48\n switchport trunk allowed vlan 110,120,220,999"},
{title:"AP switch port is access mode instead of an 802.1Q trunk",rootCause:"A controller-based AP carrying multiple SSIDs is connected to a static access port rather than the required trunk/profile.",change:"The AP was moved to a port previously used by a desktop.",complaint:"The AP powers up and joins, but client VLANs for corporate and guest SSIDs do not pass correctly.",evidence:"ACC10# show interfaces gi1/0/36 switchport\nAdministrative Mode: static access\nAccess Mode VLAN: 120\nExpected: AP trunk carrying 120,900",fix:"interface GigabitEthernet1/0/36\n switchport mode trunk\n switchport trunk native vlan 120\n switchport trunk allowed vlan 120,900\n! Use the organization's approved AP port design"}
]),
...ccnaDomain("Rapid PVST+, STP protections and loop prevention", [
{title:"Access switch becomes STP root after replacement",rootCause:"A replacement access switch has a lower bridge priority than the intended distribution root for VLAN 110.",change:"The switch was staged from a lab configuration with priority 0.",complaint:"Traffic takes an unexpected path through the access closet and convergence behavior changes.",evidence:"ACC8# show spanning-tree vlan 110 root\nRoot ID Priority 110\nThis bridge is the root",fix:"spanning-tree vlan 110 priority 61440\n! Restore the intended distribution switches as primary/secondary roots"},
{title:"BPDU Guard err-disables a desk port with an unauthorized switch",rootCause:"A user connected a small managed switch to a PortFast/BPDU Guard edge port and the port received BPDUs.",change:"The user needed extra Ethernet ports and installed an unmanaged/managed desktop switch.",complaint:"All devices behind the desk jack suddenly lose connectivity and the interface is err-disabled.",evidence:"ACC1# show interfaces status err-disabled\nGi1/0/40 err-disabled bpduguard\n%PM-4-ERR_DISABLE: bpduguard error detected on Gi1/0/40",fix:"! Remove the unauthorized downstream switch first\ninterface GigabitEthernet1/0/40\n shutdown\n no shutdown"},
{title:"Root Guard blocks a legitimate distribution link",rootCause:"Root Guard was mistakenly applied to a peer-facing link where superior BPDUs are expected from the primary distribution switch.",change:"An edge-port hardening template was copied to the inter-switch connection.",complaint:"The link is physically up but STP reports root-inconsistent and will not forward.",evidence:"DIST2# show spanning-tree inconsistentports\nInterface Gi1/0/47 Inconsistency: Root Inconsistent",fix:"interface GigabitEthernet1/0/47\n no spanning-tree guard root"},
{title:"Loop Guard places uplink in loop-inconsistent after unidirectional fault",rootCause:"The switch stops receiving BPDUs on one direction of a fiber path, so Loop Guard blocks the port to prevent a loop.",change:"Fiber strands were repatched during closet maintenance.",complaint:"The uplink is up at Layer 1 but STP refuses to forward it.",evidence:"DIST1# show spanning-tree inconsistentports\nGi1/1/2 Loop Inconsistent",fix:"! Repair the one-way fiber/optic problem and verify BPDUs resume\n! Keep Loop Guard enabled"},
{title:"PortFast was enabled on a switch-to-switch trunk",rootCause:"An access-switch uplink has `spanning-tree portfast trunk`, allowing immediate forwarding before normal STP convergence.",change:"An AP trunk template was reused for a switch uplink.",complaint:"Brief loops and MAC flaps appear when the downstream switch reloads.",evidence:"ACC10# show spanning-tree interface gi1/0/48 detail\nThe port is in the portfast edge trunk mode",fix:"interface GigabitEthernet1/0/48\n no spanning-tree portfast trunk"},
{title:"Manual STP cost forces traffic onto slower uplink",rootCause:"A 1-Gbps backup link has a lower configured path cost than the 10-Gbps primary link.",change:"A temporary failover-test cost override was never removed.",complaint:"The campus uses the slower link during normal operation and users see congestion.",evidence:"DIST2# show spanning-tree vlan 210\nGi1/0/47 Root FWD Cost 4\nTe1/1/1 Altn BLK Cost 2000",fix:"interface GigabitEthernet1/0/47\n no spanning-tree vlan 210 cost"},
{title:"BPDU Filter disables protection on a user port",rootCause:"`spanning-tree bpdufilter enable` was configured on a desk port, preventing expected BPDU handling and creating loop risk.",change:"A technician used BPDU Filter to stop an err-disable event instead of removing the unauthorized bridge.",complaint:"The port appears stable but network monitoring shows intermittent broadcast spikes when the user's device is connected.",evidence:"ACC3# show spanning-tree interface gi1/0/33 detail\nBpdu filter is enabled\nPort is edge forwarding",fix:"interface GigabitEthernet1/0/33\n no spanning-tree bpdufilter enable\n spanning-tree portfast\n spanning-tree bpduguard enable"},
{title:"Incorrect root primary command was applied to the wrong VLAN",rootCause:"DIST2 was made root primary for VLAN 220 instead of VLAN 120, so VLAN 120 elects an unintended access switch.",change:"The engineer mistyped the VLAN number during a root-placement change.",complaint:"Only VLAN 120 takes an inefficient path while other VLANs follow the intended root.",evidence:"DIST2# show spanning-tree vlan 120 root\nRoot port points toward ACC7\nDIST2# show spanning-tree vlan 220\nThis bridge is the root",fix:"spanning-tree vlan 120 root primary\n! Recheck the intended root design for VLAN 220 before changing it"},
{title:"One redundant uplink is blocked as expected but was mistaken for an outage",rootCause:"The interface is in Alternate/Blocking state by STP design; there is no fault on the redundant Layer-2 path.",change:"A new technician saw the blocking state after a topology change and opened an outage ticket.",complaint:"Monitoring reports one uplink as non-forwarding although users have no impact.",evidence:"ACC4# show spanning-tree vlan 130\nGi1/0/47 Root FWD\nGi1/0/48 Altn BLK",fix:"! No repair required if topology matches design\n! Document the expected alternate path and verify failover during an approved test"},
{title:"STP topology changes spike because a user port lacks PortFast",rootCause:"A frequently bouncing endpoint port is not configured as an edge/PortFast port, causing unnecessary STP topology changes.",change:"A new user port was configured manually and PortFast was omitted.",complaint:"Users across the VLAN see brief MAC relearning whenever one workstation reconnects.",evidence:"ACC5# show spanning-tree detail | include topology change\nNumber of topology changes 184 last change from Gi1/0/22\nACC5# show spanning-tree interface gi1/0/22 detail\nThe port is not edge",fix:"interface GigabitEthernet1/0/22\n spanning-tree portfast\n spanning-tree bpduguard enable"}
]),
...ccnaDomain("EtherChannel and LACP", [
{title:"LACP bundle forms with only one member because the other is suspended",rootCause:"One physical member has access-mode configuration while the Port-channel is a trunk, creating an EtherChannel consistency mismatch.",change:"A technician edited Gi1/0/48 directly instead of Port-channel10.",complaint:"The uplink works but available bandwidth is cut in half.",evidence:"ACC2# show etherchannel summary\nPo10(SU) LACP Gi1/0/47(P) Gi1/0/48(s)",fix:"default interface GigabitEthernet1/0/48\ninterface GigabitEthernet1/0/48\n channel-group 10 mode active\n! Reapply settings on Port-channel10 rather than individual members"},
{title:"LACP passive on both ends prevents channel formation",rootCause:"Both switches use `channel-group 20 mode passive`, so neither side sends the LACP negotiation needed to form the bundle.",change:"The peer was standardized from active to passive without coordinating the far side.",complaint:"Both physical links are up but Port-channel20 remains down.",evidence:"SW1# show etherchannel summary\nPo20(SD) LACP Gi1/0/45(I) Gi1/0/46(I)",fix:"interface range GigabitEthernet1/0/45-46\n channel-group 20 mode active"},
{title:"One EtherChannel member is in the wrong channel group",rootCause:"Gi1/0/2 is assigned to channel-group 31 while its peer link belongs in Port-channel30.",change:"A member was added manually during capacity work and the wrong group number was entered.",complaint:"One link bundles while the second behaves independently and STP blocks it.",evidence:"DIST1# show etherchannel summary\nPo30(SU) LACP Gi1/0/1(P)\nPo31(SD) LACP Gi1/0/2(I)",fix:"interface GigabitEthernet1/0/2\n no channel-group 31\n channel-group 30 mode active"},
{title:"Static mode on one side faces LACP active on the other",rootCause:"The local side uses EtherChannel mode `on` while the peer expects LACP active negotiation.",change:"Only one end was converted from static EtherChannel to LACP.",complaint:"The logical port-channel is down and both physical members look inconsistent.",evidence:"SW2# show etherchannel summary\nPo60(SD) - Gi1/0/43(D) Gi1/0/44(D)\nPeer: LACP active",fix:"interface range GigabitEthernet1/0/43-44\n no channel-group 60\n channel-group 60 mode active"},
{title:"Trunk allowed VLAN mismatch suspends a new LACP member",rootCause:"The newly added member has a different trunk allowed-VLAN list from existing Port-channel members.",change:"A third link was added using default interface settings.",complaint:"The new link never joins the bundle even though it is physically up.",evidence:"CORE1# show etherchannel summary\nPo40(SU) LACP Te1/0/1(P) Te1/0/2(P) Te1/0/3(s)\n%EC-5-CANNOT_BUNDLE2: incompatible port",fix:"! Match member Layer-2 settings to the Port-channel\ninterface TenGigabitEthernet1/0/3\n channel-group 40 mode active\n! Configure trunk attributes on Port-channel40"},
{title:"One member is physically down and team assumes LACP failure",rootCause:"The EtherChannel control plane is healthy; one member is down because its fiber has no receive light.",change:"Fiber was moved to a different patch-panel position.",complaint:"Port-channel capacity dropped by half but the bundle itself remains up.",evidence:"DIST3# show etherchannel summary\nPo50(SU) LACP Te1/1/1(P) Te1/1/2(D)\nDIST3# show interfaces transceiver detail | section Te1/1/2\nRx Power -40.0 dBm",fix:"! Repair the physical fiber/optic path on Te1/1/2\n! Verify it returns to bundled state (P)"},
{title:"Port-channel is shutdown while members are individually enabled",rootCause:"The logical Port-channel interface is administratively shut even though its member interfaces are no shut.",change:"The bundle was disabled for maintenance and only the physical members were re-enabled.",complaint:"Both cables show link but no traffic crosses the logical uplink.",evidence:"SW3# show interfaces port-channel 15\nPort-channel15 is administratively down, line protocol is down\nSW3# show etherchannel summary\nPo15(SD) LACP Gi1/0/47(I) Gi1/0/48(I)",fix:"interface Port-channel15\n no shutdown"},
{title:"Member speed mismatch prevents consistent EtherChannel operation",rootCause:"One physical member negotiates 100 Mbps while the other is 1 Gbps, violating bundle consistency.",change:"A damaged cable caused one member to fall back to Fast Ethernet.",complaint:"The port-channel is degraded and one link is not selected.",evidence:"SW4# show interfaces status | include Gi1/0/47|Gi1/0/48\nGi1/0/47 connected a-1000\nGi1/0/48 connected a-100",fix:"! Repair cabling/negotiation so both members operate at the same supported speed\n! Then verify EtherChannel membership"},
{title:"Port-channel VLAN configuration was applied only to physical members",rootCause:"Trunk settings were configured independently on members but not on Port-channel25, leaving the logical interface with incorrect Layer-2 behavior.",change:"A junior engineer configured each cable instead of the Port-channel interface.",complaint:"The bundle is up but some VLANs do not traverse it as intended.",evidence:"SW5# show interfaces port-channel25 switchport\nOperational Mode: static access\nSW5# show run interface gi1/0/45\n switchport mode trunk",fix:"interface Port-channel25\n switchport mode trunk\n switchport trunk allowed vlan 110,120,220,999\n! Keep member configuration consistent and minimal"},
{title:"EtherChannel hashing sends a large flow through one member as designed",rootCause:"A single large source/destination flow hashes to one link; EtherChannel does not stripe one flow packet-by-packet across all members.",change:"Backup traffic changed from many clients to one server-to-server transfer.",complaint:"One member shows high utilization while the other is mostly idle, and the team thinks the bundle is broken.",evidence:"CORE2# show etherchannel summary\nPo70(SU) LACP Te1/1/1(P) Te1/1/2(P)\nCORE2# show interfaces counters\nTe1/1/1 high traffic, Te1/1/2 low traffic",fix:"! No fault if both members are bundled and hashing matches platform design\n! Use multiple flows or review supported load-balance method if distribution is a real capacity issue"}
]),
...ccnaDomain("Wireless LAN fundamentals and access", [
{title:"Client joins SSID but receives no DHCP address",rootCause:"The WLAN maps clients to VLAN 310, but VLAN 310 is missing from the AP/uplink wired path.",change:"A new corporate SSID was created without completing the switch trunk change.",complaint:"Users can see and join the SSID but remain at self-assigned addresses with no application access.",evidence:"WLC# show wlan summary\nWLAN 3 CORP enabled\nPolicy VLAN 310\nACC1# show interfaces trunk\nVLAN 310 absent from AP uplink",fix:"! Permit VLAN 310 on the required wired trunk/path and verify the gateway/DHCP relay\n! Keep WLAN-to-VLAN mapping unchanged if it matches design"},
{title:"Wrong pre-shared key blocks one branch wireless network",rootCause:"The branch AP/WLAN profile uses an outdated WPA2/WPA3 pre-shared key after a corporate key rotation.",change:"The key was changed centrally but one standalone branch AP was missed.",complaint:"All users at one small branch fail authentication while other sites connect normally.",evidence:"AP1# show logging | include AUTH\nWPA authentication failed: invalid MIC/PSK\nChange record: new PSK deployed to all other sites",fix:"! Update the branch WLAN to the approved current PSK and have clients reconnect\n! Do not expose the key in the incident notes"},
{title:"Client is associated to distant AP with weak signal",rootCause:"The nearby AP is offline, so clients remain connected to a farther AP at poor RSSI/SNR.",change:"A PoE switch port feeding the nearby AP was disabled during cabling work.",complaint:"Wireless works but voice calls break up and throughput is very low in one conference room.",evidence:"WLC# show wireless client mac-address <client> detail\nRSSI -82 dBm\nSNR 12 dB\nAP name: AP-FAR-03\nACC2# show interfaces status | include AP-ROOM\nGi1/0/36 disabled",fix:"interface GigabitEthernet1/0/36\n no shutdown\n! Verify the nearby AP rejoins and clients roam to a healthier RF path"},
{title:"2.4 GHz channel overlap creates high contention",rootCause:"Nearby APs are manually set to overlapping 2.4-GHz channels 1, 3 and 6 instead of a non-overlapping plan.",change:"A temporary manual RF change was made during an event.",complaint:"Wireless latency and retries are high even though signal strength looks good.",evidence:"WLC RF summary: AP1 ch1, AP2 ch3, AP3 ch6\nClient retries >35% in affected area",fix:"! Restore the approved RF channel plan or controller RRM policy\n! Use non-overlapping 2.4-GHz channels according to the site's design"},
{title:"Guest SSID accidentally mapped to corporate VLAN",rootCause:"The guest WLAN policy profile maps to VLAN 120 instead of isolated guest VLAN 900.",change:"A policy profile was cloned from the corporate SSID and the VLAN field was not changed.",complaint:"Security monitoring detects guest clients receiving corporate-subnet addresses.",evidence:"WLC# show wlan summary\nGuest WLAN policy: GUEST-PROFILE\nPolicy VLAN: 120\nExpected guest VLAN: 900",fix:"! Change the guest WLAN/policy mapping to VLAN 900 and verify isolation, DHCP and Internet-only policy"},
{title:"AP fails to join controller because management reachability is missing",rootCause:"The AP management subnet has no route to the wireless controller management interface after a branch routing change.",change:"A new AP subnet was created but not added to upstream routing.",complaint:"The AP receives an IP address but remains in discovery/join loops and never serves clients.",evidence:"AP console: CAPWAP discovery request sent; no response\nAP# ping <WLC-management>\n.....",fix:"! Restore IP routing between the AP management subnet and controller\n! Verify CAPWAP reachability and AP join state"},
{title:"Wrong DNS name prevents controller discovery at remote site",rootCause:"The branch DNS record used for controller discovery points to the old WLC address.",change:"Controllers were migrated but a discovery DNS record was not updated.",complaint:"Newly reset APs at the branch cannot find the controller while already joined APs still work.",evidence:"AP# nslookup cisco-capwap-controller.local\nAddress: 10.10.99.10\nCurrent WLC management: 10.10.99.20",fix:"! Update the authoritative discovery DNS record to the current controller address and clear stale caches"},
{title:"Wireless client gets corporate IP but cannot resolve names",rootCause:"The DHCP scope for the wireless VLAN hands out a retired DNS server address.",change:"DNS servers were replaced but the wireless DHCP scope was missed.",complaint:"Users can ping internal IP addresses from Wi-Fi but websites and internal names fail.",evidence:"CLIENT: IP 10.31.0.44 gateway 10.31.0.1 DNS 10.10.60.11\nCurrent DNS servers: 10.10.60.20,10.10.60.21",fix:"! Update DHCP option 6 for the wireless scope and renew client leases"},
{title:"5 GHz clients cannot connect because SSID is enabled only on 2.4 GHz",rootCause:"The WLAN radio policy was changed to 2.4-GHz only, excluding 5-GHz-only client devices.",change:"A temporary troubleshooting radio-policy change was never reverted.",complaint:"Older devices connect, but newer 5-GHz-only scanners cannot see or join the SSID.",evidence:"WLC WLAN profile: Radio policy = 802.11b/g only\nScanner supports 5 GHz only",fix:"! Restore the approved WLAN radio policy to include 5 GHz and verify client visibility/association"},
{title:"Wireless roaming issue is actually an authentication timeout",rootCause:"RADIUS responses exceed the WLAN authentication timeout, so clients fail during reauthentication while moving between APs.",change:"AAA traffic was redirected through a slower WAN path after maintenance.",complaint:"Users say Wi-Fi drops while walking between buildings, but signal remains strong.",evidence:"WLC client log: reassociation complete; 802.1X authentication timeout\nAAA round-trip observed >5 seconds",fix:"! Restore reliable low-latency reachability to RADIUS/ISE and verify authentication timers against design\n! Do not change RF power/channel settings for an AAA transport issue"}
]),
...ccnaDomain("Static routes, default routes and path selection", [
{title:"Branch default route points to the wrong ISP next hop",rootCause:"The static default route uses 203.0.113.5 while the actual provider gateway is 203.0.113.1.",change:"A router was replaced using addressing from a different circuit.",complaint:"The branch reaches local networks but has no Internet access.",evidence:"BR1# show ip route 0.0.0.0\nS* 0.0.0.0/0 [1/0] via 203.0.113.5\nBR1# show arp | include 203.0.113.1\n203.0.113.1 reachable",fix:"no ip route 0.0.0.0 0.0.0.0 203.0.113.5\nip route 0.0.0.0 0.0.0.0 203.0.113.1"},
{title:"Floating static backup route has lower distance than primary learned route",rootCause:"The backup static route uses administrative distance 1, so it always wins over the intended dynamic primary path.",change:"A temporary emergency route was added without a higher administrative distance.",complaint:"Traffic uses the slower backup WAN even though the primary routing protocol is healthy.",evidence:"R1# show ip route 10.50.0.0\nS 10.50.0.0/16 [1/0] via 10.2.2.2\nO 10.50.0.0/16 [110/20] via 10.1.1.2",fix:"no ip route 10.50.0.0 255.255.0.0 10.2.2.2\nip route 10.50.0.0 255.255.0.0 10.2.2.2 200"},
{title:"Static route uses wrong subnet mask and misses part of remote network",rootCause:"The route is configured for 10.60.10.0/25 but the remote LAN is 10.60.10.0/24.",change:"The remote site expanded its subnet but the static route was not updated.",complaint:"Hosts .1-.126 are reachable while upper-half addresses fail.",evidence:"R2# show ip route static\nS 10.60.10.0/25 [1/0] via 10.1.2.2\nRemote LAN: 10.60.10.0/24",fix:"no ip route 10.60.10.0 255.255.255.128 10.1.2.2\nip route 10.60.10.0 255.255.255.0 10.1.2.2"},
{title:"Recursive static route points to an unreachable next hop",rootCause:"The router has a static route via 10.200.200.1 but no route exists to reach that next-hop address.",change:"The next-hop IP was copied from an old transit subnet.",complaint:"The configured static route does not install or forward traffic to the remote LAN.",evidence:"R3# show ip route 10.80.0.0\n% Network not in table\nR3# show ip route 10.200.200.1\n% Network not in table",fix:"! Correct the static route to a reachable directly connected next hop or appropriate exit interface"},
{title:"Default route was removed during configuration cleanup",rootCause:"The branch has no gateway of last resort after its only static default route was deleted.",change:"An engineer removed an old-looking `ip route 0.0.0.0` line without validating WAN design.",complaint:"Known internal connected networks work, but all unknown/Internet destinations fail.",evidence:"BR4# show ip route\nGateway of last resort is not set",fix:"ip route 0.0.0.0 0.0.0.0 <approved-WAN-next-hop>"},
{title:"Host route overrides the broader correct route",rootCause:"A stale /32 static route to one server points to the old next hop and wins over the valid /24 route.",change:"A temporary migration host route was never removed.",complaint:"One server is unreachable while every other server in the same subnet works.",evidence:"CORE# show ip route 10.90.20.55\nS 10.90.20.55/32 [1/0] via 10.9.9.9\nO 10.90.20.0/24 [110/20] via 10.1.1.2",fix:"no ip route 10.90.20.55 255.255.255.255 10.9.9.9"},
{title:"Static route points out Ethernet interface without a useful next hop",rootCause:"A route to a remote LAN specifies only a multiaccess Ethernet exit interface, causing unnecessary ARP for each remote destination and poor forwarding behavior.",change:"A serial-link example was copied to an Ethernet WAN handoff.",complaint:"The router generates many incomplete ARP entries and remote reachability is inconsistent.",evidence:"R5# show run | include ip route 10.100\nip route 10.100.0.0 255.255.0.0 GigabitEthernet0/0\nR5# show arp | include Incomplete\n<many remote destinations>",fix:"no ip route 10.100.0.0 255.255.0.0 GigabitEthernet0/0\nip route 10.100.0.0 255.255.0.0 <directly-connected-next-hop>"},
{title:"Summary static route blackholes a newly moved subnet",rootCause:"A broad 10.120.0.0/16 route still points to the branch after 10.120.200.0/24 moved to the data center.",change:"The application subnet was migrated without revisiting summary routing.",complaint:"Traffic to the migrated /24 goes to the old branch and is dropped.",evidence:"CORE# show ip route 10.120.200.10\nS 10.120.0.0/16 [1/0] via 10.1.20.2\nNew specific path is absent",fix:"! Add/restore the correct more-specific route to 10.120.200.0/24 and redesign/remove the stale summary as approved"},
{title:"Two equal-cost static routes cause traffic to use an unready path",rootCause:"A second static route with the same administrative distance was added before the backup circuit was fully operational, enabling load sharing over a broken path.",change:"The backup link was staged but application testing was not complete.",complaint:"Roughly half of user sessions fail while the other half succeed.",evidence:"R6# show ip route 10.130.0.0\nS 10.130.0.0/16 [1/0] via 10.1.30.2\n                [1/0] via 10.1.31.2",fix:"! Remove or raise the administrative distance of the unready backup route until the path is validated"},
{title:"Return path is missing even though forward static route is correct",rootCause:"The local router has a correct route to the remote LAN, but the remote router lacks a route back to the source subnet.",change:"A new local VLAN was added and only one side's static routing was updated.",complaint:"Pings leave the source router but replies never return; existing older VLANs work.",evidence:"R7# traceroute 10.140.20.10 source 10.70.50.1\nreaches remote router\nREMOTE# show ip route 10.70.50.0\n% Network not in table",fix:"REMOTE(config)# ip route 10.70.50.0 255.255.255.0 <return-next-hop>"}
])
];
