export type WorkplaceScenario = {
  id: number;
  domain: string;
  difficulty: "Basic" | "Intermediate" | "Advanced";
  title: string;
  ticket: string;
  evidence: string[];
  question: string;
  answer: string;
  commands: string[];
};

const patterns = [
  { domain: "Network Fundamentals", fault: "a damaged patch cable causing rising CRC errors", symptom: "the user's connection drops during file transfers", evidence: ["Interface is up/up", "CRC and input errors increase during traffic", "A nearby user on another port works normally"], answer: "Move the user to a known-good cable and switch port one item at a time. Rising CRC errors localize the problem to Layer 1 more strongly than IP configuration. Replace the failed cable, then verify that counters stop increasing." },
  { domain: "Network Fundamentals", fault: "a speed or duplex mismatch", symptom: "the link is slow and has late collisions", evidence: ["Ping works but throughput is poor", "Late collisions and interface errors increase", "One side is forced and the other negotiates"], answer: "Make both ends use compatible auto-negotiation or explicitly matching settings. Clear counters only after recording them, retest throughput, and confirm that collision/error counters remain stable." },
  { domain: "IPv4 & Subnetting", fault: "an incorrect /25 mask on a /24 user LAN", symptom: "half of the local subnet appears unreachable", evidence: ["The default gateway responds", "Addresses above the client's calculated boundary fail", "Other clients use a different mask"], answer: "Correct the client's prefix to match the documented subnet. The wrong mask makes some local destinations appear remote, so the host sends them to the gateway instead of resolving them directly." },
  { domain: "IPv4 & Subnetting", fault: "a duplicate IPv4 address", symptom: "connectivity alternates between two devices", evidence: ["ARP output maps one IP to changing MAC addresses", "Both endpoints report intermittent conflicts", "The switch learns each MAC on a different access port"], answer: "Identify both owners from DHCP/IPAM and the switch MAC table, remove the unauthorized static assignment, renew addressing, and reserve or exclude infrastructure addresses to prevent recurrence." },
  { domain: "IPv6", fault: "router advertisements blocked by an IPv6 ACL", symptom: "clients have link-local addresses but no usable global prefix", evidence: ["FE80:: addresses exist", "No default IPv6 route appears", "The router interface has the correct /64"], answer: "Permit the required ICMPv6 Router Advertisement and Neighbor Discovery traffic. IPv6 control functions depend on ICMPv6; blocking it broadly prevents prefix and default-router learning." },
  { domain: "Switching", fault: "the user port assigned to the voice VLAN instead of the data VLAN", symptom: "the phone works but the attached computer cannot reach business services", evidence: ["The switch port is physically up", "The PC receives an address from the wrong scope or none", "The phone registers successfully"], answer: "Restore the correct access VLAN while retaining the intended voice VLAN. Then renew the PC lease and verify the MAC table shows the phone and PC in their proper VLAN contexts." },
  { domain: "Switching", fault: "a newly created VLAN missing from the trunk allowed list", symptom: "users work on one switch but not across the uplink", evidence: ["Local same-VLAN pings work", "The trunk is operational", "The affected VLAN is absent from the allowed/forwarding list"], answer: "Add the VLAN to the allowed list on both trunk ends using a command that does not overwrite existing VLANs. Verify show interfaces trunk and test the return direction." },
  { domain: "Switching", fault: "a native VLAN mismatch", symptom: "management traffic is inconsistent and the switches log native mismatch warnings", evidence: ["CDP reports a mismatch", "Both trunk ports are up", "Untagged traffic lands in different VLANs"], answer: "Set the same intentionally unused native VLAN on both ends and verify the trunk. Do not merely suppress the warning; mismatched untagged classification can leak or misdirect traffic." },
  { domain: "Spanning Tree", fault: "an access switch accidentally elected as STP root", symptom: "campus traffic takes an inefficient path and reconverges slowly", evidence: ["The root bridge ID belongs to an access switch", "Distribution uplinks show unexpected roles", "A recent switch arrived with a lower priority"], answer: "Set explicit primary and secondary root priorities on the intended distribution switches, then verify root and port roles per VLAN. Add Root Guard where superior BPDUs must never arrive." },
  { domain: "EtherChannel", fault: "one LACP member configured as an access port while the bundle is a trunk", symptom: "the port-channel is degraded and one link is suspended", evidence: ["LACP neighbor information is visible", "One member has an incompatible state", "The logical port-channel remains up on fewer links"], answer: "Remove the inconsistent member configuration and apply common Layer 2 settings to the port-channel. Rejoin the member, verify bundled status, and confirm load distribution without relying on one flow." },
  { domain: "Routing", fault: "a missing return route", symptom: "a branch can send traffic to headquarters but receives no replies", evidence: ["The forward path reaches the destination router", "The destination subnet has no route back to the branch", "Local traffic at headquarters works"], answer: "Install or advertise the branch prefix into the return routing domain. Validate both directions and avoid masking the design fault with an overly broad default unless that is the approved architecture." },
  { domain: "Routing", fault: "a floating static route with an administrative distance lower than OSPF", symptom: "traffic uses the backup WAN during normal operation", evidence: ["Both paths are available", "The static route is installed", "OSPF advertises the same prefix"], answer: "Raise the static route's administrative distance above OSPF so it truly floats. Confirm the primary route wins normally, then fail the primary and verify the backup appears and later withdraws." },
  { domain: "OSPF", fault: "an OSPF area mismatch", symptom: "two directly connected routers never form an adjacency", evidence: ["Layer 3 ping succeeds", "Hello packets are observed", "Each interface is assigned to a different area"], answer: "Place both ends of the shared link in the same intended area. Then verify neighbor state reaches FULL and that expected prefixes enter the routing table." },
  { domain: "OSPF", fault: "an OSPF passive interface applied to a transit link", symptom: "a routed link works for static traffic but forms no OSPF neighbor", evidence: ["The connected route exists", "No OSPF hellos leave the interface", "The interface appears in the passive list"], answer: "Remove passive status from the transit interface while leaving endpoint LANs passive. Verify adjacency, LSDB information, and installed routes rather than stopping at neighbor-up." },
  { domain: "DHCP & DNS", fault: "a missing DHCP relay address on a new VLAN", symptom: "new clients self-assign 169.254 addresses", evidence: ["The VLAN gateway responds when addressed statically", "The DHCP server is on another subnet", "No relayed discover reaches the server"], answer: "Configure the approved helper address on the client-facing SVI, verify the relay's source subnet is scoped on the server, renew the lease, and confirm correct mask, gateway, and DNS options." },
  { domain: "DHCP & DNS", fault: "an incorrect DNS server option", symptom: "users can ping public IP addresses but cannot open sites by name", evidence: ["Default gateway and Internet IP reachability work", "nslookup times out against the assigned server", "Clients received the same bad DHCP option"], answer: "Correct the DHCP DNS option, renew leases or update clients, and test a known record. Separate DNS resolution from IP reachability so routing and NAT are not changed unnecessarily." },
  { domain: "NAT & ACLs", fault: "NAT inside and outside roles reversed", symptom: "private clients reach the edge but create no useful translations", evidence: ["The default route exists", "The NAT ACL matches client addresses", "show ip nat translations remains empty"], answer: "Apply ip nat inside to the LAN-facing interface and ip nat outside to the provider-facing interface. Generate fresh traffic and verify translations, routing, and return traffic." },
  { domain: "NAT & ACLs", fault: "a broad ACL deny placed above the required permit", symptom: "a new application stops at the routed boundary", evidence: ["Routing and ARP are healthy", "The deny entry counter rises", "The permit below it never receives hits"], answer: "Reorder the ACL so the specific approved traffic is permitted before the broader deny, document the policy with remarks, and retest both allowed and intentionally blocked flows." },
  { domain: "Wireless", fault: "2.4 GHz co-channel contention from overlapping APs", symptom: "users show strong signal but poor performance at busy times", evidence: ["RSSI is strong", "Channel utilization and retry rates are high", "Adjacent APs share the same channel"], answer: "Create a measured channel and power plan using non-overlapping channels, favor appropriate 5/6 GHz capacity, and retest airtime utilization. Strong signal alone does not prove a healthy WLAN." },
  { domain: "Wireless", fault: "a RADIUS certificate expired", symptom: "enterprise Wi-Fi clients can see the SSID but cannot authenticate", evidence: ["Association attempts reach the controller", "RADIUS logs report TLS/certificate failure", "The issue began at a precise expiration time"], answer: "Renew and deploy the trusted certificate chain, confirm client trust and synchronized time, then validate 802.1X authentication with a test identity before broad rollout." },
  { domain: "Security", fault: "DHCP snooping trusts an endpoint port", symptom: "a rogue DHCP server gives users incorrect gateways", evidence: ["Clients receive unexpected leases", "The offer source traces to an access port", "That access port is incorrectly trusted"], answer: "Remove trust from the endpoint port, retain trust only on approved infrastructure-facing paths, clear bad leases, and verify the snooping binding database and legitimate DHCP exchange." },
  { domain: "Security", fault: "port security maximum set below the phone-plus-PC requirement", symptom: "the switch err-disables a desk port when the computer connects", evidence: ["The phone alone works", "A port-security violation is logged", "The allowed MAC maximum is one"], answer: "Set the approved maximum for the phone and attached computer, choose the organization's violation action, recover the port safely, and verify learned secure MAC addresses." },
  { domain: "Automation", fault: "an automation script treats a partial API response as complete", symptom: "the compliance report marks valid interfaces as missing", evidence: ["The HTTP response indicates pagination", "Only the first result set was parsed", "Manual device state contains more interfaces"], answer: "Handle pagination and validate response completeness before evaluating compliance. Fail closed on missing fields, log the request status, and test against empty, partial, and multi-page data." },
  { domain: "Operations", fault: "unsynchronized device clocks", symptom: "logs from the same outage appear in the wrong order", evidence: ["Timestamps differ by several minutes", "NTP state is unsynchronized", "Event sequence conflicts with packet evidence"], answer: "Restore authenticated, reachable NTP using deliberate source interfaces, then correlate the incident with corrected offsets. Reliable time is a prerequisite for defensible event analysis." },
  { domain: "Operations", fault: "an MTU mismatch across a tunnel", symptom: "small pings work but large transfers stall", evidence: ["Basic reachability succeeds", "Large packets with Don't Fragment fail", "The path includes new encapsulation overhead"], answer: "Measure the effective path MTU, correct interface/tunnel MTU or MSS policy as designed, and ensure required ICMP messages are permitted. Retest the actual application, not only small pings." },
];

const locations = ["headquarters", "a new branch", "the warehouse", "the training room", "the executive floor", "a remote clinic", "the call center", "the guest lobby"];

export const workplaceScenarios: WorkplaceScenario[] = Array.from({ length: 200 }, (_, index) => {
  const pattern = patterns[index % patterns.length];
  const cycle = Math.floor(index / patterns.length);
  const location = locations[(index + cycle) % locations.length];
  const difficulty: WorkplaceScenario["difficulty"] = index < 70 ? "Basic" : index < 145 ? "Intermediate" : "Advanced";
  return {
    id: index + 1,
    domain: pattern.domain,
    difficulty,
    title: `${pattern.domain}: ${pattern.symptom[0].toUpperCase()}${pattern.symptom.slice(1)}`,
    ticket: `You are the network technician supporting ${location}. Ticket CCNA-${String(index + 1).padStart(3, "0")} reports that ${pattern.symptom}. The service worked before ${cycle % 3 === 0 ? "a workstation move" : cycle % 3 === 1 ? "a scheduled network change" : "the morning shift began"}. Your task is to diagnose the incident without disrupting unaffected users.`,
    evidence: [...pattern.evidence, `The suspected fault is limited to ${location}; a comparison test elsewhere succeeds.`],
    question: `What is the most likely root cause, which evidence proves it, and what should you do to restore service safely?`,
    answer: `Most likely root cause: ${pattern.fault}. ${pattern.answer} Finish by recording the original symptom, the evidence, the exact change, and a post-change test.`,
    commands: ["show interfaces status", "show ip interface brief", index % 2 === 0 ? "show mac address-table" : "show ip route", index % 3 === 0 ? "show logging" : "show running-config | section interface"],
  };
});

export const scenarioDomains = ["All", ...Array.from(new Set(workplaceScenarios.map((item) => item.domain)))];
