function decodeEntities(s=''){return String(s).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function attr(html,re){const m=String(html).match(re);return m?decodeEntities(m[1]):''}
function absolute(u,base){try{if(!u)return'';if(u.startsWith('//'))return'https:'+u;return new URL(u,base).href}catch{return''}}
function isGoogleNews(u=''){try{return new URL(u).hostname==='news.google.com'}catch{return false}}
function googleId(u=''){try{const p=new URL(u).pathname.split('/').filter(Boolean);return p[p.length-1]||''}catch{return''}}
function oldGoogleDecode(u=''){try{const id=googleId(u);let b=Buffer.from(id.replace(/-/g,'+').replace(/_/g,'/'),'base64');const prefix=Buffer.from([0x08,0x13,0x22]);if(b.subarray(0,3).equals(prefix))b=b.subarray(3);const suffix=Buffer.from([0xd2,0x01,0x00]);if(b.length>=3&&b.subarray(b.length-3).equals(suffix))b=b.subarray(0,b.length-3);if(!b.length)return'';let len=b[0],start=1;if(len>=0x80){len=(len&0x7f)|(b[1]<<7);start=2}const out=b.subarray(start,start+len).toString('utf8');return /^https?:\/\//i.test(out)?out:''}catch{return''}}
async function fetchText(url,timeout=5000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','accept-language':'en-US,en;q=0.8'}});if(!r.ok)throw Error(String(r.status));return{text:await r.text(),url:r.url}}finally{clearTimeout(t)}}
async function resolveGoogle(u){const legacy=oldGoogleDecode(u);if(legacy)return legacy;const id=googleId(u);if(!id)return'';try{const page=await fetchText(`https://news.google.com/rss/articles/${encodeURIComponent(id)}?hl=en-US&gl=US&ceid=US:en`,5000);const sig=attr(page.text,/data-n-a-sg=["']([^"']+)["']/i),ts=attr(page.text,/data-n-a-ts=["']([^"']+)["']/i);if(!sig||!ts)return'';const inner=['garturlreq',[['X','X',['X','X'],null,null,1,1,'US:en',null,1,null,null,null,null,null,0,1],'X','X',1,[1,1,1],1,1,null,0,0,null,0],id,Number(ts),sig];const rpc=['Fbv4je',JSON.stringify(inner)];const body=new URLSearchParams({'f.req':JSON.stringify([[rpc]])}).toString();const c=new AbortController(),timer=setTimeout(()=>c.abort(),5000);let text='';try{const r=await fetch('https://news.google.com/_/DotsSplashUi/data/batchexecute',{method:'POST',signal:c.signal,headers:{'content-type':'application/x-www-form-urlencoded;charset=UTF-8','referer':'https://news.google.com/'},body});if(!r.ok)return'';text=await r.text()}finally{clearTimeout(timer)}for(const part of text.split('\n\n')){const s=part.trim();if(!s.startsWith('['))continue;try{const rows=JSON.parse(s);for(const row of rows){if(!Array.isArray(row)||typeof row[2]!=='string')continue;try{const payload=JSON.parse(row[2]);if(Array.isArray(payload)&&payload[0]==='garturlres'&&/^https?:\/\//i.test(payload[1]||''))return payload[1]}catch{}}}catch{}}const m=text.match(/\\"garturlres\\",\\"(https?:\\\/\\\/[^"\\]+(?:\\.[^"\\]+)*)/);if(m){try{return JSON.parse('"'+m[1]+'"')}catch{}}return''}catch{return''}}
function imageCandidates(html,base){const out=[];const add=u=>{u=absolute(decodeEntities(u),base);if(!u||!/^https?:\/\//i.test(u))return;const low=u.toLowerCase();if(/(?:favicon|sprite|avatar|gravatar|emoji|tracking|pixel|badge|icon[-_.]|logo[-_.]|\/logo\b)/.test(low))return;if(!out.includes(u))out.push(u)};const patterns=[/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)["']/ig,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["']/ig,/<meta[^>]+name=["']twitter:image(?::src)?["'][^>]+content=["']([^"']+)["']/ig,/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']twitter:image(?::src)?["']/ig,/<link[^>]+rel=["'][^"']*image_src[^"']*["'][^>]+href=["']([^"']+)["']/ig,/<meta[^>]+itemprop=["']image["'][^>]+content=["']([^"']+)["']/ig];for(const re of patterns){for(const m of html.matchAll(re))add(m[1])}for(const m of html.matchAll(/<img[^>]+(?:data-src|data-original|src)=["']([^"']+)["'][^>]*>/ig))add(m[1]);return out.slice(0,12)}
async function proxyImage(url,res){const c=new AbortController(),t=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept':'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8','referer':new URL(url).origin+'/'}});if(!r.ok)throw Error(String(r.status));const type=String(r.headers.get('content-type')||'');if(!type.toLowerCase().startsWith('image/'))throw Error('not image');const buf=Buffer.from(await r.arrayBuffer());if(!buf.length||buf.length>8*1024*1024)throw Error('bad size');res.setHeader('Content-Type',type.split(';')[0]);res.setHeader('Cache-Control','public, max-age=21600, s-maxage=86400, stale-while-revalidate=604800');res.setHeader('Content-Length',String(buf.length));res.status(200).send(buf);return true}catch{return false}finally{clearTimeout(t)}}
function fallback(res,seed,title){const q=new URLSearchParams({seed:String(seed||'ai-news'),title:String(title||'AI News').slice(0,100)});res.setHeader('Cache-Control','public, max-age=3600, s-maxage=21600');res.redirect(307,'/api/article-art?'+q.toString())}
module.exports=async function(req,res){const article=String(req.query?.article||'').slice(0,3000),direct=String(req.query?.image||'').slice(0,3000),seed=String(req.query?.seed||article||'ai-news').slice(0,180),title=String(req.query?.title||'AI News').slice(0,120);try{if(direct&&/^https?:\/\//i.test(direct)&&!isGoogleNews(direct)){if(await proxyImage(direct,res))return}let target=article;if(isGoogleNews(target))target=await resolveGoogle(target)||target;if(target&&/^https?:\/\//i.test(target)&&!isGoogleNews(target)){try{const page=await fetchText(target,5500);const candidates=imageCandidates(page.text,page.url||target);for(const candidate of candidates){if(await proxyImage(candidate,res))return}}catch{}}fallback(res,seed,title)}catch{fallback(res,seed,title)}};
