function decode(s=''){return String(s).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#8217;|&#39;|&apos;/g,"'").replace(/&#8220;|&#8221;|&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function clean(s=''){return decode(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function tag(b,n){const m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'));return m?clean(m[1]):''}
function attr(b,re){const m=b.match(re);return m?decode(m[1]):''}
function link(b){const d=tag(b,'link');if(d&&/^https?:/i.test(d))return d;const m=b.match(/<link[^>]+href=["']([^"']+)["']/i);return m?decode(m[1]):tag(b,'guid')}
function hash(s=''){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h.toString(36)}
function image(b){return attr(b,/<media:content[^>]+url=["']([^"']+)["']/i)||attr(b,/<enclosure[^>]+url=["']([^"']+)["'][^>]*type=["']image/i)||attr(b,/<media:thumbnail[^>]+url=["']([^"']+)["']/i)||attr(b,/<img[^>]+src=["']([^"']+)["']/i)}
function parse(xml,source){const blocks=[...(xml.match(/<item\b[\s\S]*?<\/item>/gi)||[]),...(xml.match(/<entry\b[\s\S]*?<\/entry>/gi)||[])];return blocks.slice(0,80).map(b=>{const title=tag(b,'title')||'Untitled technology story',url=link(b),description=(tag(b,'description')||tag(b,'summary')||tag(b,'content')).slice(0,360)||'Latest major technology development.',date=tag(b,'pubDate')||tag(b,'published')||tag(b,'updated')||new Date().toISOString();let publishedAt;try{publishedAt=new Date(date).toISOString()}catch{publishedAt=new Date().toISOString()}return{id:hash(source+title+url),title,link:url,source,publishedAt,description,image:image(b)}}).filter(x=>/^https?:\/\//i.test(x.link))}
async function get(url,timeout=4200){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 AI-News-Now/6.4','accept':'application/rss+xml,application/xml,text/html;q=0.9,*/*;q=0.8'}});if(!r.ok)throw Error(String(r.status));return await r.text()}finally{clearTimeout(t)}}
async function load(source,url){try{return parse(await get(url),source)}catch{return[]}}
function google(q){return `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`}
const feeds=[
['Major Tech News',google('((OpenAI OR Anthropic OR Google OR Microsoft OR Nvidia OR Apple OR Amazon OR Meta OR AMD OR Intel OR Cloudflare OR Cisco OR Red Hat) OR cybersecurity OR technology) (breaking OR launch OR release OR outage OR breach OR vulnerability OR zero-day OR acquisition OR regulation OR recall OR shutdown) when:2d')],
['Security Breaking',google('(ransomware OR "zero-day" OR "actively exploited" OR "critical vulnerability" OR cyberattack OR "major outage") when:2d')],
['Latest Gadgets',google('(smartphone OR laptop OR GPU OR CPU OR SSD OR monitor OR router OR wearable OR gadget OR "hardware device" OR headset OR "gaming mouse" OR "gaming keyboard" OR controller) (launch OR launches OR unveiled OR unveils OR release OR releases OR announced OR introduces) when:2d')],
['Red Hat',google('(site:redhat.com OR site:access.redhat.com) ("Red Hat" OR RHEL OR OpenShift OR Ansible OR Linux OR vulnerability OR security OR AI) when:7d')],
['Black Hat',google('("Black Hat" AND (cybersecurity OR vulnerability OR exploit OR malware OR security research OR hacking OR AI security)) when:7d')],
['BleepingComputer','https://www.bleepingcomputer.com/feed/'],
['The Hacker News','https://thehackernews.com/feeds/posts/default'],
['SecurityWeek','https://www.securityweek.com/feed/'],
['Ars Technica Security','https://arstechnica.com/security/feed/'],
['TechPowerUp','https://www.techpowerup.com/rss/news'],
['TechCrunch','https://techcrunch.com/category/artificial-intelligence/feed/'],
['The Verge','https://www.theverge.com/rss/ai-artificial-intelligence/index.xml']
];
const HIGH=['zero-day','zero day','actively exploited','critical vulnerability','ransomware','major outage','global outage','outage','emergency','cyberattack','cyber attack','security incident','acquires','acquisition','merger','recall','shutdown','disruption','ban ','regulation'];
const RELEASE=['launches','launched','unveils','unveiled','releases','released','introduces','announces','announced','new model','new chip','new gpu','new cpu','new laptop','new phone','new device','new gadget'];
const MAJOR=['openai','anthropic','chatgpt','claude','gemini','google','microsoft','nvidia','apple','amazon','aws','meta','amd','intel','cloudflare','cisco','oracle','github','red hat','rhel','openshift','ansible','black hat'];
const TECH=['windows','linux','rhel','red hat','openshift','ansible','cybersecurity','security','gpu','cpu','chip','semiconductor','data center','server','cloud','artificial intelligence',' ai ','model','robotics','infrastructure','smartphone','laptop','ssd','monitor','router','wearable','gadget','device','headset','controller','keyboard','mouse'];
const TRUSTED=new Set(['BleepingComputer','The Hacker News','SecurityWeek','Ars Technica Security','TechPowerUp','TechCrunch','The Verge','Red Hat','Black Hat','Latest Gadgets']);
const LOW=['school district','high school','college students','university workshop','seminar','classroom','pastor','dental','psychiatric','opinion |','prediction:','webinar','pr newswire','sponsored','partner content'];
const HARD_BLOCK=/\b(lawsuit|sued|sues|suing|court|judge|attorney|law firm|settlement|class action|claim depot|legal claim|legal action|arrested|arrest|deputies|ran toward|runway|charged with|indicted|sentenced|pleads guilty|wrongful death|personal injury)\b/i;
const GAME_SOFTWARE=/\b(gameplay trailer|official trailer|release date trailer|new game|video game|dlc|steam release|now available on pc|playstation 5 and xbox|xbox series consoles)\b/i;
const HARDWARE_WORDS=/\b(gpu|cpu|chip|processor|motherboard|laptop|smartphone|phone|ssd|monitor|router|wearable|earbuds|headset|controller|keyboard|mouse|hardware|device|robot|console hardware|handheld)\b/i;
const RELEVANT=/(openai|anthropic|chatgpt|claude|gemini|google|microsoft|nvidia|apple|amazon|aws|meta|amd|intel|cloudflare|cisco|oracle|github|red hat|rhel|openshift|ansible|black hat|windows|linux|cybersecurity|security|ransomware|malware|vulnerab|zero.?day|exploit|hack|phishing|cisa|outage|gpu|cpu|chip|semiconductor|data center|server|cloud|artificial intelligence|\bai\b|model|robotics|infrastructure|smartphone|laptop|ssd|monitor|router|wearable|gadget|device|headset|controller|keyboard|mouse)/i;
function wanted(n){const txt=(n.title+' '+n.description+' '+n.source);if(HARD_BLOCK.test(txt))return false;if(GAME_SOFTWARE.test(txt)&&!HARDWARE_WORDS.test(n.title))return false;if(!RELEVANT.test(txt))return false;return true}
function score(n){const txt=(' '+n.title+' '+n.description+' '+n.source+' ').toLowerCase(),age=(Date.now()-new Date(n.publishedAt))/36e5;let s=0;if(age<=1)s+=85;else if(age<=3)s+=72;else if(age<=6)s+=60;else if(age<=12)s+=48;else if(age<=24)s+=34;else if(age<=48)s+=18;else s+=6;if(TRUSTED.has(n.source))s+=12;let h=0;for(const k of HIGH)if(txt.includes(k))h++;s+=Math.min(h,3)*20;let r=0;for(const k of RELEASE)if(txt.includes(k))r++;s+=Math.min(r,2)*14;let m=0;for(const k of MAJOR)if(txt.includes(k))m++;s+=Math.min(m,3)*9;let t=0;for(const k of TECH)if(txt.includes(k))t++;s+=Math.min(t,3)*5;if(/critical|zero.?day|ransomware|outage|acquisition|shutdown|recall/i.test(n.title))s+=16;if(/launch|unveil|release|introduc|new (gpu|cpu|chip|laptop|phone|device|gadget)/i.test(n.title))s+=10;for(const k of LOW)if(txt.includes(k))s-=45;if(h===0&&r===0&&m===0&&t===0)s-=25;return Math.round(s)}
function severity(score,n){const t=(n.title+' '+n.description).toLowerCase(),trusted=TRUSTED.has(n.source);if(/zero.?day|actively exploited|critical vulnerability|major outage|global outage/.test(t))return'BREAKING';if(/ransomware/.test(t)&&/(federal|government|agency|airport|hospital|global|major|million|billion)/.test(t))return'BREAKING';if(/acquisition|acquires|agreed to buy|deal/.test(t)&&/\$?\d+(?:\.\d+)?\s*b(?:illion)?\b/.test(t))return'BREAKING';if(score>=125&&trusted)return'BREAKING';if(score>=92||/ransomware|cyberattack|acquisition|acquires|launches|released|unveils|introduces|regulation|recall|shutdown/.test(t))return'MAJOR';return'DEVELOPING'}
function topic(n){const t=(n.title+' '+n.description).toLowerCase();if(/ransomware|malware|breach|vulnerab|zero.?day|cyber|hack|phishing|security|cisa|actively exploited|exploit|black hat/.test(t))return'Cyber';if(/nvidia|amd|intel|gpu|cpu|chip|semiconductor|hardware|smartphone|laptop|ssd|monitor|router|wearable|gadget|device|headset|controller|keyboard|mouse/.test(t))return'Hardware';if(/windows|linux|rhel|red hat|openshift|ansible|server|cloud|outage|network|infrastructure/.test(t))return'IT';if(/funding|valuation|acquisition|merger|earnings|regulation/.test(t))return'Business';return'AI'}
function why(n){const t=(n.title+' '+n.description).toLowerCase();if(/zero.?day|actively exploited|critical vulnerab/.test(t))return'Organizations may need to patch or mitigate exposure quickly.';if(/ransomware|breach|cyberattack/.test(t))return'This may affect security operations, users, data or incident response.';if(/outage|disruption/.test(t))return'The disruption may affect users, businesses and dependent services.';if(/red hat|rhel|openshift|ansible/.test(t))return'This can affect Linux, enterprise infrastructure, cloud platforms and system administrators.';if(/black hat/.test(t))return'This security research may reveal new attack techniques, vulnerabilities or defensive priorities.';if(HARDWARE_WORDS.test(t))return'This is a new technology or hardware development that may affect buyers, builders or IT environments.';if(/acquisition|merger/.test(t))return'The deal could change competition, products, infrastructure or the AI ecosystem.';if(/launch|release|unveil|introduc/.test(t))return'The release may change available capabilities, products or developer workflows.';return'This is a high-signal technology development worth monitoring.'}
const STOP=new Set('the a an and or of to in on for with after over from at by as is are was were has have had its their this that new says say news major recent data cyber cybersecurity security attack breach incident report reports'.split(' '));
function tokens(n){return new Set(n.title.toLowerCase().replace(/\s+-\s+[^-]{2,70}$/,'').replace(/[^a-z0-9$]+/g,' ').split(' ').filter(x=>x.length>2&&!STOP.has(x)).slice(0,20))}
function similar(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return false;let hit=0;for(const x of A)if(B.has(x))hit++;return hit>=3&&hit/Math.min(A.size,B.size)>=.48}
function collapse(items){const out=[];for(const n of items){if(out.some(x=>Math.abs(new Date(x.publishedAt)-new Date(n.publishedAt))<48*36e5&&similar(x,n)))continue;out.push(n)}return out}
function imageRoute(n,i,origin){const p=new URLSearchParams({article:n.link,seed:n.id||hash(n.title+n.link+i),title:n.title.slice(0,100),variant:String(i)});if(/^https?:\/\//i.test(n.image||''))p.set('image',n.image);return `${origin}/api/article-image?${p.toString()}`}
module.exports=async function(req,res){res.setHeader('Cache-Control','public, max-age=20, stale-while-revalidate=60');res.setHeader('Vercel-CDN-Cache-Control','public, max-age=30, stale-while-revalidate=60');const all=(await Promise.all(feeds.map(f=>load(f[0],f[1])))).flat();const seen=new Set();let items=all.filter(wanted).filter(n=>{const k=n.title.toLowerCase().replace(/\s+-\s+[^-]{2,70}$/,'').replace(/[^a-z0-9]+/g,' ').split(' ').slice(0,14).join(' ');if(!k||seen.has(k))return false;seen.add(k);return true}).filter(n=>(Date.now()-new Date(n.publishedAt))<72*36e5).map(n=>{const priority=score(n);return{...n,priority,severity:severity(priority,n),topic:topic(n),whyItMatters:why(n)}}).filter(n=>n.priority>=68).sort((a,b)=>+new Date(b.publishedAt)-+new Date(a.publishedAt)||b.priority-a.priority);items=collapse(items).slice(0,30);const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0].trim(),host=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim(),origin=host?`${proto}://${host}`:'https://cert-forge-git-ai-news-now-site-cloud-drive.vercel.app';items=items.map((n,i)=>({...n,image:imageRoute(n,i,origin)}));const severityCounts=items.reduce((a,n)=>(a[n.severity]=(a[n.severity]||0)+1,a),{BREAKING:0,MAJOR:0,DEVELOPING:0});res.status(200).json({updatedAt:new Date().toISOString(),refreshSeconds:60,count:items.length,severityCounts,ranking:'newest-first-tech-security-hardware',news:items})};
