function decode(s=''){return String(s).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#8217;|&#39;|&apos;/g,"'").replace(/&#8220;|&#8221;|&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function clean(s=''){return decode(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function tag(b,n){const m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'));return m?clean(m[1]):''}
function attr(b,re){const m=b.match(re);return m?decode(m[1]):''}
function link(b){const d=tag(b,'link');if(d&&/^https?:/i.test(d))return d;const m=b.match(/<link[^>]+href=["']([^"']+)["']/i);return m?decode(m[1]):tag(b,'guid')}
function hash(s=''){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h.toString(36)}
function image(b){return attr(b,/<media:content[^>]+url=["']([^"']+)["']/i)||attr(b,/<enclosure[^>]+url=["']([^"']+)["'][^>]*type=["']image/i)||attr(b,/<media:thumbnail[^>]+url=["']([^"']+)["']/i)||attr(b,/<img[^>]+src=["']([^"']+)["']/i)}
function parse(xml,source){const blocks=[...(xml.match(/<item\b[\s\S]*?<\/item>/gi)||[]),...(xml.match(/<entry\b[\s\S]*?<\/entry>/gi)||[])];return blocks.slice(0,80).map(b=>{const title=tag(b,'title')||'Untitled technology story',url=link(b),description=(tag(b,'description')||tag(b,'summary')||tag(b,'content')).slice(0,360)||'Latest major technology development.',date=tag(b,'pubDate')||tag(b,'published')||tag(b,'updated')||new Date().toISOString();let publishedAt;try{publishedAt=new Date(date).toISOString()}catch{publishedAt=new Date().toISOString()}return{id:hash(source+title+url),title,link:url,source,publishedAt,description,image:image(b)}}).filter(x=>/^https?:\/\//i.test(x.link))}
async function get(url,timeout=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 AI-News-Now/5.0','accept':'application/rss+xml,application/xml,text/html;q=0.9,*/*;q=0.8'}});if(!r.ok)throw Error(String(r.status));return await r.text()}finally{clearTimeout(t)}}
async function load(source,url){try{return parse(await get(url),source)}catch{return[]}}
function google(q){return `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`}
const feeds=[
 ['Major Tech News',google('(technology OR artificial intelligence OR cybersecurity OR cloud OR semiconductor) (breaking OR launch OR outage OR breach OR vulnerability OR acquisition OR regulation OR lawsuit) when:2d')],
 ['Big Tech',google('(OpenAI OR Anthropic OR Google OR Microsoft OR Nvidia OR Apple OR Amazon OR Meta OR AMD OR Intel) when:2d')],
 ['BleepingComputer','https://www.bleepingcomputer.com/feed/'],
 ['The Hacker News','https://thehackernews.com/feeds/posts/default'],
 ['SecurityWeek','https://www.securityweek.com/feed/'],
 ['Ars Technica Security','https://arstechnica.com/security/feed/'],
 ['TechCrunch','https://techcrunch.com/category/artificial-intelligence/feed/'],
 ['The Verge','https://www.theverge.com/rss/ai-artificial-intelligence/index.xml']
];
const high=['breaking','zero-day','zero day','actively exploited','critical vulnerability','ransomware','data breach','breach','major outage','global outage','outage','emergency','cyberattack','cyber attack','launches','launched','unveils','unveiled','announces','acquires','acquisition','merger','bans','ban ','regulation','antitrust','lawsuit','recall','shutdown','disruption'];
const tech=['openai','anthropic','chatgpt','claude','gemini','google','microsoft','nvidia','apple','amazon','aws','meta','amd','intel','cloudflare','cisco','windows','linux','ai ','artificial intelligence','cybersecurity','security','gpu','chip','semiconductor','data center','server','cloud'];
function score(n){const txt=(n.title+' '+n.description).toLowerCase(),age=(Date.now()-new Date(n.publishedAt))/36e5;let s=0;if(age<=2)s+=70;else if(age<=6)s+=58;else if(age<=12)s+=46;else if(age<=24)s+=34;else if(age<=48)s+=18;else s-=20;for(const k of high)if(txt.includes(k))s+=18;for(const k of tech)if(txt.includes(k))s+=4;if(/critical|emergency|breaking|zero-day|ransomware|breach|outage/i.test(n.title))s+=24;if(['BleepingComputer','The Hacker News','SecurityWeek','Ars Technica Security','TechCrunch','The Verge'].includes(n.source))s+=5;return s}
function imageRoute(n,i,origin){const p=new URLSearchParams({article:n.link,seed:n.id||hash(n.title+n.link+i),title:n.title.slice(0,100),variant:String(i)});if(/^https?:\/\//i.test(n.image||''))p.set('image',n.image);return `${origin}/api/article-image?${p.toString()}`}
module.exports=async function(req,res){res.setHeader('Cache-Control','s-maxage=120, stale-while-revalidate=300');const all=(await Promise.all(feeds.map(f=>load(f[0],f[1])))).flat();const seen=new Set();let items=all.filter(n=>{const k=n.title.toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').slice(0,12).join(' ');if(!k||seen.has(k))return false;seen.add(k);return true}).filter(n=>(Date.now()-new Date(n.publishedAt))<72*36e5).map(n=>({...n,priority:score(n)})).sort((a,b)=>b.priority-a.priority||+new Date(b.publishedAt)-+new Date(a.publishedAt)).slice(0,40);const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0].trim(),host=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim(),origin=host?`${proto}://${host}`:'https://cert-forge-git-ai-news-now-site-cloud-drive.vercel.app';items=items.map((n,i)=>({...n,image:imageRoute(n,i,origin)}));res.status(200).json({updatedAt:new Date().toISOString(),refreshSeconds:120,count:items.length,news:items})};
