const PAGE_ROUTES=[
'/','/breaking/','/chatgpt/','/claude/','/gemini/','/ai-models/','/ai-video/','/ai-images/','/coding/','/hardware/','/robotics/','/business/','/it-news/','/cybersecurity/','/sysadmin/','/all-news/','/daily-brief/','/about/','/ai-tools/','/search/?q=OpenAI','/subscribe/',
'/bleepingcomputer/','/hacker-news/','/securityweek/','/ars-security/','/dark-reading/','/the-record/','/cybernews/','/techpowerup/','/the-register/',
'/topic-claude/','/topic-nvidia-earnings/','/topic-gemini/','/topic-sora/','/topic-ai-agents/',
'/tool-magai/','/tool-opusclip/','/tool-codestral/','/tool-leonardo-ai/','/tool-voicemod-ai/'
];
const ASSETS=['/favicon.svg','/app.css','/app.js','/responsive.css','/media-fix.css','/site-live.css','/site-live.js','/nav-cleanup.js','/mobile-nav-fix.css','/breaking-live.js','/sort-news.js'];
const APIS=['/api/news?category=all-news','/api/breaking-plus','/api/ai-tools','/api/source-news?source=techpowerup','/api/source-news?source=securityweek'];
const TARGETS=[...PAGE_ROUTES,...ASSETS,...APIS];
async function check(base,path){const c=new AbortController(),t=setTimeout(()=>c.abort(),6500);try{const r=await fetch(base+path,{method:'GET',signal:c.signal,headers:{'user-agent':'AI-News-Now-Health/3.0','cache-control':'no-cache'}});const ct=r.headers.get('content-type')||'';return{path,status:r.status,ok:r.ok,contentType:ct}}catch(e){return{path,status:0,ok:false,error:e?.name==='AbortError'?'timeout':String(e?.message||e)}}finally{clearTimeout(t)}}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let next=0;async function worker(){for(;;){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i])}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
module.exports=async function(req,res){const host=req.headers['x-forwarded-host']||req.headers.host,proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0],base=`${proto}://${String(host).split(',')[0].trim()}`;const results=await mapLimit(TARGETS,10,p=>check(base,p));const failures=results.filter(x=>!x.ok),ok=failures.length===0;res.setHeader('Cache-Control','no-store');res.status(ok?200:500).json({ok,checkedAt:new Date().toISOString(),count:results.length,pageCount:PAGE_ROUTES.length,assetCount:ASSETS.length,apiCount:APIS.length,failures,results})};