const baseFeeds=[
  {source:'TechCrunch',url:'https://techcrunch.com/category/artificial-intelligence/feed/'},
  {source:'The Verge',url:'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml'},
  {source:'VentureBeat',url:'https://venturebeat.com/category/ai/feed/'},
  {source:'Hugging Face',url:'https://huggingface.co/blog/feed.xml'}
];
const securityFeeds=[
  {source:'BleepingComputer',url:'https://www.bleepingcomputer.com/feed/'},
  {source:'The Hacker News',url:'https://thehackernews.com/feeds/posts/default'},
  {source:'SecurityWeek',url:'https://www.securityweek.com/feed/'},
  {source:'Ars Technica Security',url:'https://arstechnica.com/security/feed/'}
];
const itFeeds=[
  {source:'BleepingComputer',url:'https://www.bleepingcomputer.com/feed/'},
  {source:'Ars Technica',url:'https://feeds.arstechnica.com/arstechnica/index'}
];
const sysadminFeed={source:'r/sysadmin',url:'https://www.reddit.com/r/sysadmin/.rss'};
const categoryQueries={
  breaking:'artificial intelligence when:2d',chatgpt:'(ChatGPT OR OpenAI OR GPT OR Codex OR Sora) when:30d',claude:'(Claude OR Anthropic) when:60d',gemini:'(Gemini OR Google DeepMind OR Google AI) when:45d','ai-models':'("AI model" OR LLM OR reasoning model OR Llama OR Qwen OR Mistral OR DeepSeek) when:30d','ai-video':'("AI video" OR Sora OR Runway OR Veo OR Kling OR Luma OR Higgsfield) when:60d','ai-images':'("AI image" OR Midjourney OR Stable Diffusion OR Flux OR image generation) when:60d',coding:'("AI coding" OR coding agent OR Copilot OR Cursor OR Codex OR GitHub AI) when:45d',hardware:'(Nvidia OR AMD OR Intel OR GPU OR "AI chip" OR "AI hardware" OR data center) when:30d',robotics:'("AI robot" OR robotics OR humanoid OR autonomous robot) when:60d',business:'("AI startup" OR "AI funding" OR "AI business" OR acquisition OR valuation OR enterprise AI) when:30d','it-news':'("information technology" OR "enterprise technology" OR "cloud computing" OR "enterprise software" OR Microsoft OR Windows OR Linux OR "computer networking" OR "data storage" OR servers OR "data center" OR SaaS OR "IT infrastructure") when:14d',cybersecurity:'(cybersecurity OR "cyber attack" OR ransomware OR "data breach" OR malware OR "zero-day" OR vulnerability OR CISA OR phishing OR hacking OR "threat actor") when:14d',sysadmin:'(sysadmin OR "system administrator" OR "Windows Server" OR "Active Directory" OR "Microsoft 365 administration" OR "Exchange Server" OR "VMware vSphere" OR "Hyper-V" OR "Linux administration" OR "enterprise patching" OR "IT outage" OR "server administration") when:30d','topic-claude':'(Claude OR Anthropic) when:90d','topic-nvidia-earnings':'(Nvidia earnings OR Nvidia revenue OR Nvidia results OR Nvidia stock) when:90d','topic-gemini':'(Google Gemini OR Gemini AI OR Google DeepMind) when:90d','topic-sora':'(OpenAI Sora OR Sora video OR Sora AI) when:90d','topic-ai-agents':'("AI agents" OR agentic AI OR autonomous AI agents OR AI agent) when:60d','tool-magai':'(Magai OR "Magai AI") when:365d','tool-opusclip':'(OpusClip OR "Opus Clip" OR "OpusClip AI") when:365d','tool-codestral':'(Codestral OR "Mistral Codestral") when:365d','tool-leonardo-ai':'("Leonardo AI" OR "Leonardo.Ai") when:365d','tool-voicemod-ai':'(Voicemod OR "Voicemod AI") when:365d','all-news':'(artificial intelligence OR cybersecurity OR technology) when:7d',home:'(OpenAI OR Anthropic OR Google AI OR Microsoft AI OR Nvidia OR artificial intelligence OR cybersecurity OR AI model) when:7d'
};
const fallbackImages=['https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1800&q=90','https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1800&q=90','https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1800&q=90','https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1800&q=90','https://images.unsplash.com/photo-1535378917042-10a22c95931a?auto=format&fit=crop&w=1800&q=90','https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1800&q=90'];
const fallback=[['AI infrastructure spending continues to accelerate across the industry','https://www.nvidia.com/en-us/','NVIDIA',18,'Chipmakers, cloud providers and model labs continue investing heavily in next-generation AI compute infrastructure.',fallbackImages[2]],['New multimodal AI systems push toward more capable assistants','https://openai.com/news/','OpenAI',43,'The latest generation of AI assistants increasingly combines text, vision, tools and long-running tasks.',fallbackImages[0]],['Developers adopt coding agents for larger software tasks','https://github.blog/ai-and-ml/','GitHub',75,'Agentic coding tools are moving from autocomplete toward planning, editing, testing and reviewing complete changes.',fallbackImages[3]],['Open-weight model ecosystem keeps expanding','https://huggingface.co/blog','Hugging Face',138,'New open models are giving developers more choices for local inference, fine-tuning and private deployments.',fallbackImages[1]],['Generative video competition drives better creator tools','https://deepmind.google/models/veo/','Google',186,'AI video systems are improving consistency, control and production workflows for creators.',fallbackImages[5]]].map((x,i)=>({id:'fallback-'+i,title:x[0],link:x[1],source:x[2],publishedAt:new Date(Date.now()-x[3]*60000).toISOString(),description:x[4],image:x[5]}));
function decode(s=''){return String(s).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#8217;|&#39;|&apos;/g,"'").replace(/&#8220;|&#8221;|&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function clean(s=''){return decode(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function tag(b,n){const m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'));return m?clean(m[1]):''}
function attr(b,re){const m=b.match(re);return m?decode(m[1]):''}
function link(b){let d=tag(b,'link');if(d&&/^https?:/i.test(d))return d;let m=b.match(/<link[^>]+href=["']([^"']+)["']/i);return m?decode(m[1]):tag(b,'guid')}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h.toString(36)}
function feedImage(b){return attr(b,/<media:content[^>]+url=["']([^"']+)["']/i)||attr(b,/<enclosure[^>]+url=["']([^"']+)["'][^>]*type=["']image/i)||attr(b,/<enclosure[^>]+type=["']image[^"']*["'][^>]+url=["']([^"']+)["']/i)||attr(b,/<media:thumbnail[^>]+url=["']([^"']+)["']/i)||attr(b,/<img[^>]+src=["']([^"']+)["']/i)}
function parse(xml,source){let blocks=[...(xml.match(/<item\b[\s\S]*?<\/item>/gi)||[]),...(xml.match(/<entry\b[\s\S]*?<\/entry>/gi)||[])];return blocks.slice(0,70).map(b=>{let title=tag(b,'title')||'Untitled news story',url=link(b)||'#',description=(tag(b,'description')||tag(b,'summary')||tag(b,'content')).slice(0,320)||'Latest technology news and analysis.',date=tag(b,'pubDate')||tag(b,'published')||tag(b,'updated')||new Date().toISOString(),publishedAt;try{publishedAt=new Date(date).toISOString()}catch{publishedAt=new Date().toISOString()}return{id:hash(source+title+url),title,link:url,source,publishedAt,description,image:feedImage(b)}}).filter(x=>/^https?:\/\//i.test(x.link))}
async function getText(url,timeout=3000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 AI-News-Now/6.1','accept':'text/html,application/rss+xml,application/atom+xml,application/xml;q=0.9,*/*;q=0.8'},signal:c.signal,redirect:'follow'});if(!r.ok)throw Error(String(r.status));return{text:await r.text(),url:r.url}}finally{clearTimeout(t)}}
async function load(f){try{return parse((await getText(f.url)).text,f.source)}catch{return[]}}
function googleFeedFor(category,query=''){const q=query?`"${query}" when:365d`:(categoryQueries[category]||categoryQueries.home);return{source:'Google News',url:`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`}}
function imageKey(url=''){return String(url).toLowerCase().replace(/^https?:\/\//,'').split('#')[0].split('?')[0].replace(/\/$/,'')}
function resolvedImageUrl(n,i,origin,direct=''){const p=new URLSearchParams({article:String(n.link||''),seed:String(n.id||hash(n.title+n.link+i)),title:String(n.title||'News').slice(0,100),variant:String(i)});if(direct)p.set('image',direct);return `${origin}/api/article-image?${p.toString()}`}
function routeImagesThroughPublisher(items,origin){const seen=new Set();return items.map((n,i)=>{let direct=/^https?:\/\//i.test(n.image||'')?n.image:'',key=imageKey(direct);if(key&&seen.has(key))direct='';if(key)seen.add(key);return{...n,image:resolvedImageUrl(n,i,origin,direct)}})}
function uniqueFeeds(feeds){const seen=new Set();return feeds.filter(f=>{if(seen.has(f.url))return false;seen.add(f.url);return true})}

const TRUSTED=new Set(['TechCrunch','The Verge','VentureBeat','Hugging Face','BleepingComputer','The Hacker News','SecurityWeek','Ars Technica Security','Ars Technica']);
const MAJOR=['openai','chatgpt','anthropic','claude','google','gemini','deepmind','microsoft','nvidia','apple','amazon','aws','meta','amd','intel','cloudflare','cisco','oracle','salesforce','github'];
const IMPACT=['zero-day','zero day','actively exploited','critical vulnerability','ransomware','data breach','breach','cyberattack','cyber attack','major outage','global outage','outage','emergency patch','acquisition','acquires','merger','antitrust','lawsuit','regulation','ban ','recall','shutdown','launches','launched','unveils','unveiled','releases','released','funding','valuation','earnings','security incident'];
const TECHSPEC=['gpu','chip','semiconductor','data center','server','cloud','windows','linux','active directory','microsoft 365','model','llm','agent','robot','robotics','cybersecurity','vulnerability','malware','ransomware','infrastructure','developer','coding'];
const LOW=['school district','high school','college students','university workshop','hosts ai workshop','seminar','classroom','pastor','religious realm','dental professionals','psychiatric training','conference in october','dialogue series','local school','curriculum'];
function classify(n){const t=(n.title+' '+n.description).toLowerCase();if(/ransomware|malware|breach|vulnerab|zero.?day|cyber|hack|phishing|cisa|threat actor|security incident/.test(t))return'Cyber';if(/nvidia|amd|intel|gpu|chip|semiconductor|hardware|data center/.test(t))return'Hardware';if(/funding|valuation|acquisition|merger|revenue|earnings|startup|business|antitrust|lawsuit/.test(t))return'Business';if(/windows|linux|server|active directory|microsoft 365|exchange|vmware|hyper-v|sysadmin|network|cloud|outage|infrastructure/.test(t))return'IT';if(/openai|chatgpt|anthropic|claude|gemini|deepmind|llm|artificial intelligence|\bai\b|model|agent|sora|copilot/.test(t))return'AI';return'Tech'}
function why(topic,n){const t=(n.title+' '+n.description).toLowerCase();if(/outage|disruption/.test(t))return'Service availability may affect users, operations and dependent systems.';if(/zero.?day|critical vulnerab|actively exploited/.test(t))return'Security teams may need to review exposure, patches, mitigations and exploitation risk.';if(topic==='Cyber')return'This may change defensive priorities, incident response or organizational risk.';if(topic==='Hardware')return'This may affect compute capacity, pricing and infrastructure planning.';if(topic==='Business')return'This may reshape competition, investment, regulation or enterprise strategy.';if(topic==='IT')return'This may affect enterprise systems, administrators, cloud services or operations.';if(topic==='AI')return'This may change model capabilities, developer workflows or AI product adoption.';return'This is a notable technology development with potential industry impact.'}
function importance(n,category){const txt=(n.title+' '+n.description+' '+n.source).toLowerCase(),title=n.title.toLowerCase(),age=(Date.now()-new Date(n.publishedAt))/36e5;let s=0;if(age<=2)s+=55;else if(age<=6)s+=48;else if(age<=12)s+=41;else if(age<=24)s+=34;else if(age<=72)s+=24;else if(age<=168)s+=12;else s-=5;if(TRUSTED.has(n.source))s+=13;let major=0;for(const k of MAJOR)if(txt.includes(k))major++;s+=Math.min(major,3)*8;let impact=0;for(const k of IMPACT)if(txt.includes(k))impact++;s+=Math.min(impact,3)*13;let spec=0;for(const k of TECHSPEC)if(txt.includes(k))spec++;s+=Math.min(spec,4)*3;if(/breaking|critical|zero.?day|ransomware|breach|outage|acquisition|launches|releases/i.test(title))s+=12;if(/opinion\s*\||op-ed|prediction:/.test(title))s-=10;for(const k of LOW)if(txt.includes(k))s-=24;if(/medical|dental|psychiatric|health care|hospital/.test(txt)&&category!=='cybersecurity')s-=12;if(/artificial intelligence/.test(txt)&&major===0&&spec<2&&impact===0)s-=10;if(category==='cybersecurity'&&classify(n)==='Cyber')s+=16;if(category==='hardware'&&classify(n)==='Hardware')s+=14;if(category==='it-news'&&['IT','Hardware','Cyber'].includes(classify(n)))s+=10;if(category==='sysadmin'&&/windows|linux|server|active directory|microsoft 365|exchange|vmware|hyper-v|patch|outage|backup|network/.test(txt))s+=16;if(category==='business'&&classify(n)==='Business')s+=12;return Math.round(s)}
function addSignals(n,category){const topic=classify(n),score=importance(n,category);return{...n,topic,importance:score,whyItMatters:why(topic,n)}}

module.exports=async function(req,res){
  res.setHeader('Cache-Control','public, max-age=60, stale-while-revalidate=300');
  res.setHeader('CDN-Cache-Control','public, max-age=300, stale-while-revalidate=900');
  res.setHeader('Vercel-CDN-Cache-Control','public, max-age=300, stale-while-revalidate=900');
  const category=String(req.query?.category||'home').toLowerCase(),query=String(req.query?.q||'').trim().slice(0,120);
  let feeds;
  if(category==='cybersecurity') feeds=[googleFeedFor(category,query),...securityFeeds];
  else if(category==='it-news') feeds=[googleFeedFor(category,query),...itFeeds];
  else if(category==='sysadmin') feeds=[googleFeedFor(category,query),sysadminFeed,...securityFeeds];
  else if(category==='all-news') feeds=[googleFeedFor(category,query),...baseFeeds,...securityFeeds,...itFeeds];
  else feeds=[googleFeedFor(category,query),...baseFeeds];
  feeds=uniqueFeeds(feeds);
  let live=(await Promise.all(feeds.map(load))).flat(),pool=live.length>=12?live:[...live,...fallback],seen=new Set();
  const maxItems=category==='all-news'?80:60;
  let news=pool.filter(n=>{let k=n.title.toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').slice(0,11).join(' ');if(seen.has(k))return false;seen.add(k);return true}).map(n=>addSignals(n,category)).sort((a,b)=>b.importance-a.importance||+new Date(b.publishedAt)-+new Date(a.publishedAt)).slice(0,maxItems);
  const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0].trim(),host=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim(),origin=host?`${proto}://${host}`:'https://cert-forge-git-ai-news-now-site-cloud-drive.vercel.app';
  news=routeImagesThroughPublisher(news,origin);
  const sourceCounts=news.reduce((a,n)=>(a[n.source]=(a[n.source]||0)+1,a),{});
  res.status(200).json({updatedAt:new Date().toISOString(),category,query,count:news.length,ranking:'importance+recency',sourceCounts,news});
};
