const FEEDS=[
{source:'TechCrunch',url:'https://techcrunch.com/category/artificial-intelligence/feed/'},
{source:'VentureBeat',url:'https://venturebeat.com/category/ai/feed/'},
{source:'Google News',url:'https://news.google.com/rss/search?q=artificial+intelligence+when:2d&hl=en-US&gl=US&ceid=US:en'}
];
const FALLBACKS=[
'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1600&q=88',
'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1600&q=88',
'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1600&q=88',
'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=88',
'https://images.unsplash.com/photo-1535378917042-10a22c95931a?auto=format&fit=crop&w=1600&q=88'
];
function decode(s=''){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function strip(s=''){return decode(s).replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function tag(b,n){const m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'));return m?decode(m[1].trim()):''}
function attr(b,re){const m=b.match(re);return m?decode(m[1]):''}
function parse(xml,source){return[...xml.matchAll(/<item\b[\s\S]*?<\/item>/gi)].map((m,i)=>{const b=m[0],title=strip(tag(b,'title')),link=strip(tag(b,'link'))||attr(b,/<link[^>]+href=["']([^"']+)/i),description=strip(tag(b,'description')||tag(b,'content:encoded')).slice(0,420),published=strip(tag(b,'pubDate')||tag(b,'published')||tag(b,'dc:date'))||new Date().toISOString(),image=attr(b,/<media:(?:content|thumbnail)[^>]+url=["']([^"']+)["']/i)||attr(b,/<enclosure[^>]+url=["']([^"']+)["'][^>]*type=["']image/i)||attr(b,/<img[^>]+src=["']([^"']+)["']/i),creator=strip(tag(b,'dc:creator'));return{title,link,description,published,source:creator||source,image,rank:i}}).filter(x=>x.title&&/^https?:\/\//i.test(x.link))}
async function getText(url,timeout=6000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 AI-News-Now/1.0','accept':'text/html,application/rss+xml,application/xml;q=0.9,*/*;q=0.8'}});if(!r.ok)throw Error(String(r.status));return{text:await r.text(),url:r.url}}finally{clearTimeout(t)}}
async function enrich(item,index){if(item.image&&/^https?:\/\//i.test(item.image))return item;try{const{text,url}=await getText(item.link,3500),image=attr(text,/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)["']/i)||attr(text,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image/i)||attr(text,/<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"']+)["']/i);if(url&&!url.includes('news.google.com'))item.link=url;if(image)item.image=image.startsWith('//')?'https:'+image:image}catch{}if(!item.image)item.image=FALLBACKS[index%FALLBACKS.length];return item}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=900');res.setHeader('Content-Type','application/json; charset=utf-8');const settled=await Promise.allSettled(FEEDS.map(async f=>parse((await getText(f.url)).text,f.source)));let items=settled.flatMap(r=>r.status==='fulfilled'?r.value:[]),seen=new Set();items=items.filter(x=>{const k=x.title.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>new Date(b.published)-new Date(a.published)).slice(0,30);const top=await Promise.all(items.slice(0,14).map(enrich));items=[...top,...items.slice(14).map((x,i)=>({...x,image:x.image||FALLBACKS[(i+top.length)%FALLBACKS.length]}))];if(!items.length)items=[{title:'AI News Now is ready for live publisher feeds',link:'https://news.google.com/search?q=artificial%20intelligence',description:'The live feed service is temporarily unavailable. Open Google News for current artificial-intelligence coverage.',published:new Date().toISOString(),source:'AI News Now',image:FALLBACKS[0]}];res.status(200).json({updatedAt:new Date().toISOString(),count:items.length,items})};
